// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// LegacyRecurringProductPriceFixed - A recurring price for a product, i.e. a subscription.  **Deprecated**: The recurring interval should be set on the product itself.
type LegacyRecurringProductPriceFixed struct {
	CreatedAt string `json:"created_at,omitempty"`
	ModifiedAt string `json:"modified_at,omitempty"`
	Id RTID `json:"id,omitempty"`
	Source string `json:"source,omitempty"`
	AmountType string `json:"amount_type,omitempty"`
	PriceCurrency string `json:"price_currency,omitempty"`
	TaxBehavior string `json:"tax_behavior,omitempty"`
	IsArchived *bool `json:"is_archived,omitempty"`
	ProductId string `json:"product_id,omitempty"`
	Type string `json:"type,omitempty"`
	RecurringInterval string `json:"recurring_interval,omitempty"`
	PriceAmount int32 `json:"price_amount,omitempty"`
	Legacy *bool `json:"legacy,omitempty"`
}
