// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// CustomerCancellationReasonFilter - Filter by customer cancellation reason.
type CustomerCancellationReasonFilter struct {
}
