// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// DiscountPercentageRepeatDuration - Schema for a percentage discount that is applied on every invoice for a certain number of months.
type DiscountPercentageRepeatDuration struct {
	Duration string `json:"duration,omitempty"`
	DurationInMonths int32 `json:"duration_in_months,omitempty"`
	Type string `json:"type,omitempty"`
	BasisPoints int32 `json:"basis_points,omitempty"`
	CreatedAt string `json:"created_at,omitempty"`
	ModifiedAt string `json:"modified_at,omitempty"`
	Id RTID `json:"id,omitempty"`
	Metadata map[string]MetadataOutputTypeValue `json:"metadata,omitempty"`
	Name string `json:"name,omitempty"`
	Code string `json:"code,omitempty"`
	StartsAt string `json:"starts_at,omitempty"`
	EndsAt string `json:"ends_at,omitempty"`
	MaxRedemptions int32 `json:"max_redemptions,omitempty"`
	MaxRedemptionsPerCustomer int32 `json:"max_redemptions_per_customer,omitempty"`
	RedemptionsCount int32 `json:"redemptions_count,omitempty"`
	OrganizationId string `json:"organization_id,omitempty"`
	Products []DiscountProduct `json:"products,omitempty"`
}
