// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// FilterClauses - FilterClauses struct
type FilterClauses struct {
	Property string `json:"property,omitempty"`
	Operator string `json:"operator,omitempty"`
	Value    string `json:"value,omitempty"`
}
