// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ProductUpdatePricesInner - ProductUpdatePricesInner struct
type ProductUpdatePricesInner struct {
	Id string `json:"id,omitempty"`
	PriceCurrency string `json:"price_currency,omitempty"`
	TaxBehavior string `json:"tax_behavior,omitempty"`
	PriceAmount int32 `json:"price_amount,omitempty"`
	MinimumAmount int32 `json:"minimum_amount,omitempty"`
	MaximumAmount int32 `json:"maximum_amount,omitempty"`
	PresetAmount int32 `json:"preset_amount,omitempty"`
	SeatTiers *ProductPriceSeatTiersInput `json:"seat_tiers,omitempty"`
	MeterId string `json:"meter_id,omitempty"`
	UnitAmount interface{} `json:"unit_amount,omitempty"`
	CapAmount int32 `json:"cap_amount,omitempty"`
	AmountType string `json:"amount_type,omitempty"`
}
