// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// FilterClause - FilterClause struct
type FilterClause struct {
	Property string `json:"property,omitempty"`
	Operator string `json:"operator,omitempty"`
	Value interface{} `json:"value,omitempty"`
}
