// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// Order - Order struct
type Order struct {
	Id string `json:"id,omitempty"`
	CreatedAt string `json:"created_at,omitempty"`
	ModifiedAt string `json:"modified_at,omitempty"`
	Status string `json:"status,omitempty"`
	Paid *bool `json:"paid,omitempty"`
	SubtotalAmount int32 `json:"subtotal_amount,omitempty"`
	DiscountAmount int32 `json:"discount_amount,omitempty"`
	NetAmount int32 `json:"net_amount,omitempty"`
	TaxAmount int32 `json:"tax_amount,omitempty"`
	TotalAmount int32 `json:"total_amount,omitempty"`
	AppliedBalanceAmount int32 `json:"applied_balance_amount,omitempty"`
	DueAmount int32 `json:"due_amount,omitempty"`
	RefundedAmount int32 `json:"refunded_amount,omitempty"`
	RefundedTaxAmount int32 `json:"refunded_tax_amount,omitempty"`
	Currency string `json:"currency,omitempty"`
	BillingReason string `json:"billing_reason,omitempty"`
	BillingName string `json:"billing_name,omitempty"`
	BillingAddress *Address `json:"billing_address,omitempty"`
	InvoiceNumber string `json:"invoice_number,omitempty"`
	IsInvoiceGenerated *bool `json:"is_invoice_generated,omitempty"`
	ReceiptNumber string `json:"receipt_number,omitempty"`
	Seats int32 `json:"seats,omitempty"`
	CustomerId string `json:"customer_id,omitempty"`
	ProductId string `json:"product_id,omitempty"`
	DiscountId string `json:"discount_id,omitempty"`
	SubscriptionId string `json:"subscription_id,omitempty"`
	CheckoutId string `json:"checkout_id,omitempty"`
	NextPaymentAttemptAt string `json:"next_payment_attempt_at,omitempty"`
	Metadata map[string]CustomerMetadataValue `json:"metadata,omitempty"`
	CustomFieldData map[string]CustomFieldDataValue `json:"custom_field_data,omitempty"`
	PlatformFeeAmount int32 `json:"platform_fee_amount,omitempty"`
	PlatformFeeCurrency string `json:"platform_fee_currency,omitempty"`
	Customer *OrderCustomer `json:"customer,omitempty"`
	Product *OrderProduct `json:"product,omitempty"`
	Discount *OrderDiscount `json:"discount,omitempty"`
	Subscription *OrderSubscription `json:"subscription,omitempty"`
	Items []OrderItemSchema `json:"items,omitempty"`
	Description string `json:"description,omitempty"`
	RefundableAmount int32 `json:"refundable_amount,omitempty"`
	RefundableTaxAmount int32 `json:"refundable_tax_amount,omitempty"`
}
