// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// BenefitCustomUpdate - BenefitCustomUpdate struct
type BenefitCustomUpdate struct {
	Metadata    map[string]string        `json:"metadata,omitempty"`
	Description *string                  `json:"description,omitempty"`
	Visibility  *string                  `json:"visibility,omitempty"`
	Type        *string                  `json:"type,omitempty"`
	Properties  *BenefitCustomProperties `json:"properties,omitempty"`
}
