// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ListResourceSubscription - ListResourceSubscription struct
type ListResourceSubscription struct {
	Items []Subscription `json:"items,omitempty"`
	Pagination *Pagination `json:"pagination,omitempty"`
}
