// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// OrganizationCompanyLegalEntitySchema - OrganizationCompanyLegalEntitySchema struct
type OrganizationCompanyLegalEntitySchema struct {
	Type string `json:"type,omitempty"`
	RegisteredName string `json:"registered_name,omitempty"`
}
