// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ListResourceCustomer - ListResourceCustomer struct
type ListResourceCustomer struct {
	Items []Customer `json:"items,omitempty"`
	Pagination *Pagination `json:"pagination,omitempty"`
}
