// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ListResourceOrder - ListResourceOrder struct
type ListResourceOrder struct {
	Items []Order `json:"items,omitempty"`
	Pagination *Pagination `json:"pagination,omitempty"`
}
