// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// BenefitDownloadablesProperties - BenefitDownloadablesProperties struct
type BenefitDownloadablesProperties struct {
	Archived map[string]bool `json:"archived,omitempty"`
	Files []string `json:"files,omitempty"`
}
