// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// OrderCreate - Schema to create a draft order for an off-session charge.
type OrderCreate struct {
	CustomFieldData map[string]string `json:"custom_field_data,omitempty"`
	Metadata        map[string]string `json:"metadata,omitempty"`
	OrganizationId  string            `json:"organization_id,omitempty"`
	CustomerId      string            `json:"customer_id,omitempty"`
	ProductId       string            `json:"product_id,omitempty"`
	Currency        string            `json:"currency,omitempty"`
	Amount          int32             `json:"amount,omitempty"`
	Description     string            `json:"description,omitempty"`
}
