// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ValidationError - ValidationError struct
type ValidationError struct {
	Loc   []string               `json:"loc,omitempty"`
	Msg   string                 `json:"msg,omitempty"`
	Type  string                 `json:"type,omitempty"`
	Input interface{}            `json:"input,omitempty"`
	Ctx   map[string]interface{} `json:"ctx,omitempty"`
}
