// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// BenefitFeatureFlag - A benefit of type `feature_flag`.  Use it to grant feature flags with key-value metadata that can be queried via the API and webhooks.
type BenefitFeatureFlag struct {
	Id RTID `json:"id,omitempty"`
	CreatedAt string `json:"created_at,omitempty"`
	ModifiedAt string `json:"modified_at,omitempty"`
	Type string `json:"type,omitempty"`
	Description string `json:"description,omitempty"`
	Selectable *bool `json:"selectable,omitempty"`
	Deletable *bool `json:"deletable,omitempty"`
	IsDeleted *bool `json:"is_deleted,omitempty"`
	OrganizationId string `json:"organization_id,omitempty"`
	Metadata map[string]MetadataOutputTypeValue `json:"metadata,omitempty"`
	Visibility string `json:"visibility,omitempty"`
	Properties map[string]interface{} `json:"properties,omitempty"`
	VisibilityConfigurable *bool `json:"visibility_configurable,omitempty"`
}
