// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// CustomerCreate - CustomerCreate struct
type CustomerCreate struct {
	Metadata map[string]MetadataValue `json:"metadata,omitempty"`
	ExternalId string `json:"external_id,omitempty"`
	Name string `json:"name,omitempty"`
	BillingAddress *AddressInput `json:"billing_address,omitempty"`
	TaxId string `json:"tax_id,omitempty"`
	Locale string `json:"locale,omitempty"`
	OrganizationId string `json:"organization_id,omitempty"`
	Owner *MemberOwnerCreate `json:"owner,omitempty"`
	Type string `json:"type,omitempty"`
	Email string `json:"email,omitempty"`
}
