// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// Filter - Filter struct
type Filter struct {
	Conjunction string `json:"conjunction,omitempty"`
	Clauses []FilterClauses `json:"clauses,omitempty"`
}
