// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// WebhookEndpointUpdate - Schema to update a webhook endpoint.
type WebhookEndpointUpdate struct {
	Url string `json:"url,omitempty"`
	Name string `json:"name,omitempty"`
	Format string `json:"format,omitempty"`
	Events []WebhookEventType `json:"events,omitempty"`
	Enabled *bool `json:"enabled,omitempty"`
}
