// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// BenefitCreate - BenefitCreate struct
type BenefitCreate struct {
	Metadata                     map[string]string                          `json:"metadata,omitempty"`
	Description                  *string                                    `json:"description,omitempty"`
	OrganizationId               *string                                    `json:"organization_id,omitempty"`
	Visibility                   *string                                    `json:"visibility,omitempty"`
	CustomProperties             *BenefitCustomCreateProperties             `json:"custom_properties,omitempty"`
	DiscordProperties            *BenefitDiscordCreateProperties            `json:"discord_properties,omitempty"`
	GithubRepositoryProperties   *BenefitGitHubRepositoryCreateProperties   `json:"github_repository_properties,omitempty"`
	DownloadablesProperties      *BenefitDownloadablesCreateProperties      `json:"downloadables_properties,omitempty"`
	LicenseKeysProperties        *BenefitLicenseKeysCreateProperties        `json:"license_keys_properties,omitempty"`
	MeterCreditProperties        *BenefitMeterCreditCreateProperties        `json:"meter_credit_properties,omitempty"`
	FeatureFlagProperties        map[string]interface{}                     `json:"feature_flag_properties,omitempty"`
	SlackSharedChannelProperties *BenefitSlackSharedChannelCreateProperties `json:"slack_shared_channel_properties,omitempty"`
	Type                         *string                                    `json:"type,omitempty"`
}
