// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// MeterCreateAggregation - MeterCreateAggregation struct
type MeterCreateAggregation struct {
	CountFunc string `json:"count_func,omitempty"`
	AvgFunc string `json:"avg_func,omitempty"`
	UniqueFunc string `json:"unique_func,omitempty"`
	Property string `json:"property,omitempty"`
}
