// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// SsoEnforcementRequiresConnection - SsoEnforcementRequiresConnection struct
type SsoEnforcementRequiresConnection struct {
	Error string `json:"error,omitempty"`
	Detail string `json:"detail,omitempty"`
}
