// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// CustomerPortalUsageSettings - CustomerPortalUsageSettings struct
type CustomerPortalUsageSettings struct {
	Show *bool `json:"show,omitempty"`
}
