// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// UnitAmount - The price per unit in cents. Supports up to 12 decimal places.
type UnitAmount struct {
}
