// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// NotOpenCheckout - NotOpenCheckout struct
type NotOpenCheckout struct {
	Error string `json:"error,omitempty"`
	Detail string `json:"detail,omitempty"`
}
