// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// CustomFieldCreate - CustomFieldCreate struct
type CustomFieldCreate struct {
	Metadata map[string]string `json:"metadata,omitempty"`
	Slug string `json:"slug,omitempty"`
	Name string `json:"name,omitempty"`
	OrganizationId string `json:"organization_id,omitempty"`
	TextProperties *CustomFieldTextProperties `json:"text_properties,omitempty"`
	NumberProperties *CustomFieldNumberProperties `json:"number_properties,omitempty"`
	DateProperties *CustomFieldDateProperties `json:"date_properties,omitempty"`
	CheckboxProperties *CustomFieldCheckboxProperties `json:"checkbox_properties,omitempty"`
	SelectProperties *CustomFieldSelectProperties `json:"select_properties,omitempty"`
	Type string `json:"type,omitempty"`
}
