// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// CustomFieldCreateDate - Schema to create a custom field of type date.
type CustomFieldCreateDate struct {
	Metadata map[string]MetadataValue `json:"metadata,omitempty"`
	Type string `json:"type,omitempty"`
	Slug string `json:"slug,omitempty"`
	Name string `json:"name,omitempty"`
	OrganizationId string `json:"organization_id,omitempty"`
	Properties *CustomFieldDateProperties `json:"properties,omitempty"`
}
