// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// BenefitCreate - BenefitCreate struct
type BenefitCreate struct {
	Metadata map[string]MetadataValue `json:"metadata,omitempty"`
	Type string `json:"type,omitempty"`
	Description string `json:"description,omitempty"`
	OrganizationId string `json:"organization_id,omitempty"`
	Visibility string `json:"visibility,omitempty"`
	Properties *BenefitSlackSharedChannelCreateProperties `json:"properties,omitempty"`
}
