// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// CheckoutDiscountFixedOnceForeverDuration - Schema for a fixed amount discount that is applied once or forever.
type CheckoutDiscountFixedOnceForeverDuration struct {
	Duration string `json:"duration,omitempty"`
	Type string `json:"type,omitempty"`
	Amount int32 `json:"amount,omitempty"`
	Currency string `json:"currency,omitempty"`
	Amounts map[string]int32 `json:"amounts,omitempty"`
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Code string `json:"code,omitempty"`
}
