// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// OrderItemSchema - An order line item.
type OrderItemSchema struct {
	CreatedAt string `json:"created_at,omitempty"`
	ModifiedAt string `json:"modified_at,omitempty"`
	Id RTID `json:"id,omitempty"`
	Label string `json:"label,omitempty"`
	Amount int32 `json:"amount,omitempty"`
	TaxAmount int32 `json:"tax_amount,omitempty"`
	Proration *bool `json:"proration,omitempty"`
	ProductPriceId string `json:"product_price_id,omitempty"`
}
