// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// SubscriptionProrationBehavior - SubscriptionProrationBehavior struct
type SubscriptionProrationBehavior struct {
}
