// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// BenefitLicenseKeysProperties - BenefitLicenseKeysProperties struct
type BenefitLicenseKeysProperties struct {
	Prefix string `json:"prefix,omitempty"`
	Expires *BenefitLicenseKeyExpirationProperties `json:"expires,omitempty"`
	Activations *BenefitLicenseKeyActivationProperties `json:"activations,omitempty"`
	LimitUsage int32 `json:"limit_usage,omitempty"`
}
