// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// CustomFieldUpdateNumber - Schema to update a custom field of type number.
type CustomFieldUpdateNumber struct {
	Metadata map[string]MetadataValue `json:"metadata,omitempty"`
	Name string `json:"name,omitempty"`
	Slug string `json:"slug,omitempty"`
	Type string `json:"type,omitempty"`
	Properties *CustomFieldNumberProperties `json:"properties,omitempty"`
}
