// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// CountAggregation - CountAggregation struct
type CountAggregation struct {
	Func string `json:"func,omitempty"`
}
