// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// MetricDashboardUpdate - Schema for updating a metrics dashboard.
type MetricDashboardUpdate struct {
	Name string `json:"name,omitempty"`
	Metrics []string `json:"metrics,omitempty"`
}
