// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// Response403OrganizationsUpdate - Response403OrganizationsUpdate struct
type Response403OrganizationsUpdate struct {
	Error string `json:"error,omitempty"`
	Detail string `json:"detail,omitempty"`
}
