// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// BenefitUpdate - BenefitUpdate struct
type BenefitUpdate struct {
	Metadata    map[string]string                          `json:"metadata,omitempty"`
	Description *string                                    `json:"description,omitempty"`
	Visibility  *string                                    `json:"visibility,omitempty"`
	Type        *string                                    `json:"type,omitempty"`
	Properties  *BenefitSlackSharedChannelCreateProperties `json:"properties,omitempty"`
}
