// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// OrderUpdate - Schema to update an order.
type OrderUpdate struct {
	BillingName    string        `json:"billing_name,omitempty"`
	BillingAddress *AddressInput `json:"billing_address,omitempty"`
}
