// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// MemberUpdate - Schema for updating a member.
type MemberUpdate struct {
	Name string `json:"name,omitempty"`
	Email string `json:"email,omitempty"`
	Role string `json:"role,omitempty"`
}
