// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ProductPriceCustom - A pay-what-you-want price for a product.
type ProductPriceCustom struct {
	CreatedAt string `json:"created_at,omitempty"`
	ModifiedAt string `json:"modified_at,omitempty"`
	Id RTID `json:"id,omitempty"`
	Source string `json:"source,omitempty"`
	AmountType string `json:"amount_type,omitempty"`
	PriceCurrency string `json:"price_currency,omitempty"`
	TaxBehavior string `json:"tax_behavior,omitempty"`
	IsArchived *bool `json:"is_archived,omitempty"`
	ProductId string `json:"product_id,omitempty"`
	MinimumAmount int32 `json:"minimum_amount,omitempty"`
	MaximumAmount int32 `json:"maximum_amount,omitempty"`
	PresetAmount int32 `json:"preset_amount,omitempty"`
}
