// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// MeterCreateAggregation - The aggregation to apply on the filtered events to calculate the meter.
type MeterCreateAggregation struct {
	Property string `json:"property,omitempty"`
	Func     string `json:"func,omitempty"`
}
