// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ExternalCustomerIdFilter - Filter by customer external ID.
type ExternalCustomerIdFilter struct {
}
