// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// CheckoutForbiddenError - CheckoutForbiddenError struct
type CheckoutForbiddenError struct {
	Error string `json:"error,omitempty"`
	Detail string `json:"detail,omitempty"`
}
