// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// BenefitPublic - BenefitPublic struct
type BenefitPublic struct {
	Id RTID `json:"id,omitempty"`
	CreatedAt string `json:"created_at,omitempty"`
	ModifiedAt string `json:"modified_at,omitempty"`
	Type string `json:"type,omitempty"`
	Description string `json:"description,omitempty"`
	Selectable *bool `json:"selectable,omitempty"`
	Deletable *bool `json:"deletable,omitempty"`
	IsDeleted *bool `json:"is_deleted,omitempty"`
	OrganizationId string `json:"organization_id,omitempty"`
}
