// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ListResourceOrganization - ListResourceOrganization struct
type ListResourceOrganization struct {
	Items []Organization `json:"items,omitempty"`
	Pagination *Pagination `json:"pagination,omitempty"`
}
