// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// TrialEnd - Set or extend the trial period of the subscription. If set to `now`, the trial will end immediately.
type TrialEnd struct {
}
