// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ListResourceMeter - ListResourceMeter struct
type ListResourceMeter struct {
	Items []Meter `json:"items,omitempty"`
	Pagination *Pagination `json:"pagination,omitempty"`
}
