// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// OrganizationSocialPlatforms - OrganizationSocialPlatforms struct
type OrganizationSocialPlatforms struct {
}
