// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ListResourceProduct - ListResourceProduct struct
type ListResourceProduct struct {
	Items []Product `json:"items,omitempty"`
	Pagination *Pagination `json:"pagination,omitempty"`
}
