// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// CustomerPortalCustomerSettings - CustomerPortalCustomerSettings struct
type CustomerPortalCustomerSettings struct {
	AllowEmailChange *bool `json:"allow_email_change,omitempty"`
}
