// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// BenefitLicenseKeyActivationCreateProperties - BenefitLicenseKeyActivationCreateProperties struct
type BenefitLicenseKeyActivationCreateProperties struct {
	Limit               int32 `json:"limit,omitempty"`
	EnableCustomerAdmin *bool `json:"enable_customer_admin,omitempty"`
}
