// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// CustomFieldCheckboxProperties - CustomFieldCheckboxProperties struct
type CustomFieldCheckboxProperties struct {
	FormLabel       *string `json:"form_label,omitempty"`
	FormHelpText    *string `json:"form_help_text,omitempty"`
	FormPlaceholder *string `json:"form_placeholder,omitempty"`
}
