// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// AlreadyActiveSubscriptionError - AlreadyActiveSubscriptionError struct
type AlreadyActiveSubscriptionError struct {
	Error string `json:"error,omitempty"`
	Detail string `json:"detail,omitempty"`
}
