// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// SubscriptionLocked - SubscriptionLocked struct
type SubscriptionLocked struct {
	Error string `json:"error,omitempty"`
	Detail string `json:"detail,omitempty"`
}
