// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// BenefitGitHubRepositoryUpdate - BenefitGitHubRepositoryUpdate struct
type BenefitGitHubRepositoryUpdate struct {
	Metadata    map[string]string                        `json:"metadata,omitempty"`
	Description string                                   `json:"description,omitempty"`
	Type        string                                   `json:"type,omitempty"`
	Properties  *BenefitGitHubRepositoryCreateProperties `json:"properties,omitempty"`
}
