// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// CheckoutUpdate - Update an existing checkout session using an access token.
type CheckoutUpdate struct {
	CustomFieldData        map[string]string `json:"custom_field_data,omitempty"`
	ProductId              string            `json:"product_id,omitempty"`
	ProductPriceId         string            `json:"product_price_id,omitempty"`
	Amount                 int32             `json:"amount,omitempty"`
	Seats                  int32             `json:"seats,omitempty"`
	IsBusinessCustomer     *bool             `json:"is_business_customer,omitempty"`
	CustomerName           string            `json:"customer_name,omitempty"`
	CustomerEmail          string            `json:"customer_email,omitempty"`
	CustomerBillingName    string            `json:"customer_billing_name,omitempty"`
	CustomerBillingAddress *AddressInput     `json:"customer_billing_address,omitempty"`
	CustomerTaxId          string            `json:"customer_tax_id,omitempty"`
	Locale                 string            `json:"locale,omitempty"`
	TrialInterval          string            `json:"trial_interval,omitempty"`
	TrialIntervalCount     int32             `json:"trial_interval_count,omitempty"`
	Metadata               map[string]string `json:"metadata,omitempty"`
	Currency               string            `json:"currency,omitempty"`
	DiscountId             string            `json:"discount_id,omitempty"`
	AllowDiscountCodes     *bool             `json:"allow_discount_codes,omitempty"`
	RequireBillingAddress  *bool             `json:"require_billing_address,omitempty"`
	AllowTrial             *bool             `json:"allow_trial,omitempty"`
	CustomerIpAddress      string            `json:"customer_ip_address,omitempty"`
	CustomerMetadata       map[string]string `json:"customer_metadata,omitempty"`
	SuccessUrl             string            `json:"success_url,omitempty"`
	ReturnUrl              string            `json:"return_url,omitempty"`
	EmbedOrigin            string            `json:"embed_origin,omitempty"`
}
