// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// CustomFieldCreate - CustomFieldCreate struct
type CustomFieldCreate struct {
	Metadata map[string]MetadataValue `json:"metadata,omitempty"`
	Type string `json:"type,omitempty"`
	Slug string `json:"slug,omitempty"`
	Name string `json:"name,omitempty"`
	OrganizationId string `json:"organization_id,omitempty"`
	Properties *CustomFieldSelectProperties `json:"properties,omitempty"`
}
