// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"context"
	"fmt"

	"encoding/json"


	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	"github.com/n-at-han-k/terraform-provider-polar/internal/client"
)

var _ datasource.DataSource = &BenefitDataSource{}

func NewBenefitDataSource() datasource.DataSource {
	return &BenefitDataSource{}
}

type BenefitDataSource struct {
	client *client.Client
}

func (d *BenefitDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_benefit"
}

func (d *BenefitDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Fetches a benefit data source.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:    true,
				Description: "The ID of the benefit.",
			},
			"created_at": schema.StringAttribute{
				Computed:    true,
				Description: "Creation timestamp of the object.",
			},
			"modified_at": schema.StringAttribute{
				Computed:    true,
				Description: "Last modification timestamp of the object.",
			},
			"metadata": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"description": schema.StringAttribute{
				Required:    true,
				Description: "The description of the benefit.",
			},
			"organization_id": schema.StringAttribute{
				Computed:    true,
				Description: "The ID of the organization owning the benefit.",
			},
			"visibility": schema.StringAttribute{
				Computed:    true,
				Description: "The visibility of the benefit in the customer portal.",
			},
			"custom_properties": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"discord_properties": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"github_repository_properties": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"downloadables_properties": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"license_keys_properties": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"meter_credit_properties": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"feature_flag_properties": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "Properties for a benefit of type `feature_flag`.",
			},
			"slack_shared_channel_properties": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"type": schema.StringAttribute{
				Required:    true,
				Description: "Which variant this is. Selects which of the optional blocks above applies.",
			},
		},
	}
}

func (d *BenefitDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Data Source Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}

	d.client = c
}

func (d *BenefitDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config BenefitModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	respBody, err := d.client.DoRequest(ctx, "GET", fmt.Sprintf("/benefits/%v", config.Id.ValueString()), nil)
	if err != nil {
		resp.Diagnostics.AddError("Error reading benefit", err.Error())
		return
	}

	var result client.Benefit
	if err := json.Unmarshal(respBody, &result); err != nil {
		resp.Diagnostics.AddError("Error parsing response", err.Error())
		return
	}

	config.FromClientModel(&result)

	tflog.Trace(ctx, "read benefit data source")
	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
