// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"encoding/json"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/n-at-han-k/terraform-provider-polar/internal/client"
)

// BenefitModel is the Terraform model for benefit.
type BenefitModel struct {
	Id                           types.String                              `tfsdk:"id"`
	Metadata                     types.Map                                 `tfsdk:"metadata"`
	Description                  types.String                              `tfsdk:"description"`
	Visibility                   types.String                              `tfsdk:"visibility"`
	CustomProperties             *BenefitCustomPropertiesModel             `tfsdk:"custom_properties"`
	DiscordProperties            *BenefitDiscordPropertiesModel            `tfsdk:"discord_properties"`
	GithubRepositoryProperties   *BenefitGithubRepositoryPropertiesModel   `tfsdk:"github_repository_properties"`
	DownloadablesProperties      *BenefitDownloadablesPropertiesModel      `tfsdk:"downloadables_properties"`
	LicenseKeysProperties        *BenefitLicenseKeysPropertiesModel        `tfsdk:"license_keys_properties"`
	MeterCreditProperties        *BenefitMeterCreditPropertiesModel        `tfsdk:"meter_credit_properties"`
	FeatureFlagProperties        jsontypes.Normalized                      `tfsdk:"feature_flag_properties"`
	SlackSharedChannelProperties *BenefitSlackSharedChannelPropertiesModel `tfsdk:"slack_shared_channel_properties"`
	Type                         types.String                              `tfsdk:"type"`
}

// BenefitCustomPropertiesModel is one `custom_properties` block.
//
// A STRUCT WITH tfsdk TAGS, not a types.Object: terraform-plugin-framework
// reflects over these, so a slice of them is a ListNestedAttribute and a
// pointer to one is a SingleNestedAttribute, with no AttributeTypes map to keep
// in step with the fields by hand.
type BenefitCustomPropertiesModel struct {
	Note types.String `tfsdk:"note"`
}

// ToClientModel converts one block to the client type the request carries.
func (m *BenefitCustomPropertiesModel) ToClientModel() (*client.BenefitCustomCreateProperties, error) {
	out := &client.BenefitCustomCreateProperties{}
	if !m.Note.IsNull() && !m.Note.IsUnknown() {
		Note := m.Note.ValueString()
		out.Note = &Note
	}
	return out, nil
}

// FromClientModel fills one block from what the server answered.
//
// EVERY CHILD IS WRITTEN, not only the ones the configuration set, because they
// are Optional AND Computed: Polar fills in a price's currency and tax
// behaviour, and a Computed attribute left unknown after an apply is "provider
// returned invalid result object after apply".
func (m *BenefitCustomPropertiesModel) FromClientModel(c *client.BenefitCustomCreateProperties) {
	// NIL IS ABSENT. The server omitted it, so state says null rather than
	// Go's zero -- otherwise the next plan proposes removing a value nobody set.
	if c.Note != nil {
		m.Note = types.StringValue(*c.Note)
	} else {
		m.Note = types.StringNull()
	}
}

// BenefitDiscordPropertiesModel is one `discord_properties` block.
//
// A STRUCT WITH tfsdk TAGS, not a types.Object: terraform-plugin-framework
// reflects over these, so a slice of them is a ListNestedAttribute and a
// pointer to one is a SingleNestedAttribute, with no AttributeTypes map to keep
// in step with the fields by hand.
type BenefitDiscordPropertiesModel struct {
	GuildToken types.String `tfsdk:"guild_token"`
	RoleId     types.String `tfsdk:"role_id"`
	KickMember types.Bool   `tfsdk:"kick_member"`
}

// ToClientModel converts one block to the client type the request carries.
func (m *BenefitDiscordPropertiesModel) ToClientModel() (*client.BenefitDiscordCreateProperties, error) {
	out := &client.BenefitDiscordCreateProperties{}
	if !m.GuildToken.IsNull() && !m.GuildToken.IsUnknown() {
		out.GuildToken = m.GuildToken.ValueString()
	}
	if !m.RoleId.IsNull() && !m.RoleId.IsUnknown() {
		out.RoleId = m.RoleId.ValueString()
	}
	if !m.KickMember.IsNull() && !m.KickMember.IsUnknown() {
		KickMember := m.KickMember.ValueBool()
		out.KickMember = &KickMember
	}
	return out, nil
}

// FromClientModel fills one block from what the server answered.
//
// EVERY CHILD IS WRITTEN, not only the ones the configuration set, because they
// are Optional AND Computed: Polar fills in a price's currency and tax
// behaviour, and a Computed attribute left unknown after an apply is "provider
// returned invalid result object after apply".
func (m *BenefitDiscordPropertiesModel) FromClientModel(c *client.BenefitDiscordCreateProperties) {
	m.GuildToken = types.StringValue(c.GuildToken)
	m.RoleId = types.StringValue(c.RoleId)
	if c.KickMember != nil {
		m.KickMember = types.BoolValue(*c.KickMember)
	} else {
		m.KickMember = types.BoolNull()
	}
}

// BenefitGithubRepositoryPropertiesModel is one `github_repository_properties` block.
//
// A STRUCT WITH tfsdk TAGS, not a types.Object: terraform-plugin-framework
// reflects over these, so a slice of them is a ListNestedAttribute and a
// pointer to one is a SingleNestedAttribute, with no AttributeTypes map to keep
// in step with the fields by hand.
type BenefitGithubRepositoryPropertiesModel struct {
	RepositoryOwner types.String `tfsdk:"repository_owner"`
	RepositoryName  types.String `tfsdk:"repository_name"`
	Permission      types.String `tfsdk:"permission"`
}

// ToClientModel converts one block to the client type the request carries.
func (m *BenefitGithubRepositoryPropertiesModel) ToClientModel() (*client.BenefitGitHubRepositoryCreateProperties, error) {
	out := &client.BenefitGitHubRepositoryCreateProperties{}
	if !m.RepositoryOwner.IsNull() && !m.RepositoryOwner.IsUnknown() {
		out.RepositoryOwner = m.RepositoryOwner.ValueString()
	}
	if !m.RepositoryName.IsNull() && !m.RepositoryName.IsUnknown() {
		out.RepositoryName = m.RepositoryName.ValueString()
	}
	if !m.Permission.IsNull() && !m.Permission.IsUnknown() {
		out.Permission = m.Permission.ValueString()
	}
	return out, nil
}

// FromClientModel fills one block from what the server answered.
//
// EVERY CHILD IS WRITTEN, not only the ones the configuration set, because they
// are Optional AND Computed: Polar fills in a price's currency and tax
// behaviour, and a Computed attribute left unknown after an apply is "provider
// returned invalid result object after apply".
func (m *BenefitGithubRepositoryPropertiesModel) FromClientModel(c *client.BenefitGitHubRepositoryCreateProperties) {
	m.RepositoryOwner = types.StringValue(c.RepositoryOwner)
	m.RepositoryName = types.StringValue(c.RepositoryName)
	m.Permission = types.StringValue(c.Permission)
}

// BenefitDownloadablesPropertiesModel is one `downloadables_properties` block.
//
// A STRUCT WITH tfsdk TAGS, not a types.Object: terraform-plugin-framework
// reflects over these, so a slice of them is a ListNestedAttribute and a
// pointer to one is a SingleNestedAttribute, with no AttributeTypes map to keep
// in step with the fields by hand.
type BenefitDownloadablesPropertiesModel struct {
	Archived types.Map  `tfsdk:"archived"`
	Files    types.List `tfsdk:"files"`
}

// ToClientModel converts one block to the client type the request carries.
func (m *BenefitDownloadablesPropertiesModel) ToClientModel() (*client.BenefitDownloadablesCreateProperties, error) {
	out := &client.BenefitDownloadablesCreateProperties{}
	return out, nil
}

// FromClientModel fills one block from what the server answered.
//
// EVERY CHILD IS WRITTEN, not only the ones the configuration set, because they
// are Optional AND Computed: Polar fills in a price's currency and tax
// behaviour, and a Computed attribute left unknown after an apply is "provider
// returned invalid result object after apply".
func (m *BenefitDownloadablesPropertiesModel) FromClientModel(c *client.BenefitDownloadablesCreateProperties) {
}

// BenefitLicenseKeysPropertiesModel is one `license_keys_properties` block.
//
// A STRUCT WITH tfsdk TAGS, not a types.Object: terraform-plugin-framework
// reflects over these, so a slice of them is a ListNestedAttribute and a
// pointer to one is a SingleNestedAttribute, with no AttributeTypes map to keep
// in step with the fields by hand.
type BenefitLicenseKeysPropertiesModel struct {
	Prefix      types.String                                       `tfsdk:"prefix"`
	Expires     *BenefitLicenseKeysPropertiesModelExpiresModel     `tfsdk:"expires"`
	Activations *BenefitLicenseKeysPropertiesModelActivationsModel `tfsdk:"activations"`
	LimitUsage  types.Int64                                        `tfsdk:"limit_usage"`
}

// ToClientModel converts one block to the client type the request carries.
func (m *BenefitLicenseKeysPropertiesModel) ToClientModel() (*client.BenefitLicenseKeysCreateProperties, error) {
	out := &client.BenefitLicenseKeysCreateProperties{}
	if !m.Prefix.IsNull() && !m.Prefix.IsUnknown() {
		Prefix := m.Prefix.ValueString()
		out.Prefix = &Prefix
	}
	if !m.LimitUsage.IsNull() && !m.LimitUsage.IsUnknown() {
		LimitUsage := int32(m.LimitUsage.ValueInt64())
		out.LimitUsage = &LimitUsage
	}
	return out, nil
}

// FromClientModel fills one block from what the server answered.
//
// EVERY CHILD IS WRITTEN, not only the ones the configuration set, because they
// are Optional AND Computed: Polar fills in a price's currency and tax
// behaviour, and a Computed attribute left unknown after an apply is "provider
// returned invalid result object after apply".
func (m *BenefitLicenseKeysPropertiesModel) FromClientModel(c *client.BenefitLicenseKeysCreateProperties) {
	// NIL IS ABSENT. The server omitted it, so state says null rather than
	// Go's zero -- otherwise the next plan proposes removing a value nobody set.
	if c.Prefix != nil {
		m.Prefix = types.StringValue(*c.Prefix)
	} else {
		m.Prefix = types.StringNull()
	}
	// NIL IS ABSENT. The server omitted it, so state says null rather than
	// Go's zero -- otherwise the next plan proposes removing a value nobody set.
	if c.LimitUsage != nil {
		m.LimitUsage = types.Int64Value(int64(*c.LimitUsage))
	} else {
		m.LimitUsage = types.Int64Null()
	}
}

// BenefitLicenseKeysPropertiesModelExpiresModel is one `expires` block.
//
// A STRUCT WITH tfsdk TAGS, not a types.Object: terraform-plugin-framework
// reflects over these, so a slice of them is a ListNestedAttribute and a
// pointer to one is a SingleNestedAttribute, with no AttributeTypes map to keep
// in step with the fields by hand.
type BenefitLicenseKeysPropertiesModelExpiresModel struct {
	Ttl       types.Int64  `tfsdk:"ttl"`
	Timeframe types.String `tfsdk:"timeframe"`
}

// ToClientModel converts one block to the client type the request carries.
func (m *BenefitLicenseKeysPropertiesModelExpiresModel) ToClientModel() (*client.BenefitLicenseKeyExpirationProperties, error) {
	out := &client.BenefitLicenseKeyExpirationProperties{}
	if !m.Ttl.IsNull() && !m.Ttl.IsUnknown() {
		out.Ttl = int32(m.Ttl.ValueInt64())
	}
	if !m.Timeframe.IsNull() && !m.Timeframe.IsUnknown() {
		out.Timeframe = m.Timeframe.ValueString()
	}
	return out, nil
}

// FromClientModel fills one block from what the server answered.
//
// EVERY CHILD IS WRITTEN, not only the ones the configuration set, because they
// are Optional AND Computed: Polar fills in a price's currency and tax
// behaviour, and a Computed attribute left unknown after an apply is "provider
// returned invalid result object after apply".
func (m *BenefitLicenseKeysPropertiesModelExpiresModel) FromClientModel(c *client.BenefitLicenseKeyExpirationProperties) {
	m.Ttl = types.Int64Value(int64(c.Ttl))
	m.Timeframe = types.StringValue(c.Timeframe)
}

// BenefitLicenseKeysPropertiesModelActivationsModel is one `activations` block.
//
// A STRUCT WITH tfsdk TAGS, not a types.Object: terraform-plugin-framework
// reflects over these, so a slice of them is a ListNestedAttribute and a
// pointer to one is a SingleNestedAttribute, with no AttributeTypes map to keep
// in step with the fields by hand.
type BenefitLicenseKeysPropertiesModelActivationsModel struct {
	Limit               types.Int64 `tfsdk:"limit"`
	EnableCustomerAdmin types.Bool  `tfsdk:"enable_customer_admin"`
}

// ToClientModel converts one block to the client type the request carries.
func (m *BenefitLicenseKeysPropertiesModelActivationsModel) ToClientModel() (*client.BenefitLicenseKeyActivationCreateProperties, error) {
	out := &client.BenefitLicenseKeyActivationCreateProperties{}
	if !m.Limit.IsNull() && !m.Limit.IsUnknown() {
		out.Limit = int32(m.Limit.ValueInt64())
	}
	if !m.EnableCustomerAdmin.IsNull() && !m.EnableCustomerAdmin.IsUnknown() {
		EnableCustomerAdmin := m.EnableCustomerAdmin.ValueBool()
		out.EnableCustomerAdmin = &EnableCustomerAdmin
	}
	return out, nil
}

// FromClientModel fills one block from what the server answered.
//
// EVERY CHILD IS WRITTEN, not only the ones the configuration set, because they
// are Optional AND Computed: Polar fills in a price's currency and tax
// behaviour, and a Computed attribute left unknown after an apply is "provider
// returned invalid result object after apply".
func (m *BenefitLicenseKeysPropertiesModelActivationsModel) FromClientModel(c *client.BenefitLicenseKeyActivationCreateProperties) {
	m.Limit = types.Int64Value(int64(c.Limit))
	if c.EnableCustomerAdmin != nil {
		m.EnableCustomerAdmin = types.BoolValue(*c.EnableCustomerAdmin)
	} else {
		m.EnableCustomerAdmin = types.BoolNull()
	}
}

// BenefitMeterCreditPropertiesModel is one `meter_credit_properties` block.
//
// A STRUCT WITH tfsdk TAGS, not a types.Object: terraform-plugin-framework
// reflects over these, so a slice of them is a ListNestedAttribute and a
// pointer to one is a SingleNestedAttribute, with no AttributeTypes map to keep
// in step with the fields by hand.
type BenefitMeterCreditPropertiesModel struct {
	Units    types.Int64  `tfsdk:"units"`
	Rollover types.Bool   `tfsdk:"rollover"`
	MeterId  types.String `tfsdk:"meter_id"`
}

// ToClientModel converts one block to the client type the request carries.
func (m *BenefitMeterCreditPropertiesModel) ToClientModel() (*client.BenefitMeterCreditCreateProperties, error) {
	out := &client.BenefitMeterCreditCreateProperties{}
	if !m.Units.IsNull() && !m.Units.IsUnknown() {
		out.Units = int32(m.Units.ValueInt64())
	}
	if !m.Rollover.IsNull() && !m.Rollover.IsUnknown() {
		Rollover := m.Rollover.ValueBool()
		out.Rollover = &Rollover
	}
	if !m.MeterId.IsNull() && !m.MeterId.IsUnknown() {
		out.MeterId = m.MeterId.ValueString()
	}
	return out, nil
}

// FromClientModel fills one block from what the server answered.
//
// EVERY CHILD IS WRITTEN, not only the ones the configuration set, because they
// are Optional AND Computed: Polar fills in a price's currency and tax
// behaviour, and a Computed attribute left unknown after an apply is "provider
// returned invalid result object after apply".
func (m *BenefitMeterCreditPropertiesModel) FromClientModel(c *client.BenefitMeterCreditCreateProperties) {
	m.Units = types.Int64Value(int64(c.Units))
	if c.Rollover != nil {
		m.Rollover = types.BoolValue(*c.Rollover)
	} else {
		m.Rollover = types.BoolNull()
	}
	m.MeterId = types.StringValue(c.MeterId)
}

// BenefitSlackSharedChannelPropertiesModel is one `slack_shared_channel_properties` block.
//
// A STRUCT WITH tfsdk TAGS, not a types.Object: terraform-plugin-framework
// reflects over these, so a slice of them is a ListNestedAttribute and a
// pointer to one is a SingleNestedAttribute, with no AttributeTypes map to keep
// in step with the fields by hand.
type BenefitSlackSharedChannelPropertiesModel struct {
	SlackIntegrationId  types.String `tfsdk:"slack_integration_id"`
	ChannelNameTemplate types.String `tfsdk:"channel_name_template"`
	Private             types.Bool   `tfsdk:"private"`
	WelcomeMessage      types.String `tfsdk:"welcome_message"`
	ArchiveOnRevoke     types.Bool   `tfsdk:"archive_on_revoke"`
	TeamInvitees        types.List   `tfsdk:"team_invitees"`
}

// ToClientModel converts one block to the client type the request carries.
func (m *BenefitSlackSharedChannelPropertiesModel) ToClientModel() (*client.BenefitSlackSharedChannelCreateProperties, error) {
	out := &client.BenefitSlackSharedChannelCreateProperties{}
	if !m.SlackIntegrationId.IsNull() && !m.SlackIntegrationId.IsUnknown() {
		out.SlackIntegrationId = m.SlackIntegrationId.ValueString()
	}
	if !m.ChannelNameTemplate.IsNull() && !m.ChannelNameTemplate.IsUnknown() {
		out.ChannelNameTemplate = m.ChannelNameTemplate.ValueString()
	}
	if !m.Private.IsNull() && !m.Private.IsUnknown() {
		Private := m.Private.ValueBool()
		out.Private = &Private
	}
	if !m.WelcomeMessage.IsNull() && !m.WelcomeMessage.IsUnknown() {
		WelcomeMessage := m.WelcomeMessage.ValueString()
		out.WelcomeMessage = &WelcomeMessage
	}
	if !m.ArchiveOnRevoke.IsNull() && !m.ArchiveOnRevoke.IsUnknown() {
		ArchiveOnRevoke := m.ArchiveOnRevoke.ValueBool()
		out.ArchiveOnRevoke = &ArchiveOnRevoke
	}
	return out, nil
}

// FromClientModel fills one block from what the server answered.
//
// EVERY CHILD IS WRITTEN, not only the ones the configuration set, because they
// are Optional AND Computed: Polar fills in a price's currency and tax
// behaviour, and a Computed attribute left unknown after an apply is "provider
// returned invalid result object after apply".
func (m *BenefitSlackSharedChannelPropertiesModel) FromClientModel(c *client.BenefitSlackSharedChannelCreateProperties) {
	m.SlackIntegrationId = types.StringValue(c.SlackIntegrationId)
	m.ChannelNameTemplate = types.StringValue(c.ChannelNameTemplate)
	if c.Private != nil {
		m.Private = types.BoolValue(*c.Private)
	} else {
		m.Private = types.BoolNull()
	}
	// NIL IS ABSENT. The server omitted it, so state says null rather than
	// Go's zero -- otherwise the next plan proposes removing a value nobody set.
	if c.WelcomeMessage != nil {
		m.WelcomeMessage = types.StringValue(*c.WelcomeMessage)
	} else {
		m.WelcomeMessage = types.StringNull()
	}
	if c.ArchiveOnRevoke != nil {
		m.ArchiveOnRevoke = types.BoolValue(*c.ArchiveOnRevoke)
	} else {
		m.ArchiveOnRevoke = types.BoolNull()
	}
}

// ToClientModel converts a Terraform model to a client model.
func (m *BenefitModel) ToClientModel() (*client.BenefitCreate, error) {
	out := &client.BenefitCreate{}
	if !m.Metadata.IsNull() && !m.Metadata.IsUnknown() {
		out.Metadata = make(map[string]string, len(m.Metadata.Elements()))
		for key, element := range m.Metadata.Elements() {
			out.Metadata[key] = element.(types.String).ValueString()
		}
	}
	if !m.Description.IsNull() && !m.Description.IsUnknown() {
		out.Description = m.Description.ValueString()
	}
	if !m.Visibility.IsNull() && !m.Visibility.IsUnknown() {
		Visibility := m.Visibility.ValueString()
		out.Visibility = &Visibility
	}
	if m.CustomProperties != nil {
		converted, err := m.CustomProperties.ToClientModel()
		if err != nil {
			return out, fmt.Errorf("custom_properties: %w", err)
		}
		out.CustomProperties = converted
	}
	if m.DiscordProperties != nil {
		converted, err := m.DiscordProperties.ToClientModel()
		if err != nil {
			return out, fmt.Errorf("discord_properties: %w", err)
		}
		out.DiscordProperties = converted
	}
	if m.GithubRepositoryProperties != nil {
		converted, err := m.GithubRepositoryProperties.ToClientModel()
		if err != nil {
			return out, fmt.Errorf("github_repository_properties: %w", err)
		}
		out.GithubRepositoryProperties = converted
	}
	if m.DownloadablesProperties != nil {
		converted, err := m.DownloadablesProperties.ToClientModel()
		if err != nil {
			return out, fmt.Errorf("downloadables_properties: %w", err)
		}
		out.DownloadablesProperties = converted
	}
	if m.LicenseKeysProperties != nil {
		converted, err := m.LicenseKeysProperties.ToClientModel()
		if err != nil {
			return out, fmt.Errorf("license_keys_properties: %w", err)
		}
		out.LicenseKeysProperties = converted
	}
	if m.MeterCreditProperties != nil {
		converted, err := m.MeterCreditProperties.ToClientModel()
		if err != nil {
			return out, fmt.Errorf("meter_credit_properties: %w", err)
		}
		out.MeterCreditProperties = converted
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.FeatureFlagProperties.IsNull() && !m.FeatureFlagProperties.IsUnknown() {
		if err := json.Unmarshal([]byte(m.FeatureFlagProperties.ValueString()), &out.FeatureFlagProperties); err != nil {
			return out, fmt.Errorf("feature_flag_properties: %w", err)
		}
	}
	if m.SlackSharedChannelProperties != nil {
		converted, err := m.SlackSharedChannelProperties.ToClientModel()
		if err != nil {
			return out, fmt.Errorf("slack_shared_channel_properties: %w", err)
		}
		out.SlackSharedChannelProperties = converted
	}
	if !m.Type.IsNull() && !m.Type.IsUnknown() {
		out.Type = m.Type.ValueString()
	}
	return out, nil
}

// ToUpdateModel converts a Terraform model to the UPDATE client model, which is
// a different shape from the create one: an update body may declare neither the
// nested blocks the create takes nor the id, and sending the create model to the
// patch endpoint is answered with "provided request body content is not in the
// expected format".
//
// Fields the patch model does not declare are simply absent here -- the
// generator only emits the ones it has.
func (m *BenefitModel) ToUpdateModel() (*client.BenefitUpdate, error) {
	out := &client.BenefitUpdate{}
	if !m.Metadata.IsNull() && !m.Metadata.IsUnknown() {
		out.Metadata = make(map[string]string, len(m.Metadata.Elements()))
		for key, element := range m.Metadata.Elements() {
			out.Metadata[key] = element.(types.String).ValueString()
		}
	}
	if !m.Description.IsNull() && !m.Description.IsUnknown() {
		Description := m.Description.ValueString()
		out.Description = &Description
	}
	if !m.Visibility.IsNull() && !m.Visibility.IsUnknown() {
		Visibility := m.Visibility.ValueString()
		out.Visibility = &Visibility
	}
	if !m.Type.IsNull() && !m.Type.IsUnknown() {
		out.Type = m.Type.ValueString()
	}
	return out, nil
}

// FromClientModel updates the Terraform model from a client model, for a
// RESOURCE: an attribute that is Optional alone is written only where the
// configuration already said something.
//
// OPTIONAL ALONE MEANS THE CONFIGURATION OWNS IT. A value the plan left null and
// the read then answers is "Provider produced inconsistent result after apply",
// on every apply -- so a position the create body does not insist on is filled
// in here only if it was filled in there. The positions where the SERVER fills
// it in are the ones that are Optional AND Computed, and those are written
// unconditionally.
func (m *BenefitModel) FromClientModel(c *client.Benefit) {
	m.fromAnswer(c, false)
}

// WHETHER THIS STATE CAME FROM AN IMPORT rather than from an apply.
//
// ImportState is a passthrough of the identifier: after it, state carries the id
// and nothing else, and only then does the framework call Read. FromClientModel's
// guard -- which exists so a refresh cannot clobber what the configuration said --
// therefore skips every writable attribute, leaving them null. The next plan then
// proposes to ADD url, format and events to a webhook endpoint that already has
// all three, and shows `name` going to (known after apply) when the server has a
// name for it.
//
// So: the identifier is set and nothing the create body owns is. That is an
// import, and an import wants everything the server answered.
func (m *BenefitModel) importing() bool {
	if !m.Metadata.IsNull() && !m.Metadata.IsUnknown() {
		return false
	}
	if !m.Description.IsNull() && !m.Description.IsUnknown() {
		return false
	}
	if !m.Visibility.IsNull() && !m.Visibility.IsUnknown() {
		return false
	}
	if m.CustomProperties != nil {
		return false
	}
	if m.DiscordProperties != nil {
		return false
	}
	if m.GithubRepositoryProperties != nil {
		return false
	}
	if m.DownloadablesProperties != nil {
		return false
	}
	if m.LicenseKeysProperties != nil {
		return false
	}
	if m.MeterCreditProperties != nil {
		return false
	}
	if !m.FeatureFlagProperties.IsNull() && !m.FeatureFlagProperties.IsUnknown() {
		return false
	}
	if m.SlackSharedChannelProperties != nil {
		return false
	}
	if !m.Type.IsNull() && !m.Type.IsUnknown() {
		return false
	}
	return true
}

// FromAnswer writes every attribute the server answered, which is what a DATA
// SOURCE wants: there is no configuration behind it to disagree with, and its
// schema says Computed for everything but the identifier it was given.
func (m *BenefitModel) FromAnswer(c *client.Benefit) {
	m.fromAnswer(c, true)
}

func (m *BenefitModel) fromAnswer(c *client.Benefit, everything bool) {
	m.Id = types.StringValue(c.Id)
	if c.Metadata == nil {
		m.Metadata = types.MapNull(types.StringType)
	} else {
		Metadata := make(map[string]attr.Value, len(c.Metadata))
		for key, element := range c.Metadata {
			Metadata[key] = types.StringValue(element)
		}
		m.Metadata = types.MapValueMust(types.StringType, Metadata)
	}
	if everything || !m.Description.IsNull() && !m.Description.IsUnknown() {
		m.Description = types.StringValue(c.Description)
	}
	if everything || !m.Visibility.IsNull() && !m.Visibility.IsUnknown() {
		m.Visibility = types.StringValue(c.Visibility)
	}
	if everything || !m.FeatureFlagProperties.IsNull() && !m.FeatureFlagProperties.IsUnknown() {
		// Marshalling a Go value cannot fail in a way worth surfacing here; an
		// unrepresentable one would have failed on the way in.
		//
		// The answer is only written when it says something the configuration does
		// not already say -- see jsonSupersetOf. A server that merely filled in its
		// own defaults has told us nothing, and recording it would fail the apply
		// and then propose an update forever.
		if encoded, err := json.Marshal(c.FeatureFlagProperties); err == nil {
			if m.FeatureFlagProperties.IsNull() || m.FeatureFlagProperties.IsUnknown() ||
				!jsonSupersetOf(string(encoded), m.FeatureFlagProperties.ValueString()) {
				m.FeatureFlagProperties = jsontypes.NewNormalizedValue(string(encoded))
			}
		}
	}
	if everything || !m.Type.IsNull() && !m.Type.IsUnknown() {
		m.Type = types.StringValue(c.Type)
	}
}
