// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"encoding/json"



	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"

	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"

	"github.com/hashicorp/terraform-plugin-log/tflog"



	"github.com/n-at-han-k/terraform-provider-polar/internal/client"
)

var _ resource.Resource = &CheckoutResource{}
var _ resource.ResourceWithImportState = &CheckoutResource{}

func NewCheckoutResource() resource.Resource {
	return &CheckoutResource{}
}

type CheckoutResource struct {
	client *client.Client
}

func (r *CheckoutResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_checkout"
}

func (r *CheckoutResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a checkout resource.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:    true,
				Description: "The ID of the object.",
			},
			"created_at": schema.StringAttribute{
				Computed:    true,
				Description: "Creation timestamp of the object.",
			},
			"modified_at": schema.StringAttribute{
				Computed:    true,
				Description: "Last modification timestamp of the object.",
			},
			"custom_field_data": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Optional:    true,
				Description: "Key-value object storing custom field values.",
			},
			"payment_processor": schema.StringAttribute{
				Computed:    true,
				Description: "Payment processor used.",
			},
			"status": schema.StringAttribute{
				Computed:    true,
				Description: "         Status of the checkout session.          - Open: the checkout session was opened.         - Expired: the checkout session was expired and is no more accessible.         - Confirmed: the user on the checkout session clicked Pay. This is not indicative of the payment's success status.         - Failed: the checkout definitely failed for technical reasons and cannot be retried. In most cases, this state is never reached.         - Succeeded: the payment on the checkout was performed successfully.         ",
			},
			"client_secret": schema.StringAttribute{
				Computed:    true,
				Description: "Client secret used to update and complete the checkout session from the client.",
			},
			"url": schema.StringAttribute{
				Computed:    true,
				Description: "URL where the customer can access the checkout session.",
			},
			"expires_at": schema.StringAttribute{
				Computed:    true,
				Description: "Expiration date and time of the checkout session.",
			},
			"success_url": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: "URL where the customer will be redirected after a successful payment.",
			},
			"return_url": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: "When set, a back button will be shown in the checkout to return to this URL.",
			},
			"embed_origin": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: "When checkout is embedded, represents the Origin of the page embedding the checkout. Used as a security measure to send messages only to the embedding page.",
			},
			"amount": schema.Int64Attribute{
				Computed:    true,
				Optional:    true,
				Description: "Amount in cents, before discounts and taxes.",
			},
			"seats": schema.Int64Attribute{
				Computed:    true,
				Optional:    true,
				Description: "Predefined number of seats (works with seat-based pricing only)",
			},
			"min_seats": schema.Int64Attribute{
				Computed:    true,
				Description: "Minimum number of seats (works with seat-based pricing only)",
			},
			"max_seats": schema.Int64Attribute{
				Computed:    true,
				Description: "Maximum number of seats (works with seat-based pricing only)",
			},
			"discount_amount": schema.Int64Attribute{
				Computed:    true,
				Description: "Discount amount in cents.",
			},
			"net_amount": schema.Int64Attribute{
				Computed:    true,
				Description: "Amount in cents, after discounts but before taxes.",
			},
			"tax_amount": schema.Int64Attribute{
				Computed:    true,
				Description: "Sales tax amount in cents. If `null`, it means there is no enough information yet to calculate it.",
			},
			"tax_behavior": schema.StringAttribute{
				Computed:    true,
				Description: "Tax behavior of the checkout. `inclusive` means the price includes tax, `exclusive` means tax is added on top. If `null`, tax is not yet calculated.",
			},
			"total_amount": schema.Int64Attribute{
				Computed:    true,
				Description: "Amount in cents, after discounts and taxes.",
			},
			"currency": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: "Currency code of the checkout session.",
			},
			"allow_trial": schema.BoolAttribute{
				Computed:    true,
				Optional:    true,
				Description: "Whether to enable the trial period for the checkout session. If `false`, the trial period will be disabled, even if the selected product has a trial configured.",
			},
			"active_trial_interval": schema.StringAttribute{
				Computed:    true,
				Description: "Interval unit of the trial period, if any. This value is either set from the checkout, if `trial_interval` is set, or from the selected product.",
			},
			"active_trial_interval_count": schema.Int64Attribute{
				Computed:    true,
				Description: "Number of interval units of the trial period, if any. This value is either set from the checkout, if `trial_interval_count` is set, or from the selected product.",
			},
			"trial_end": schema.StringAttribute{
				Computed:    true,
				Description: "End date and time of the trial period, if any.",
			},
			"organization_id": schema.StringAttribute{
				Computed:    true,
				Description: "ID of the organization owning the checkout session.",
			},
			"product_id": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: "ID of the product to checkout.",
			},
			"product_price_id": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: "ID of the product price to checkout.",
			},
			"discount_id": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: "ID of the discount applied to the checkout.",
			},
			"allow_discount_codes": schema.BoolAttribute{
				Computed:    true,
				Optional:    true,
				Description: "Whether to allow the customer to apply discount codes. If you apply a discount through `discount_id`, it'll still be applied, but the customer won't be able to change it.",
			},
			"require_billing_address": schema.BoolAttribute{
				Computed:    true,
				Optional:    true,
				Description: "Whether to require the customer to fill their full billing address, instead of just the country. Customers in the US will always be required to fill their full address, regardless of this setting. If you preset the billing address, this setting will be automatically set to `true`.",
			},
			"is_discount_applicable": schema.BoolAttribute{
				Computed:    true,
				Description: "Whether the discount is applicable to the checkout. Typically, free and custom prices are not discountable.",
			},
			"is_free_product_price": schema.BoolAttribute{
				Computed:    true,
				Description: "Whether the product price is free, regardless of discounts.",
			},
			"is_payment_required": schema.BoolAttribute{
				Computed:    true,
				Description: "Whether the checkout requires payment, e.g. in case of free products or discounts that cover the total amount.",
			},
			"is_payment_setup_required": schema.BoolAttribute{
				Computed:    true,
				Description: "Whether the checkout requires setting up a payment method, regardless of the amount, e.g. subscriptions that have first free cycles.",
			},
			"is_payment_form_required": schema.BoolAttribute{
				Computed:    true,
				Description: "Whether the checkout requires a payment form, whether because of a payment or payment method setup.",
			},
			"customer_id": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"is_business_customer": schema.BoolAttribute{
				Computed:    true,
				Optional:    true,
				Description: "Whether the customer is a business or an individual. If `true`, the customer will be required to fill their full billing address and billing name.",
			},
			"customer_name": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: "Name of the customer.",
			},
			"customer_email": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: "Email address of the customer.",
			},
			"customer_ip_address": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: "",
			},
			"customer_billing_name": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: "",
			},
			"customer_billing_address": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Optional:    true,
				Description: "Billing address of the customer.",
			},
			"customer_tax_id": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: "",
			},
			"locale": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: "",
			},
			"payment_method_type": schema.StringAttribute{
				Computed:    true,
				Description: "Payment method type selected by the customer in the checkout form, e.g. `card`, `apple_pay` or `upi`.",
			},
			"payment_processor_metadata": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"billing_address_fields": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "Determine which billing address fields should be disabled, optional or required in the checkout form.",
			},
			"trial_interval": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: "The interval unit for the trial period.",
			},
			"trial_interval_count": schema.Int64Attribute{
				Computed:    true,
				Optional:    true,
				Description: "The number of interval units for the trial period.",
			},
			"metadata": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Optional:    true,
				Description: "",
			},
			"external_customer_id": schema.StringAttribute{
				Computed:    true,
				Description: "ID of the customer in your system. If a matching customer exists on Polar, the resulting order will be linked to this customer. Otherwise, a new customer will be created with this external ID set.",
			},
			"products": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "List of products available to select.",
			},
			"product": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "Product selected to checkout.",
			},
			"product_price": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"prices": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "Mapping of product IDs to their list of prices.",
			},
			"discount": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"subscription_id": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"attached_custom_fields": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"customer_metadata": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Optional:    true,
				Description: "",
			},
		},
	}
}

func (r *CheckoutResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}

	r.client = c
}

func (r *CheckoutResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	resp.Diagnostics.AddError("Not Supported", "Create is not supported for checkout")
}

func (r *CheckoutResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state CheckoutModel

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// A resource with no identifier is not a resource. Without this the read
	// interpolates an empty id and asks the COLLECTION endpoint, which answers
	// 200 and a list -- so a state written before the id was known would look
	// healthy forever instead of being adopted again.
	if state.Id.ValueString() == "" {
		resp.State.RemoveResource(ctx)
		return
	}

	respBody, err := r.client.DoRequest(ctx, "GET", fmt.Sprintf("/checkouts/%v", state.Id.ValueString()), nil)
	if err != nil {
		// GONE IS NOT BROKEN. A 404 here means the resource this state row
		// describes no longer exists -- deleted by hand, or by something else
		// that owns it -- and the honest answer is to drop the row and let the
		// plan decide whether to recreate it. Raising instead fails every plan
		// in the configuration, including the ones with nothing to do with this
		// resource, and leaves no way out but editing state by hand.
		//
		// ONLY IN Read. The same 404 after a create or an update is a real
		// failure: something we just wrote is missing.
		var apiErr *client.APIError
		if errors.As(err, &apiErr) && apiErr.StatusCode == http.StatusNotFound {
			resp.State.RemoveResource(ctx)
			return
		}

		resp.Diagnostics.AddError("Error reading checkout", err.Error())
		return
	}

	var result client.Checkout
	if err := json.Unmarshal(respBody, &result); err != nil {
		resp.Diagnostics.AddError("Error parsing response", err.Error())
		return
	}

	state.FromClientModel(&result)

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *CheckoutResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan CheckoutModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// The identifiers come off state: they cannot change on an update, and the
	// plan's copy of a Computed one is unknown -- which is also the only place
	// an imported nested resource's parents live.
	var state CheckoutModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	reqBody, err := plan.ToClientModel()
	if err != nil {
		resp.Diagnostics.AddError("Invalid checkout configuration", err.Error())
		return
	}

	respBody, err := r.client.DoRequest(ctx, "PATCH", fmt.Sprintf("/checkouts/%v", state.Id.ValueString()), reqBody)
	if err != nil {
		resp.Diagnostics.AddError("Error updating checkout", err.Error())
		return
	}

	// AN UPDATE'S ANSWER IS NOT THE READ'S. RT answers a PUT with the list of
	// changes it made -- ["Description changed from 'a' to 'b'"] -- and some
	// updates answer nothing at all; neither is the resource, and
	// unmarshalling either one is "Error parsing response" AFTER the server
	// has already accepted the change. What it now looks like is read back.
	respBody, err = r.client.DoRequest(ctx, "GET", fmt.Sprintf("/checkouts/%v", state.Id.ValueString()), nil)
	if err != nil {
		resp.Diagnostics.AddError("Error reading back the updated checkout", err.Error())
		return
	}

	if len(respBody) > 0 {
		var result client.Checkout
		if err := json.Unmarshal(respBody, &result); err != nil {
			resp.Diagnostics.AddError("Error parsing response", err.Error())
			return
		}

		plan.FromClientModel(&result)
	}

	tflog.Trace(ctx, "updated checkout resource")
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *CheckoutResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	// No delete endpoint available; remove the resource from state.
}

func (r *CheckoutResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
