// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"encoding/json"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"

	"github.com/n-at-han-k/terraform-provider-polar/internal/client"
)

// CustomFieldModel is the Terraform model for custom_field.
type CustomFieldModel struct {
	Id types.String `tfsdk:"id"`
	CreatedAt types.String `tfsdk:"created_at"`
	ModifiedAt types.String `tfsdk:"modified_at"`
	Metadata jsontypes.Normalized `tfsdk:"metadata"`
	Slug types.String `tfsdk:"slug"`
	Name types.String `tfsdk:"name"`
	OrganizationId types.String `tfsdk:"organization_id"`
	Properties *CustomFieldPropertiesModel `tfsdk:"properties"`
	Type types.String `tfsdk:"type"`
}

// CustomFieldPropertiesModel is one `properties` block.
//
// A STRUCT WITH tfsdk TAGS, not a types.Object: terraform-plugin-framework
// reflects over these, so a slice of them is a ListNestedAttribute and a
// pointer to one is a SingleNestedAttribute, with no AttributeTypes map to keep
// in step with the fields by hand.
type CustomFieldPropertiesModel struct {
	FormLabel types.String `tfsdk:"form_label"`
	FormHelpText types.String `tfsdk:"form_help_text"`
	FormPlaceholder types.String `tfsdk:"form_placeholder"`
	Textarea types.Bool `tfsdk:"textarea"`
	MinLength types.Int64 `tfsdk:"min_length"`
	MaxLength types.Int64 `tfsdk:"max_length"`
}

// ToClientModel converts one block to the client type the request carries.
func (m *CustomFieldPropertiesModel) ToClientModel() (*client.CustomFieldTextProperties, error) {
	out := &client.CustomFieldTextProperties{}
	if !m.FormLabel.IsNull() && !m.FormLabel.IsUnknown() {
		out.FormLabel = m.FormLabel.ValueString()
	}
	if !m.FormHelpText.IsNull() && !m.FormHelpText.IsUnknown() {
		out.FormHelpText = m.FormHelpText.ValueString()
	}
	if !m.FormPlaceholder.IsNull() && !m.FormPlaceholder.IsUnknown() {
		out.FormPlaceholder = m.FormPlaceholder.ValueString()
	}
	if !m.Textarea.IsNull() && !m.Textarea.IsUnknown() {
		Textarea := m.Textarea.ValueBool()
		out.Textarea = &Textarea
	}
	if !m.MinLength.IsNull() && !m.MinLength.IsUnknown() {
		out.MinLength = int32(m.MinLength.ValueInt64())
	}
	if !m.MaxLength.IsNull() && !m.MaxLength.IsUnknown() {
		out.MaxLength = int32(m.MaxLength.ValueInt64())
	}
	return out, nil
}

// FromClientModel fills one block from what the server answered.
//
// EVERY CHILD IS WRITTEN, not only the ones the configuration set, because they
// are Optional AND Computed: Polar fills in a price's currency and tax
// behaviour, and a Computed attribute left unknown after an apply is "provider
// returned invalid result object after apply".
func (m *CustomFieldPropertiesModel) FromClientModel(c *client.CustomFieldTextProperties) {
	m.FormLabel = types.StringValue(c.FormLabel)
	m.FormHelpText = types.StringValue(c.FormHelpText)
	m.FormPlaceholder = types.StringValue(c.FormPlaceholder)
	if c.Textarea != nil {
		m.Textarea = types.BoolValue(*c.Textarea)
	} else {
		m.Textarea = types.BoolNull()
	}
	m.MinLength = types.Int64Value(int64(c.MinLength))
	m.MaxLength = types.Int64Value(int64(c.MaxLength))
}

// ToClientModel converts a Terraform model to a client model.
func (m *CustomFieldModel) ToClientModel() (*client.CustomFieldCreate, error) {
	out := &client.CustomFieldCreate{}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.Metadata.IsNull() && !m.Metadata.IsUnknown() {
		if err := json.Unmarshal([]byte(m.Metadata.ValueString()), &out.Metadata); err != nil {
			return out, fmt.Errorf("metadata: %w", err)
		}
	}
	if !m.Slug.IsNull() && !m.Slug.IsUnknown() {
		out.Slug = m.Slug.ValueString()
	}
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		out.Name = m.Name.ValueString()
	}
	if !m.OrganizationId.IsNull() && !m.OrganizationId.IsUnknown() {
		out.OrganizationId = m.OrganizationId.ValueString()
	}
	if m.Properties != nil {
		converted, err := m.Properties.ToClientModel()
		if err != nil {
			return out, fmt.Errorf("properties: %w", err)
		}
		out.Properties = converted
	}
	if !m.Type.IsNull() && !m.Type.IsUnknown() {
		out.Type = m.Type.ValueString()
	}
	return out, nil
}

// ToUpdateModel converts a Terraform model to the UPDATE client model, which is
// a different shape from the create one: an update body may declare neither the
// nested blocks the create takes nor the id, and sending the create model to the
// patch endpoint is answered with "provided request body content is not in the
// expected format".
//
// Fields the patch model does not declare are simply absent here -- the
// generator only emits the ones it has.
func (m *CustomFieldModel) ToUpdateModel() (*client.CustomFieldUpdate, error) {
	out := &client.CustomFieldUpdate{}
	if !m.Metadata.IsNull() && !m.Metadata.IsUnknown() {
		if err := json.Unmarshal([]byte(m.Metadata.ValueString()), &out.Metadata); err != nil {
			return out, fmt.Errorf("metadata: %w", err)
		}
	}
	if !m.Slug.IsNull() && !m.Slug.IsUnknown() {
		out.Slug = m.Slug.ValueString()
	}
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		out.Name = m.Name.ValueString()
	}
	if m.Properties != nil {
		converted, err := m.Properties.ToClientModel()
		if err != nil {
			return out, fmt.Errorf("properties: %w", err)
		}
		out.Properties = converted
	}
	if !m.Type.IsNull() && !m.Type.IsUnknown() {
		out.Type = m.Type.ValueString()
	}
	return out, nil
}

// FromClientModel updates the Terraform model from a client model.
func (m *CustomFieldModel) FromClientModel(c *client.CustomField) {
	m.Id = types.StringValue(c.Id)
	m.CreatedAt = types.StringValue(c.CreatedAt)
	m.ModifiedAt = types.StringValue(c.ModifiedAt)
	// The create body takes this and no response of the same shape answers it --
	// AssociationRequest against AssociationResponse -- so nothing above writes
	// it, and a Computed attribute the configuration left out stays UNKNOWN once
	// the apply is over: "provider returned invalid result object after apply".
	// Unknown becomes null; a value the plan already knows is left alone.
	if m.Metadata.IsUnknown() {
		m.Metadata = jsontypes.NewNormalizedNull()
	}
	m.Slug = types.StringValue(c.Slug)
	m.Name = types.StringValue(c.Name)
	m.OrganizationId = types.StringValue(c.OrganizationId)
	m.Type = types.StringValue(c.Type)
}
