// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/n-at-han-k/terraform-provider-polar/internal/client"
)

// CustomFieldModel is the Terraform model for custom_field.
type CustomFieldModel struct {
	Id         types.String                `tfsdk:"id"`
	Metadata   types.Map                   `tfsdk:"metadata"`
	Slug       types.String                `tfsdk:"slug"`
	Name       types.String                `tfsdk:"name"`
	Properties *CustomFieldPropertiesModel `tfsdk:"properties"`
	Type       types.String                `tfsdk:"type"`
}

// CustomFieldPropertiesModel is one `properties` block.
//
// A STRUCT WITH tfsdk TAGS, not a types.Object: terraform-plugin-framework
// reflects over these, so a slice of them is a ListNestedAttribute and a
// pointer to one is a SingleNestedAttribute, with no AttributeTypes map to keep
// in step with the fields by hand.
type CustomFieldPropertiesModel struct {
	FormLabel       types.String                             `tfsdk:"form_label"`
	FormHelpText    types.String                             `tfsdk:"form_help_text"`
	FormPlaceholder types.String                             `tfsdk:"form_placeholder"`
	Textarea        types.Bool                               `tfsdk:"textarea"`
	MinLength       types.Int64                              `tfsdk:"min_length"`
	MaxLength       types.Int64                              `tfsdk:"max_length"`
	Ge              types.Int64                              `tfsdk:"ge"`
	Le              types.Int64                              `tfsdk:"le"`
	Options         []CustomFieldPropertiesModelOptionsModel `tfsdk:"options"`
}

// ToClientModel converts one block to the client type the request carries.
func (m *CustomFieldPropertiesModel) ToClientModel() (*client.CustomFieldCreateProperties, error) {
	out := &client.CustomFieldCreateProperties{}
	if !m.FormLabel.IsNull() && !m.FormLabel.IsUnknown() {
		FormLabel := m.FormLabel.ValueString()
		out.FormLabel = &FormLabel
	}
	if !m.FormHelpText.IsNull() && !m.FormHelpText.IsUnknown() {
		FormHelpText := m.FormHelpText.ValueString()
		out.FormHelpText = &FormHelpText
	}
	if !m.FormPlaceholder.IsNull() && !m.FormPlaceholder.IsUnknown() {
		FormPlaceholder := m.FormPlaceholder.ValueString()
		out.FormPlaceholder = &FormPlaceholder
	}
	if !m.Textarea.IsNull() && !m.Textarea.IsUnknown() {
		Textarea := m.Textarea.ValueBool()
		out.Textarea = &Textarea
	}
	if !m.MinLength.IsNull() && !m.MinLength.IsUnknown() {
		MinLength := int32(m.MinLength.ValueInt64())
		out.MinLength = &MinLength
	}
	if !m.MaxLength.IsNull() && !m.MaxLength.IsUnknown() {
		MaxLength := int32(m.MaxLength.ValueInt64())
		out.MaxLength = &MaxLength
	}
	if !m.Ge.IsNull() && !m.Ge.IsUnknown() {
		Ge := int32(m.Ge.ValueInt64())
		out.Ge = &Ge
	}
	if !m.Le.IsNull() && !m.Le.IsUnknown() {
		Le := int32(m.Le.ValueInt64())
		out.Le = &Le
	}
	return out, nil
}

// FromClientModel fills one block from what the server answered.
//
// EVERY CHILD IS WRITTEN, not only the ones the configuration set, because they
// are Optional AND Computed: Polar fills in a price's currency and tax
// behaviour, and a Computed attribute left unknown after an apply is "provider
// returned invalid result object after apply".
func (m *CustomFieldPropertiesModel) FromClientModel(c *client.CustomFieldCreateProperties) {
	// NIL IS ABSENT. The server omitted it, so state says null rather than
	// Go's zero -- otherwise the next plan proposes removing a value nobody set.
	if c.FormLabel != nil {
		m.FormLabel = types.StringValue(*c.FormLabel)
	} else {
		m.FormLabel = types.StringNull()
	}
	// NIL IS ABSENT. The server omitted it, so state says null rather than
	// Go's zero -- otherwise the next plan proposes removing a value nobody set.
	if c.FormHelpText != nil {
		m.FormHelpText = types.StringValue(*c.FormHelpText)
	} else {
		m.FormHelpText = types.StringNull()
	}
	// NIL IS ABSENT. The server omitted it, so state says null rather than
	// Go's zero -- otherwise the next plan proposes removing a value nobody set.
	if c.FormPlaceholder != nil {
		m.FormPlaceholder = types.StringValue(*c.FormPlaceholder)
	} else {
		m.FormPlaceholder = types.StringNull()
	}
	if c.Textarea != nil {
		m.Textarea = types.BoolValue(*c.Textarea)
	} else {
		m.Textarea = types.BoolNull()
	}
	// NIL IS ABSENT. The server omitted it, so state says null rather than
	// Go's zero -- otherwise the next plan proposes removing a value nobody set.
	if c.MinLength != nil {
		m.MinLength = types.Int64Value(int64(*c.MinLength))
	} else {
		m.MinLength = types.Int64Null()
	}
	// NIL IS ABSENT. The server omitted it, so state says null rather than
	// Go's zero -- otherwise the next plan proposes removing a value nobody set.
	if c.MaxLength != nil {
		m.MaxLength = types.Int64Value(int64(*c.MaxLength))
	} else {
		m.MaxLength = types.Int64Null()
	}
	// NIL IS ABSENT. The server omitted it, so state says null rather than
	// Go's zero -- otherwise the next plan proposes removing a value nobody set.
	if c.Ge != nil {
		m.Ge = types.Int64Value(int64(*c.Ge))
	} else {
		m.Ge = types.Int64Null()
	}
	// NIL IS ABSENT. The server omitted it, so state says null rather than
	// Go's zero -- otherwise the next plan proposes removing a value nobody set.
	if c.Le != nil {
		m.Le = types.Int64Value(int64(*c.Le))
	} else {
		m.Le = types.Int64Null()
	}
}

// CustomFieldPropertiesModelOptionsModel is one `options` block.
//
// A STRUCT WITH tfsdk TAGS, not a types.Object: terraform-plugin-framework
// reflects over these, so a slice of them is a ListNestedAttribute and a
// pointer to one is a SingleNestedAttribute, with no AttributeTypes map to keep
// in step with the fields by hand.
type CustomFieldPropertiesModelOptionsModel struct {
	Value types.String `tfsdk:"value"`
	Label types.String `tfsdk:"label"`
}

// ToClientModel converts one block to the client type the request carries.
func (m *CustomFieldPropertiesModelOptionsModel) ToClientModel() (*client.CustomFieldSelectOption, error) {
	out := &client.CustomFieldSelectOption{}
	if !m.Value.IsNull() && !m.Value.IsUnknown() {
		Value := m.Value.ValueString()
		out.Value = &Value
	}
	if !m.Label.IsNull() && !m.Label.IsUnknown() {
		Label := m.Label.ValueString()
		out.Label = &Label
	}
	return out, nil
}

// FromClientModel fills one block from what the server answered.
//
// EVERY CHILD IS WRITTEN, not only the ones the configuration set, because they
// are Optional AND Computed: Polar fills in a price's currency and tax
// behaviour, and a Computed attribute left unknown after an apply is "provider
// returned invalid result object after apply".
func (m *CustomFieldPropertiesModelOptionsModel) FromClientModel(c *client.CustomFieldSelectOption) {
	// NIL IS ABSENT. The server omitted it, so state says null rather than
	// Go's zero -- otherwise the next plan proposes removing a value nobody set.
	if c.Value != nil {
		m.Value = types.StringValue(*c.Value)
	} else {
		m.Value = types.StringNull()
	}
	// NIL IS ABSENT. The server omitted it, so state says null rather than
	// Go's zero -- otherwise the next plan proposes removing a value nobody set.
	if c.Label != nil {
		m.Label = types.StringValue(*c.Label)
	} else {
		m.Label = types.StringNull()
	}
}

// ToClientModel converts a Terraform model to a client model.
func (m *CustomFieldModel) ToClientModel() (*client.CustomFieldCreate, error) {
	out := &client.CustomFieldCreate{}
	if !m.Metadata.IsNull() && !m.Metadata.IsUnknown() {
		out.Metadata = make(map[string]string, len(m.Metadata.Elements()))
		for key, element := range m.Metadata.Elements() {
			out.Metadata[key] = element.(types.String).ValueString()
		}
	}
	if !m.Slug.IsNull() && !m.Slug.IsUnknown() {
		Slug := m.Slug.ValueString()
		out.Slug = &Slug
	}
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		Name := m.Name.ValueString()
		out.Name = &Name
	}
	if m.Properties != nil {
		converted, err := m.Properties.ToClientModel()
		if err != nil {
			return out, fmt.Errorf("properties: %w", err)
		}
		out.Properties = converted
	}
	if !m.Type.IsNull() && !m.Type.IsUnknown() {
		Type := m.Type.ValueString()
		out.Type = &Type
	}
	return out, nil
}

// ToUpdateModel converts a Terraform model to the UPDATE client model, which is
// a different shape from the create one: an update body may declare neither the
// nested blocks the create takes nor the id, and sending the create model to the
// patch endpoint is answered with "provided request body content is not in the
// expected format".
//
// Fields the patch model does not declare are simply absent here -- the
// generator only emits the ones it has.
func (m *CustomFieldModel) ToUpdateModel() (*client.CustomFieldUpdate, error) {
	out := &client.CustomFieldUpdate{}
	if !m.Metadata.IsNull() && !m.Metadata.IsUnknown() {
		out.Metadata = make(map[string]string, len(m.Metadata.Elements()))
		for key, element := range m.Metadata.Elements() {
			out.Metadata[key] = element.(types.String).ValueString()
		}
	}
	if !m.Slug.IsNull() && !m.Slug.IsUnknown() {
		Slug := m.Slug.ValueString()
		out.Slug = &Slug
	}
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		Name := m.Name.ValueString()
		out.Name = &Name
	}
	if !m.Type.IsNull() && !m.Type.IsUnknown() {
		Type := m.Type.ValueString()
		out.Type = &Type
	}
	return out, nil
}

// FromClientModel updates the Terraform model from a client model, for a
// RESOURCE: an attribute that is Optional alone is written only where the
// configuration already said something.
//
// OPTIONAL ALONE MEANS THE CONFIGURATION OWNS IT. A value the plan left null and
// the read then answers is "Provider produced inconsistent result after apply",
// on every apply -- so a position the create body does not insist on is filled
// in here only if it was filled in there. The positions where the SERVER fills
// it in are the ones that are Optional AND Computed, and those are written
// unconditionally.
func (m *CustomFieldModel) FromClientModel(c *client.CustomField) {
	m.fromAnswer(c, false)
}

// WHETHER THIS STATE CAME FROM AN IMPORT rather than from an apply.
//
// ImportState is a passthrough of the identifier: after it, state carries the id
// and nothing else, and only then does the framework call Read. FromClientModel's
// guard -- which exists so a refresh cannot clobber what the configuration said --
// therefore skips every writable attribute, leaving them null. The next plan then
// proposes to ADD url, format and events to a webhook endpoint that already has
// all three, and shows `name` going to (known after apply) when the server has a
// name for it.
//
// So: the identifier is set and nothing the create body owns is. That is an
// import, and an import wants everything the server answered.
func (m *CustomFieldModel) importing() bool {
	if !m.Metadata.IsNull() && !m.Metadata.IsUnknown() {
		return false
	}
	if !m.Slug.IsNull() && !m.Slug.IsUnknown() {
		return false
	}
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		return false
	}
	if m.Properties != nil {
		return false
	}
	if !m.Type.IsNull() && !m.Type.IsUnknown() {
		return false
	}
	return true
}

// FromAnswer writes every attribute the server answered, which is what a DATA
// SOURCE wants: there is no configuration behind it to disagree with, and its
// schema says Computed for everything but the identifier it was given.
func (m *CustomFieldModel) FromAnswer(c *client.CustomField) {
	m.fromAnswer(c, true)
}

func (m *CustomFieldModel) fromAnswer(c *client.CustomField, everything bool) {
	// NIL IS ABSENT. The server omitted it, so state says null rather than
	// Go's zero -- otherwise the next plan proposes removing a value nobody set.
	if c.Id != nil {
		m.Id = types.StringValue(*c.Id)
	} else {
		m.Id = types.StringNull()
	}
	if c.Metadata == nil {
		m.Metadata = types.MapNull(types.StringType)
	} else {
		Metadata := make(map[string]attr.Value, len(c.Metadata))
		for key, element := range c.Metadata {
			Metadata[key] = types.StringValue(element)
		}
		m.Metadata = types.MapValueMust(types.StringType, Metadata)
	}
	if everything || !m.Slug.IsNull() && !m.Slug.IsUnknown() {
		// NIL IS ABSENT. The server omitted it, so state says null rather than
		// Go's zero -- otherwise the next plan proposes removing a value nobody set.
		if c.Slug != nil {
			m.Slug = types.StringValue(*c.Slug)
		} else {
			m.Slug = types.StringNull()
		}
	}
	if everything || !m.Name.IsNull() && !m.Name.IsUnknown() {
		// NIL IS ABSENT. The server omitted it, so state says null rather than
		// Go's zero -- otherwise the next plan proposes removing a value nobody set.
		if c.Name != nil {
			m.Name = types.StringValue(*c.Name)
		} else {
			m.Name = types.StringNull()
		}
	}
	if everything || !m.Type.IsNull() && !m.Type.IsUnknown() {
		// NIL IS ABSENT. The server omitted it, so state says null rather than
		// Go's zero -- otherwise the next plan proposes removing a value nobody set.
		if c.Type != nil {
			m.Type = types.StringValue(*c.Type)
		} else {
			m.Type = types.StringNull()
		}
	}
}
