// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/n-at-han-k/terraform-provider-polar/internal/client"
)

// CustomerModel is the Terraform model for customer.
type CustomerModel struct {
	Id                      types.String                 `tfsdk:"id"`
	Metadata                types.Map                    `tfsdk:"metadata"`
	ExternalId              types.String                 `tfsdk:"external_id"`
	Name                    types.String                 `tfsdk:"name"`
	BillingAddress          *CustomerBillingAddressModel `tfsdk:"billing_address"`
	TaxId                   types.String                 `tfsdk:"tax_id"`
	Locale                  types.String                 `tfsdk:"locale"`
	Owner                   *CustomerOwnerModel          `tfsdk:"owner"`
	CustomerIndividualType  types.String                 `tfsdk:"customer_individual_type"`
	CustomerTeamType        types.String                 `tfsdk:"customer_team_type"`
	CustomerIndividualEmail types.String                 `tfsdk:"customer_individual_email"`
	CustomerTeamEmail       types.String                 `tfsdk:"customer_team_email"`
}

// CustomerBillingAddressModel is one `billing_address` block.
//
// A STRUCT WITH tfsdk TAGS, not a types.Object: terraform-plugin-framework
// reflects over these, so a slice of them is a ListNestedAttribute and a
// pointer to one is a SingleNestedAttribute, with no AttributeTypes map to keep
// in step with the fields by hand.
type CustomerBillingAddressModel struct {
	Line1      types.String `tfsdk:"line1"`
	Line2      types.String `tfsdk:"line2"`
	PostalCode types.String `tfsdk:"postal_code"`
	City       types.String `tfsdk:"city"`
	State      types.String `tfsdk:"state"`
	Country    types.String `tfsdk:"country"`
}

// ToClientModel converts one block to the client type the request carries.
func (m *CustomerBillingAddressModel) ToClientModel() (*client.AddressInput, error) {
	out := &client.AddressInput{}
	if !m.Line1.IsNull() && !m.Line1.IsUnknown() {
		out.Line1 = m.Line1.ValueString()
	}
	if !m.Line2.IsNull() && !m.Line2.IsUnknown() {
		out.Line2 = m.Line2.ValueString()
	}
	if !m.PostalCode.IsNull() && !m.PostalCode.IsUnknown() {
		out.PostalCode = m.PostalCode.ValueString()
	}
	if !m.City.IsNull() && !m.City.IsUnknown() {
		out.City = m.City.ValueString()
	}
	if !m.State.IsNull() && !m.State.IsUnknown() {
		out.State = m.State.ValueString()
	}
	if !m.Country.IsNull() && !m.Country.IsUnknown() {
		out.Country = m.Country.ValueString()
	}
	return out, nil
}

// FromClientModel fills one block from what the server answered.
//
// EVERY CHILD IS WRITTEN, not only the ones the configuration set, because they
// are Optional AND Computed: Polar fills in a price's currency and tax
// behaviour, and a Computed attribute left unknown after an apply is "provider
// returned invalid result object after apply".
func (m *CustomerBillingAddressModel) FromClientModel(c *client.AddressInput) {
	m.Line1 = types.StringValue(c.Line1)
	m.Line2 = types.StringValue(c.Line2)
	m.PostalCode = types.StringValue(c.PostalCode)
	m.City = types.StringValue(c.City)
	m.State = types.StringValue(c.State)
	m.Country = types.StringValue(c.Country)
}

// CustomerOwnerModel is one `owner` block.
//
// A STRUCT WITH tfsdk TAGS, not a types.Object: terraform-plugin-framework
// reflects over these, so a slice of them is a ListNestedAttribute and a
// pointer to one is a SingleNestedAttribute, with no AttributeTypes map to keep
// in step with the fields by hand.
type CustomerOwnerModel struct {
	Email      types.String `tfsdk:"email"`
	Name       types.String `tfsdk:"name"`
	ExternalId types.String `tfsdk:"external_id"`
}

// ToClientModel converts one block to the client type the request carries.
func (m *CustomerOwnerModel) ToClientModel() (*client.MemberOwnerCreate, error) {
	out := &client.MemberOwnerCreate{}
	if !m.Email.IsNull() && !m.Email.IsUnknown() {
		out.Email = m.Email.ValueString()
	}
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		out.Name = m.Name.ValueString()
	}
	if !m.ExternalId.IsNull() && !m.ExternalId.IsUnknown() {
		out.ExternalId = m.ExternalId.ValueString()
	}
	return out, nil
}

// FromClientModel fills one block from what the server answered.
//
// EVERY CHILD IS WRITTEN, not only the ones the configuration set, because they
// are Optional AND Computed: Polar fills in a price's currency and tax
// behaviour, and a Computed attribute left unknown after an apply is "provider
// returned invalid result object after apply".
func (m *CustomerOwnerModel) FromClientModel(c *client.MemberOwnerCreate) {
	m.Email = types.StringValue(c.Email)
	m.Name = types.StringValue(c.Name)
	m.ExternalId = types.StringValue(c.ExternalId)
}

// ToClientModel converts a Terraform model to a client model.
func (m *CustomerModel) ToClientModel() (*client.CustomerCreate, error) {
	out := &client.CustomerCreate{}
	if !m.Metadata.IsNull() && !m.Metadata.IsUnknown() {
		out.Metadata = make(map[string]string, len(m.Metadata.Elements()))
		for key, element := range m.Metadata.Elements() {
			out.Metadata[key] = element.(types.String).ValueString()
		}
	}
	if !m.ExternalId.IsNull() && !m.ExternalId.IsUnknown() {
		out.ExternalId = m.ExternalId.ValueString()
	}
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		out.Name = m.Name.ValueString()
	}
	if m.BillingAddress != nil {
		converted, err := m.BillingAddress.ToClientModel()
		if err != nil {
			return out, fmt.Errorf("billing_address: %w", err)
		}
		out.BillingAddress = converted
	}
	if !m.Locale.IsNull() && !m.Locale.IsUnknown() {
		out.Locale = m.Locale.ValueString()
	}
	if m.Owner != nil {
		converted, err := m.Owner.ToClientModel()
		if err != nil {
			return out, fmt.Errorf("owner: %w", err)
		}
		out.Owner = converted
	}
	if !m.CustomerIndividualType.IsNull() && !m.CustomerIndividualType.IsUnknown() {
		out.CustomerIndividualType = m.CustomerIndividualType.ValueString()
	}
	if !m.CustomerTeamType.IsNull() && !m.CustomerTeamType.IsUnknown() {
		out.CustomerTeamType = m.CustomerTeamType.ValueString()
	}
	if !m.CustomerIndividualEmail.IsNull() && !m.CustomerIndividualEmail.IsUnknown() {
		out.CustomerIndividualEmail = m.CustomerIndividualEmail.ValueString()
	}
	if !m.CustomerTeamEmail.IsNull() && !m.CustomerTeamEmail.IsUnknown() {
		out.CustomerTeamEmail = m.CustomerTeamEmail.ValueString()
	}
	return out, nil
}

// ToUpdateModel converts a Terraform model to the UPDATE client model, which is
// a different shape from the create one: an update body may declare neither the
// nested blocks the create takes nor the id, and sending the create model to the
// patch endpoint is answered with "provided request body content is not in the
// expected format".
//
// Fields the patch model does not declare are simply absent here -- the
// generator only emits the ones it has.
func (m *CustomerModel) ToUpdateModel() (*client.CustomerUpdate, error) {
	out := &client.CustomerUpdate{}
	if !m.Metadata.IsNull() && !m.Metadata.IsUnknown() {
		out.Metadata = make(map[string]string, len(m.Metadata.Elements()))
		for key, element := range m.Metadata.Elements() {
			out.Metadata[key] = element.(types.String).ValueString()
		}
	}
	if !m.ExternalId.IsNull() && !m.ExternalId.IsUnknown() {
		out.ExternalId = m.ExternalId.ValueString()
	}
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		out.Name = m.Name.ValueString()
	}
	if m.BillingAddress != nil {
		converted, err := m.BillingAddress.ToClientModel()
		if err != nil {
			return out, fmt.Errorf("billing_address: %w", err)
		}
		out.BillingAddress = converted
	}
	if !m.Locale.IsNull() && !m.Locale.IsUnknown() {
		out.Locale = m.Locale.ValueString()
	}
	return out, nil
}

// FromClientModel updates the Terraform model from a client model, for a
// RESOURCE: an attribute that is Optional alone is written only where the
// configuration already said something.
//
// OPTIONAL ALONE MEANS THE CONFIGURATION OWNS IT. A value the plan left null and
// the read then answers is "Provider produced inconsistent result after apply",
// on every apply -- so a position the create body does not insist on is filled
// in here only if it was filled in there. The positions where the SERVER fills
// it in are the ones that are Optional AND Computed, and those are written
// unconditionally.
func (m *CustomerModel) FromClientModel(c *client.Customer) {
	m.fromAnswer(c, false)
}

// WHETHER THIS STATE CAME FROM AN IMPORT rather than from an apply.
//
// ImportState is a passthrough of the identifier: after it, state carries the id
// and nothing else, and only then does the framework call Read. FromClientModel's
// guard -- which exists so a refresh cannot clobber what the configuration said --
// therefore skips every writable attribute, leaving them null. The next plan then
// proposes to ADD url, format and events to a webhook endpoint that already has
// all three, and shows `name` going to (known after apply) when the server has a
// name for it.
//
// So: the identifier is set and nothing the create body owns is. That is an
// import, and an import wants everything the server answered.
func (m *CustomerModel) importing() bool {
	if !m.Metadata.IsNull() && !m.Metadata.IsUnknown() {
		return false
	}
	if !m.ExternalId.IsNull() && !m.ExternalId.IsUnknown() {
		return false
	}
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		return false
	}
	if m.BillingAddress != nil {
		return false
	}
	if !m.TaxId.IsNull() && !m.TaxId.IsUnknown() {
		return false
	}
	if !m.Locale.IsNull() && !m.Locale.IsUnknown() {
		return false
	}
	if m.Owner != nil {
		return false
	}
	if !m.CustomerIndividualType.IsNull() && !m.CustomerIndividualType.IsUnknown() {
		return false
	}
	if !m.CustomerTeamType.IsNull() && !m.CustomerTeamType.IsUnknown() {
		return false
	}
	if !m.CustomerIndividualEmail.IsNull() && !m.CustomerIndividualEmail.IsUnknown() {
		return false
	}
	if !m.CustomerTeamEmail.IsNull() && !m.CustomerTeamEmail.IsUnknown() {
		return false
	}
	return true
}

// FromAnswer writes every attribute the server answered, which is what a DATA
// SOURCE wants: there is no configuration behind it to disagree with, and its
// schema says Computed for everything but the identifier it was given.
func (m *CustomerModel) FromAnswer(c *client.Customer) {
	m.fromAnswer(c, true)
}

func (m *CustomerModel) fromAnswer(c *client.Customer, everything bool) {
	m.Id = types.StringValue(c.Id)
	if c.Metadata == nil {
		m.Metadata = types.MapNull(types.StringType)
	} else {
		Metadata := make(map[string]attr.Value, len(c.Metadata))
		for key, element := range c.Metadata {
			Metadata[key] = types.StringValue(element)
		}
		m.Metadata = types.MapValueMust(types.StringType, Metadata)
	}
	if everything || !m.ExternalId.IsNull() && !m.ExternalId.IsUnknown() {
		m.ExternalId = types.StringValue(c.ExternalId)
	}
	if everything || !m.Name.IsNull() && !m.Name.IsUnknown() {
		m.Name = types.StringValue(c.Name)
	}
	if everything || !m.Locale.IsNull() && !m.Locale.IsUnknown() {
		m.Locale = types.StringValue(c.Locale)
	}
}
