// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"encoding/json"



	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"

	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-log/tflog"



	"github.com/n-at-han-k/terraform-provider-polar/internal/client"
)

var _ resource.Resource = &CustomFieldResource{}
var _ resource.ResourceWithImportState = &CustomFieldResource{}

func NewCustomFieldResource() resource.Resource {
	return &CustomFieldResource{}
}

type CustomFieldResource struct {
	client *client.Client
}

func (r *CustomFieldResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_custom_field"
}

func (r *CustomFieldResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a custom_field resource.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:    true,
				Description: "The ID of the object.",
			},
			"created_at": schema.StringAttribute{
				Computed:    true,
				Description: "Creation timestamp of the object.",
			},
			"modified_at": schema.StringAttribute{
				Computed:    true,
				Description: "Last modification timestamp of the object.",
			},
			"metadata": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Optional:    true,
				Description: "",
			},
			"slug": schema.StringAttribute{
				Required:    true,
				Description: "Identifier of the custom field. It'll be used as key when storing the value.",
			},
			"name": schema.StringAttribute{
				Required:    true,
				Description: "Name of the custom field.",
			},
			"organization_id": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: "The ID of the organization owning the custom field.",
			},
			"text_properties": schema.SingleNestedAttribute{
				Computed:    true,
				Optional:    true,
				Attributes: map[string]schema.Attribute{
					"form_label": schema.StringAttribute{
						Computed:    true,
						Optional:    true,
						Description: "",
					},
					"form_help_text": schema.StringAttribute{
						Computed:    true,
						Optional:    true,
						Description: "",
					},
					"form_placeholder": schema.StringAttribute{
						Computed:    true,
						Optional:    true,
						Description: "",
					},
					"textarea": schema.BoolAttribute{
						Computed:    true,
						Optional:    true,
						Description: "",
					},
					"min_length": schema.Int64Attribute{
						Computed:    true,
						Optional:    true,
						Description: "",
					},
					"max_length": schema.Int64Attribute{
						Computed:    true,
						Optional:    true,
						Description: "",
					},
				},
				Description: "",
			},
			"number_properties": schema.SingleNestedAttribute{
				Computed:    true,
				Optional:    true,
				Attributes: map[string]schema.Attribute{
					"form_label": schema.StringAttribute{
						Computed:    true,
						Optional:    true,
						Description: "",
					},
					"form_help_text": schema.StringAttribute{
						Computed:    true,
						Optional:    true,
						Description: "",
					},
					"form_placeholder": schema.StringAttribute{
						Computed:    true,
						Optional:    true,
						Description: "",
					},
					"ge": schema.Int64Attribute{
						Computed:    true,
						Optional:    true,
						Description: "",
					},
					"le": schema.Int64Attribute{
						Computed:    true,
						Optional:    true,
						Description: "",
					},
				},
				Description: "",
			},
			"date_properties": schema.SingleNestedAttribute{
				Computed:    true,
				Optional:    true,
				Attributes: map[string]schema.Attribute{
					"form_label": schema.StringAttribute{
						Computed:    true,
						Optional:    true,
						Description: "",
					},
					"form_help_text": schema.StringAttribute{
						Computed:    true,
						Optional:    true,
						Description: "",
					},
					"form_placeholder": schema.StringAttribute{
						Computed:    true,
						Optional:    true,
						Description: "",
					},
					"ge": schema.Int64Attribute{
						Computed:    true,
						Optional:    true,
						Description: "",
					},
					"le": schema.Int64Attribute{
						Computed:    true,
						Optional:    true,
						Description: "",
					},
				},
				Description: "",
			},
			"checkbox_properties": schema.SingleNestedAttribute{
				Computed:    true,
				Optional:    true,
				Attributes: map[string]schema.Attribute{
					"form_label": schema.StringAttribute{
						Computed:    true,
						Optional:    true,
						Description: "",
					},
					"form_help_text": schema.StringAttribute{
						Computed:    true,
						Optional:    true,
						Description: "",
					},
					"form_placeholder": schema.StringAttribute{
						Computed:    true,
						Optional:    true,
						Description: "",
					},
				},
				Description: "",
			},
			"select_properties": schema.SingleNestedAttribute{
				Computed:    true,
				Optional:    true,
				Attributes: map[string]schema.Attribute{
					"form_label": schema.StringAttribute{
						Computed:    true,
						Optional:    true,
						Description: "",
					},
					"form_help_text": schema.StringAttribute{
						Computed:    true,
						Optional:    true,
						Description: "",
					},
					"form_placeholder": schema.StringAttribute{
						Computed:    true,
						Optional:    true,
						Description: "",
					},
					"options": schema.ListNestedAttribute{
						Required:    true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"value": schema.StringAttribute{
							Required:    true,
							Description: "",
						},
						"label": schema.StringAttribute{
							Required:    true,
							Description: "",
						},
					},
				},
						Description: "",
					},
				},
				Description: "",
			},
			"type": schema.StringAttribute{
				Required:    true,
				Description: "Which variant this is. Selects which of the optional blocks above applies.",
			},
		},
	}
}

func (r *CustomFieldResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}

	r.client = c
}

func (r *CustomFieldResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan CustomFieldModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	reqBody, err := plan.ToClientModel()
	if err != nil {
		resp.Diagnostics.AddError("Invalid custom_field configuration", err.Error())
		return
	}

	respBody, location, err := r.client.DoCreateRequest(ctx, "POST", "/custom-fields/", reqBody)
	if err != nil {
		resp.Diagnostics.AddError("Error creating custom_field", err.Error())
		return
	}

	// A create may answer a 201 whose body is an identifier and a link, not
	// the resource -- and sometimes only a Location header. Either way what
	// was created has to be READ BACK, not taken from the create's own
	// answer: taking it wrote empty strings over the values just sent,
	// "provider produced inconsistent result after apply".
	if created := client.IDFromCreate(respBody, location); created != "" {
		plan.Id = types.StringValue(created)
	}

	respBody, err = r.client.DoRequest(ctx, "GET", fmt.Sprintf("/custom-fields/%v", plan.Id.ValueString()), nil)
	if err != nil {
		resp.Diagnostics.AddError("Error reading back the created custom_field", err.Error())
		return
	}

	if len(respBody) > 0 {
		var result client.CustomField
		if err := json.Unmarshal(respBody, &result); err != nil {
			resp.Diagnostics.AddError("Error parsing response", err.Error())
			return
		}

		plan.FromClientModel(&result)
	}

	tflog.Trace(ctx, "created custom_field resource")
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *CustomFieldResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state CustomFieldModel

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// A resource with no identifier is not a resource. Without this the read
	// interpolates an empty id and asks the COLLECTION endpoint, which answers
	// 200 and a list -- so a state written before the id was known would look
	// healthy forever instead of being adopted again.
	if state.Id.ValueString() == "" {
		resp.State.RemoveResource(ctx)
		return
	}

	respBody, err := r.client.DoRequest(ctx, "GET", fmt.Sprintf("/custom-fields/%v", state.Id.ValueString()), nil)
	if err != nil {
		// GONE IS NOT BROKEN. A 404 here means the resource this state row
		// describes no longer exists -- deleted by hand, or by something else
		// that owns it -- and the honest answer is to drop the row and let the
		// plan decide whether to recreate it. Raising instead fails every plan
		// in the configuration, including the ones with nothing to do with this
		// resource, and leaves no way out but editing state by hand.
		//
		// ONLY IN Read. The same 404 after a create or an update is a real
		// failure: something we just wrote is missing.
		var apiErr *client.APIError
		if errors.As(err, &apiErr) && apiErr.StatusCode == http.StatusNotFound {
			resp.State.RemoveResource(ctx)
			return
		}

		resp.Diagnostics.AddError("Error reading custom_field", err.Error())
		return
	}

	var result client.CustomField
	if err := json.Unmarshal(respBody, &result); err != nil {
		resp.Diagnostics.AddError("Error parsing response", err.Error())
		return
	}

	state.FromClientModel(&result)

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *CustomFieldResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan CustomFieldModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// The identifiers come off state: they cannot change on an update, and the
	// plan's copy of a Computed one is unknown -- which is also the only place
	// an imported nested resource's parents live.
	var state CustomFieldModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// The UPDATE model, not the create one -- see ToUpdateModel.
	reqBody, err := plan.ToUpdateModel()
	if err != nil {
		resp.Diagnostics.AddError("Invalid custom_field configuration", err.Error())
		return
	}

	respBody, err := r.client.DoRequest(ctx, "PATCH", fmt.Sprintf("/custom-fields/%v", state.Id.ValueString()), reqBody)
	if err != nil {
		resp.Diagnostics.AddError("Error updating custom_field", err.Error())
		return
	}

	// AN UPDATE'S ANSWER IS NOT ALWAYS THE READ'S. An API may answer a PUT with the list of
	// changes it made -- ["Description changed from 'a' to 'b'"] -- and some
	// updates answer nothing at all; neither is the resource, and
	// unmarshalling either one is "Error parsing response" AFTER the server
	// has already accepted the change. What it now looks like is read back.
	respBody, err = r.client.DoRequest(ctx, "GET", fmt.Sprintf("/custom-fields/%v", state.Id.ValueString()), nil)
	if err != nil {
		resp.Diagnostics.AddError("Error reading back the updated custom_field", err.Error())
		return
	}

	if len(respBody) > 0 {
		var result client.CustomField
		if err := json.Unmarshal(respBody, &result); err != nil {
			resp.Diagnostics.AddError("Error parsing response", err.Error())
			return
		}

		plan.FromClientModel(&result)
	}

	tflog.Trace(ctx, "updated custom_field resource")
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *CustomFieldResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state CustomFieldModel

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	_, err := r.client.DoRequest(ctx, "DELETE", fmt.Sprintf("/custom-fields/%v", state.Id.ValueString()), nil)
	if err != nil {
		resp.Diagnostics.AddError("Error deleting custom_field", err.Error())
		return
	}

	tflog.Trace(ctx, "deleted custom_field resource")
}

func (r *CustomFieldResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
