// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/n-at-han-k/terraform-provider-polar/internal/client"
)

// CustomersExternalMemberModel is the Terraform model for customers_external_member.
type CustomersExternalMemberModel struct {
	Id types.String `tfsdk:"id"`
	CreatedAt types.String `tfsdk:"created_at"`
	ModifiedAt types.String `tfsdk:"modified_at"`
	CustomerId types.String `tfsdk:"customer_id"`
	Email types.String `tfsdk:"email"`
	Name types.String `tfsdk:"name"`
	ExternalId types.String `tfsdk:"external_id"`
	Role types.String `tfsdk:"role"`
}


// ToClientModel converts a Terraform model to a client model.
func (m *CustomersExternalMemberModel) ToClientModel() (*client.MemberCreateFromCustomer, error) {
	out := &client.MemberCreateFromCustomer{}
	if !m.Email.IsNull() && !m.Email.IsUnknown() {
		out.Email = m.Email.ValueString()
	}
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		out.Name = m.Name.ValueString()
	}
	if !m.ExternalId.IsNull() && !m.ExternalId.IsUnknown() {
		out.ExternalId = m.ExternalId.ValueString()
	}
	if !m.Role.IsNull() && !m.Role.IsUnknown() {
		out.Role = m.Role.ValueString()
	}
	return out, nil
}

// ToUpdateModel converts a Terraform model to the UPDATE client model, which is
// a different shape from the create one: RT's update bodies have no
// inboundProtocolConfiguration and no id, and sending the create model to the
// patch endpoint is answered with "provided request body content is not in the
// expected format".
//
// Fields the patch model does not declare are simply absent here -- the
// generator only emits the ones it has.
func (m *CustomersExternalMemberModel) ToUpdateModel() (*client.MemberUpdate, error) {
	out := &client.MemberUpdate{}
	if !m.Email.IsNull() && !m.Email.IsUnknown() {
		out.Email = m.Email.ValueString()
	}
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		out.Name = m.Name.ValueString()
	}
	if !m.Role.IsNull() && !m.Role.IsUnknown() {
		out.Role = m.Role.ValueString()
	}
	return out, nil
}

// FromClientModel updates the Terraform model from a client model.
func (m *CustomersExternalMemberModel) FromClientModel(c *client.Member) {
	m.Id = types.StringValue(string(c.Id))
	m.CreatedAt = types.StringValue(c.CreatedAt)
	m.ModifiedAt = types.StringValue(c.ModifiedAt)
	m.CustomerId = types.StringValue(c.CustomerId)
	m.Email = types.StringValue(c.Email)
	m.Name = types.StringValue(c.Name)
	m.ExternalId = types.StringValue(c.ExternalId)
	m.Role = types.StringValue(c.Role)
}
