// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"context"
	"fmt"

	"encoding/json"


	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	"github.com/n-at-han-k/terraform-provider-polar/internal/client"
)

var _ datasource.DataSource = &CustomerDataSource{}

func NewCustomerDataSource() datasource.DataSource {
	return &CustomerDataSource{}
}

type CustomerDataSource struct {
	client *client.Client
}

func (d *CustomerDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_customer"
}

func (d *CustomerDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Fetches a customer data source.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:    true,
				Description: "The ID of the customer.",
			},
			"created_at": schema.StringAttribute{
				Computed:    true,
				Description: "Creation timestamp of the object.",
			},
			"modified_at": schema.StringAttribute{
				Computed:    true,
				Description: "Last modification timestamp of the object.",
			},
			"metadata": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"external_id": schema.StringAttribute{
				Computed:    true,
				Description: "The ID of the customer in your system. This must be unique within the organization. Once set, it can't be updated.",
			},
			"name": schema.StringAttribute{
				Computed:    true,
				Description: "The name of the customer.",
			},
			"billing_address": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"tax_id": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"locale": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"organization_id": schema.StringAttribute{
				Computed:    true,
				Description: "The ID of the organization owning the customer.",
			},
			"owner": schema.StringAttribute{
				Computed:    true,
				Description: "Optional owner member to create with the customer. If not provided, an owner member will be automatically created using the customer's email and name.",
			},
			"customer_individual_type": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"customer_team_type": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"customer_individual_email": schema.StringAttribute{
				Computed:    true,
				Description: "The email address of the customer. This must be unique within the organization.",
			},
			"customer_team_email": schema.StringAttribute{
				Computed:    true,
				Description: "The email address of the team customer. Optional for team customers — if omitted, an owner with an email must be provided.",
			},
		},
	}
}

func (d *CustomerDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Data Source Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}

	d.client = c
}

func (d *CustomerDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config CustomerModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	respBody, err := d.client.DoRequest(ctx, "GET", fmt.Sprintf("/customers/%v", config.Id.ValueString()), nil)
	if err != nil {
		resp.Diagnostics.AddError("Error reading customer", err.Error())
		return
	}

	var result client.Customer
	if err := json.Unmarshal(respBody, &result); err != nil {
		resp.Diagnostics.AddError("Error parsing response", err.Error())
		return
	}

	config.FromClientModel(&result)

	tflog.Trace(ctx, "read customer data source")
	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
