// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"context"
	"fmt"

	"encoding/json"


	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	"github.com/n-at-han-k/terraform-provider-polar/internal/client"
)

var _ datasource.DataSource = &DiscountDataSource{}

func NewDiscountDataSource() datasource.DataSource {
	return &DiscountDataSource{}
}

type DiscountDataSource struct {
	client *client.Client
}

func (d *DiscountDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_discount"
}

func (d *DiscountDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Fetches a discount data source.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:    true,
				Description: "The ID of the object.",
			},
			"created_at": schema.StringAttribute{
				Computed:    true,
				Description: "Creation timestamp of the object.",
			},
			"modified_at": schema.StringAttribute{
				Computed:    true,
				Description: "Last modification timestamp of the object.",
			},
			"metadata": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"name": schema.StringAttribute{
				Required:    true,
				Description: "Name of the discount. Will be displayed to the customer when the discount is applied.",
			},
			"code": schema.StringAttribute{
				Computed:    true,
				Description: "Code customers can use to apply the discount during checkout.",
			},
			"starts_at": schema.StringAttribute{
				Computed:    true,
				Description: "Timestamp after which the discount is redeemable.",
			},
			"ends_at": schema.StringAttribute{
				Computed:    true,
				Description: "Timestamp after which the discount is no longer redeemable.",
			},
			"max_redemptions": schema.Int64Attribute{
				Computed:    true,
				Description: "Maximum number of times the discount can be redeemed.",
			},
			"max_redemptions_per_customer": schema.Int64Attribute{
				Computed:    true,
				Description: "Maximum number of times the discount can be redeemed by a single customer.",
			},
			"products": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"organization_id": schema.StringAttribute{
				Computed:    true,
				Description: "The organization ID.",
			},
			"duration": schema.StringAttribute{
				Required:    true,
				Description: "",
			},
			"duration_in_months": schema.Int64Attribute{
				Computed:    true,
				Description: "",
			},
			"amount": schema.Int64Attribute{
				Computed:    true,
				Description: "",
			},
			"currency": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"amounts": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "Map of currency to fixed amount to discount from the total.",
			},
			"basis_points": schema.Int64Attribute{
				Computed:    true,
				Description: "Discount percentage in basis points. A basis point is 1/100th of a percent. For example, 1000 basis points equals a 10% discount.",
			},
			"type": schema.StringAttribute{
				Required:    true,
				Description: "",
			},
		},
	}
}

func (d *DiscountDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Data Source Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}

	d.client = c
}

func (d *DiscountDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config DiscountModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	respBody, err := d.client.DoRequest(ctx, "GET", fmt.Sprintf("/discounts/%v", config.Id.ValueString()), nil)
	if err != nil {
		resp.Diagnostics.AddError("Error reading discount", err.Error())
		return
	}

	var result client.Discount
	if err := json.Unmarshal(respBody, &result); err != nil {
		resp.Diagnostics.AddError("Error parsing response", err.Error())
		return
	}

	config.FromClientModel(&result)

	tflog.Trace(ctx, "read discount data source")
	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
