// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"

	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-log/tflog"

	"github.com/n-at-han-k/terraform-provider-polar/internal/client"
)

var _ resource.Resource = &DiscountResource{}
var _ resource.ResourceWithImportState = &DiscountResource{}
var _ resource.ResourceWithValidateConfig = &DiscountResource{}

func NewDiscountResource() resource.Resource {
	return &DiscountResource{}
}

type DiscountResource struct {
	client *client.Client
}

func (r *DiscountResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_discount"
}

func (r *DiscountResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a discount resource.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:    true,
				Description: "The ID of the object.",
			},
			"metadata": schema.MapAttribute{
				Computed:    true,
				Optional:    true,
				ElementType: types.StringType,
				Description: "",
			},
			"name": schema.StringAttribute{
				Required:    true,
				Description: "Name of the discount. Will be displayed to the customer when the discount is applied.",
			},
			"code": schema.StringAttribute{
				Optional:    true,
				Description: "Code customers can use to apply the discount during checkout.",
			},
			"starts_at": schema.StringAttribute{
				Optional:    true,
				Description: "Timestamp after which the discount is redeemable.",
			},
			"ends_at": schema.StringAttribute{
				Optional:    true,
				Description: "Timestamp after which the discount is no longer redeemable.",
			},
			"max_redemptions": schema.Int64Attribute{
				Optional:    true,
				Description: "Maximum number of times the discount can be redeemed.",
			},
			"max_redemptions_per_customer": schema.Int64Attribute{
				Optional:    true,
				Description: "Maximum number of times the discount can be redeemed by a single customer.",
			},
			"products": schema.ListAttribute{
				Optional:    true,
				ElementType: types.StringType,
				Description: "",
			},
			"duration": schema.StringAttribute{
				Required: true,
				Validators: []validator.String{
					stringvalidator.OneOf(
						"once",
						"forever",
						"repeating",
					),
				},
				Description: "",
			},
			"duration_in_months": schema.Int64Attribute{
				Optional:    true,
				Description: "",
			},
			"amount": schema.Int64Attribute{
				Optional:    true,
				Description: "",
			},
			"currency": schema.StringAttribute{
				Optional: true,
				Validators: []validator.String{
					stringvalidator.OneOf(
						"aed",
						"all",
						"amd",
						"aoa",
						"ars",
						"aud",
						"awg",
						"azn",
						"bam",
						"bbd",
						"bdt",
						"bif",
						"bmd",
						"bnd",
						"bob",
						"brl",
						"bsd",
						"bwp",
						"bzd",
						"cad",
						"cdf",
						"chf",
						"clp",
						"cny",
						"cop",
						"crc",
						"cve",
						"czk",
						"djf",
						"dkk",
						"dop",
						"dzd",
						"egp",
						"etb",
						"eur",
						"fjd",
						"fkp",
						"gbp",
						"gel",
						"gip",
						"gmd",
						"gnf",
						"gtq",
						"gyd",
						"hkd",
						"hnl",
						"htg",
						"huf",
						"idr",
						"ils",
						"inr",
						"isk",
						"jmd",
						"jpy",
						"kes",
						"kgs",
						"khr",
						"kmf",
						"krw",
						"kyd",
						"kzt",
						"lak",
						"lkr",
						"lrd",
						"lsl",
						"mad",
						"mdl",
						"mga",
						"mkd",
						"mnt",
						"mop",
						"mur",
						"mvr",
						"mwk",
						"mxn",
						"myr",
						"mzn",
						"nad",
						"ngn",
						"nio",
						"nok",
						"npr",
						"nzd",
						"pab",
						"pen",
						"pgk",
						"php",
						"pkr",
						"pln",
						"pyg",
						"qar",
						"ron",
						"rsd",
						"rwf",
						"sar",
						"sbd",
						"scr",
						"sek",
						"sgd",
						"shp",
						"sos",
						"srd",
						"szl",
						"thb",
						"tjs",
						"top",
						"try",
						"ttd",
						"twd",
						"tzs",
						"uah",
						"ugx",
						"usd",
						"uyu",
						"uzs",
						"vnd",
						"vuv",
						"wst",
						"xaf",
						"xcd",
						"xcg",
						"xof",
						"xpf",
						"yer",
						"zar",
						"zmw",
					),
				},
				Description: "",
			},
			"amounts": schema.MapAttribute{
				Optional:    true,
				ElementType: types.Int64Type,
				Description: "Map of currency to fixed amount to discount from the total.",
			},
			"basis_points": schema.Int64Attribute{
				Optional:    true,
				Description: "Discount percentage in basis points. A basis point is 1/100th of a percent. For example, 1000 basis points equals a 10% discount.",
			},
			"type": schema.StringAttribute{
				Required: true,
				Validators: []validator.String{
					stringvalidator.OneOf(
						"fixed",
						"percentage",
					),
				},
				Description: "",
			},
		},
	}
}

// ValidateConfig refuses WHAT THE DISCRIMINATOR SAYS: a field that belongs to
// another variant, and one the chosen variant demands and nobody set.
//
// amount are the
// fields a flattened union became, one set per variant, and nothing in the schema
// stops a configuration from filling two of them -- or from filling the one
// type did not ask for. Polar answers 422 for that, which arrives
// after the plan as a refused request rather than as a message naming the two
// attributes that disagreed.
//
// The plan is where it can be named.
func (r *DiscountResource) ValidateConfig(ctx context.Context, req resource.ValidateConfigRequest, resp *resource.ValidateConfigResponse) {
	var config DiscountModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// type may be unknown while a variable decides it, and there is
	// nothing to check against until it is known.
	if config.Type.IsUnknown() {
		return
	}

	// A FIELD OF THE ONE BLOCK EVERY VARIANT SHARES, so there is no other block
	// to name: the message is about the field.
	if !config.Amount.IsNull() && !config.Type.IsUnknown() && config.Type.ValueString() != "fixed" {
		resp.Diagnostics.AddAttributeError(
			path.Root("amount"),
			"Conflicting properties field",
			fmt.Sprintf("%q can only be set when type is %q.", "amount", "fixed"),
		)
	}
	// A FIELD OF THE ONE BLOCK EVERY VARIANT SHARES, so there is no other block
	// to name: the message is about the field.
	if !config.Currency.IsNull() && !config.Type.IsUnknown() && config.Type.ValueString() != "fixed" {
		resp.Diagnostics.AddAttributeError(
			path.Root("currency"),
			"Conflicting properties field",
			fmt.Sprintf("%q can only be set when type is %q.", "currency", "fixed"),
		)
	}
	// A FIELD OF THE ONE BLOCK EVERY VARIANT SHARES, so there is no other block
	// to name: the message is about the field.
	if !config.Amounts.IsNull() && !config.Type.IsUnknown() && config.Type.ValueString() != "fixed" {
		resp.Diagnostics.AddAttributeError(
			path.Root("amounts"),
			"Conflicting properties field",
			fmt.Sprintf("%q can only be set when type is %q.", "amounts", "fixed"),
		)
	}
	// A FIELD OF THE ONE BLOCK EVERY VARIANT SHARES, so there is no other block
	// to name: the message is about the field.
	if !config.BasisPoints.IsNull() && !config.Type.IsUnknown() && config.Type.ValueString() != "percentage" {
		resp.Diagnostics.AddAttributeError(
			path.Root("basis_points"),
			"Conflicting properties field",
			fmt.Sprintf("%q can only be set when type is %q.", "basis_points", "percentage"),
		)
	}
	// A FIELD OF THE ONE BLOCK EVERY VARIANT SHARES, so there is no other block
	// to name: the message is about the field.
	if !config.DurationInMonths.IsNull() && !config.Duration.IsUnknown() && config.Duration.ValueString() != "repeating" {
		resp.Diagnostics.AddAttributeError(
			path.Root("duration_in_months"),
			"Conflicting properties field",
			fmt.Sprintf("%q can only be set when duration is %q.", "duration_in_months", "repeating"),
		)
	}
	if config.Type.ValueString() == "fixed" && config.Amounts.IsNull() {
		resp.Diagnostics.AddAttributeError(
			path.Root("amounts"),
			"Missing required property",
			fmt.Sprintf("%q is required when type is %q.", "amounts", "fixed"),
		)
	}
	if config.Type.ValueString() == "percentage" && config.BasisPoints.IsNull() {
		resp.Diagnostics.AddAttributeError(
			path.Root("basis_points"),
			"Missing required property",
			fmt.Sprintf("%q is required when type is %q.", "basis_points", "percentage"),
		)
	}
	if config.Duration.ValueString() == "repeating" && config.DurationInMonths.IsNull() {
		resp.Diagnostics.AddAttributeError(
			path.Root("duration_in_months"),
			"Missing required property",
			fmt.Sprintf("%q is required when duration is %q.", "duration_in_months", "repeating"),
		)
	}
}

func (r *DiscountResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}

	r.client = c
}

func (r *DiscountResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan DiscountModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	reqBody, err := plan.ToClientModel()
	if err != nil {
		resp.Diagnostics.AddError("Invalid discount configuration", err.Error())
		return
	}

	respBody, location, err := r.client.DoCreateRequest(ctx, "POST", "/discounts/", reqBody)
	if err != nil {
		resp.Diagnostics.AddError("Error creating discount", err.Error())
		return
	}

	// A create may answer a 201 whose body is an identifier and a link, not
	// the resource -- and sometimes only a Location header. Either way what
	// was created has to be READ BACK, not taken from the create's own
	// answer: taking it wrote empty strings over the values just sent,
	// "provider produced inconsistent result after apply".
	if created := client.IDFromCreate(respBody, location); created != "" {
		plan.Id = types.StringValue(created)
	}

	respBody, err = r.client.DoRequest(ctx, "GET", fmt.Sprintf("/discounts/%v", plan.Id.ValueString()), nil)
	if err != nil {
		resp.Diagnostics.AddError("Error reading back the created discount", err.Error())
		return
	}

	if len(respBody) > 0 {
		var result client.Discount
		if err := json.Unmarshal(respBody, &result); err != nil {
			resp.Diagnostics.AddError("Error parsing response", err.Error())
			return
		}

		plan.FromClientModel(&result)
	}

	tflog.Trace(ctx, "created discount resource")
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *DiscountResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state DiscountModel

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// A resource with no identifier is not a resource. Without this the read
	// interpolates an empty id and asks the COLLECTION endpoint, which answers
	// 200 and a list -- so a state written before the id was known would look
	// healthy forever instead of being adopted again.
	if state.Id.ValueString() == "" {
		resp.State.RemoveResource(ctx)
		return
	}

	respBody, err := r.client.DoRequest(ctx, "GET", fmt.Sprintf("/discounts/%v", state.Id.ValueString()), nil)
	if err != nil {
		// GONE IS NOT BROKEN. A 404 here means the resource this state row
		// describes no longer exists -- deleted by hand, or by something else
		// that owns it -- and the honest answer is to drop the row and let the
		// plan decide whether to recreate it. Raising instead fails every plan
		// in the configuration, including the ones with nothing to do with this
		// resource, and leaves no way out but editing state by hand.
		//
		// ONLY IN Read. The same 404 after a create or an update is a real
		// failure: something we just wrote is missing.
		var apiErr *client.APIError
		if errors.As(err, &apiErr) && apiErr.StatusCode == http.StatusNotFound {
			resp.State.RemoveResource(ctx)
			return
		}

		resp.Diagnostics.AddError("Error reading discount", err.Error())
		return
	}

	var result client.Discount
	if err := json.Unmarshal(respBody, &result); err != nil {
		resp.Diagnostics.AddError("Error parsing response", err.Error())
		return
	}

	state.FromClientModel(&result)

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *DiscountResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan DiscountModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// The identifiers come off state: they cannot change on an update, and the
	// plan's copy of a Computed one is unknown -- which is also the only place
	// an imported nested resource's parents live.
	var state DiscountModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// The UPDATE model, not the create one -- see ToUpdateModel.
	reqBody, err := plan.ToUpdateModel()
	if err != nil {
		resp.Diagnostics.AddError("Invalid discount configuration", err.Error())
		return
	}

	respBody, err := r.client.DoRequest(ctx, "PATCH", fmt.Sprintf("/discounts/%v", state.Id.ValueString()), reqBody)
	if err != nil {
		resp.Diagnostics.AddError("Error updating discount", err.Error())
		return
	}

	// AN UPDATE'S ANSWER IS NOT ALWAYS THE READ'S. An API may answer a PUT with the list of
	// changes it made -- ["Description changed from 'a' to 'b'"] -- and some
	// updates answer nothing at all; neither is the resource, and
	// unmarshalling either one is "Error parsing response" AFTER the server
	// has already accepted the change. What it now looks like is read back.
	respBody, err = r.client.DoRequest(ctx, "GET", fmt.Sprintf("/discounts/%v", state.Id.ValueString()), nil)
	if err != nil {
		resp.Diagnostics.AddError("Error reading back the updated discount", err.Error())
		return
	}

	if len(respBody) > 0 {
		var result client.Discount
		if err := json.Unmarshal(respBody, &result); err != nil {
			resp.Diagnostics.AddError("Error parsing response", err.Error())
			return
		}

		plan.FromClientModel(&result)
	}

	tflog.Trace(ctx, "updated discount resource")
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *DiscountResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state DiscountModel

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	_, err := r.client.DoRequest(ctx, "DELETE", fmt.Sprintf("/discounts/%v", state.Id.ValueString()), nil)
	if err != nil {
		resp.Diagnostics.AddError("Error deleting discount", err.Error())
		return
	}

	tflog.Trace(ctx, "deleted discount resource")
}

func (r *DiscountResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
