// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"

	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-log/tflog"

	"github.com/n-at-han-k/terraform-provider-polar/internal/client"
)

var _ resource.Resource = &MeterResource{}
var _ resource.ResourceWithImportState = &MeterResource{}

func NewMeterResource() resource.Resource {
	return &MeterResource{}
}

type MeterResource struct {
	client *client.Client
}

func (r *MeterResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_meter"
}

func (r *MeterResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a meter resource.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:    true,
				Description: "The ID of the object.",
			},
			"metadata": schema.MapAttribute{
				Computed:    true,
				Optional:    true,
				ElementType: types.StringType,
				Description: "",
			},
			"name": schema.StringAttribute{
				Required:    true,
				Description: "The name of the meter. Will be shown on customer's invoices and usage.",
			},
			"unit": schema.StringAttribute{
				Optional: true,
				Validators: []validator.String{
					stringvalidator.OneOf(
						"scalar",
						"token",
						"custom",
					),
				},
				Description: "",
			},
			"custom_label": schema.StringAttribute{
				Optional:    true,
				Description: "The label for the custom unit.",
			},
			"custom_multiplier": schema.Int64Attribute{
				Optional:    true,
				Description: "The multiplier to convert from base unit to display scale.",
			},
			"filter": schema.SingleNestedAttribute{
				Required: true,
				Attributes: map[string]schema.Attribute{
					"conjunction": schema.StringAttribute{
						Required: true,
						Validators: []validator.String{
							stringvalidator.OneOf(
								"and",
								"or",
							),
						},
						Description: "",
					},
					"clauses": schema.ListNestedAttribute{
						Required: true,
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"property": schema.StringAttribute{
									Required:    true,
									Description: "",
								},
								"operator": schema.StringAttribute{
									Required: true,
									Validators: []validator.String{
										stringvalidator.OneOf(
											"eq",
											"ne",
											"gt",
											"gte",
											"lt",
											"lte",
											"like",
											"not_like",
										),
									},
									Description: "",
								},
								"value": schema.StringAttribute{
									Required:    true,
									Description: "",
								},
							},
						},
						Description: "",
					},
				},
				Description: "The filter to apply on events that'll be used to calculate the meter.",
			},
			"aggregation": schema.SingleNestedAttribute{
				Required: true,
				Attributes: map[string]schema.Attribute{
					"property": schema.StringAttribute{
						Optional:    true,
						Description: "",
					},
					"func": schema.StringAttribute{
						Required: true,
						Validators: []validator.String{
							stringvalidator.OneOf(
								"avg",
								"count",
								"max",
								"min",
								"sum",
								"unique",
							),
						},
						Description: "Which variant this is. Selects which of the optional blocks above applies.",
					},
				},
				Description: "The aggregation to apply on the filtered events to calculate the meter.",
			},
		},
	}
}

func (r *MeterResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}

	r.client = c
}

func (r *MeterResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan MeterModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	reqBody, err := plan.ToClientModel()
	if err != nil {
		resp.Diagnostics.AddError("Invalid meter configuration", err.Error())
		return
	}

	respBody, location, err := r.client.DoCreateRequest(ctx, "POST", "/meters/", reqBody)
	if err != nil {
		resp.Diagnostics.AddError("Error creating meter", err.Error())
		return
	}

	// A create may answer a 201 whose body is an identifier and a link, not
	// the resource -- and sometimes only a Location header. Either way what
	// was created has to be READ BACK, not taken from the create's own
	// answer: taking it wrote empty strings over the values just sent,
	// "provider produced inconsistent result after apply".
	if created := client.IDFromCreate(respBody, location); created != "" {
		plan.Id = types.StringValue(created)
	}

	respBody, err = r.client.DoRequest(ctx, "GET", fmt.Sprintf("/meters/%v", plan.Id.ValueString()), nil)
	if err != nil {
		resp.Diagnostics.AddError("Error reading back the created meter", err.Error())
		return
	}

	if len(respBody) > 0 {
		var result client.Meter
		if err := json.Unmarshal(respBody, &result); err != nil {
			resp.Diagnostics.AddError("Error parsing response", err.Error())
			return
		}

		plan.FromClientModel(&result)
	}

	tflog.Trace(ctx, "created meter resource")
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *MeterResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state MeterModel

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// A resource with no identifier is not a resource. Without this the read
	// interpolates an empty id and asks the COLLECTION endpoint, which answers
	// 200 and a list -- so a state written before the id was known would look
	// healthy forever instead of being adopted again.
	if state.Id.ValueString() == "" {
		resp.State.RemoveResource(ctx)
		return
	}

	respBody, err := r.client.DoRequest(ctx, "GET", fmt.Sprintf("/meters/%v", state.Id.ValueString()), nil)
	if err != nil {
		// GONE IS NOT BROKEN. A 404 here means the resource this state row
		// describes no longer exists -- deleted by hand, or by something else
		// that owns it -- and the honest answer is to drop the row and let the
		// plan decide whether to recreate it. Raising instead fails every plan
		// in the configuration, including the ones with nothing to do with this
		// resource, and leaves no way out but editing state by hand.
		//
		// ONLY IN Read. The same 404 after a create or an update is a real
		// failure: something we just wrote is missing.
		var apiErr *client.APIError
		if errors.As(err, &apiErr) && apiErr.StatusCode == http.StatusNotFound {
			resp.State.RemoveResource(ctx)
			return
		}

		resp.Diagnostics.AddError("Error reading meter", err.Error())
		return
	}

	var result client.Meter
	if err := json.Unmarshal(respBody, &result); err != nil {
		resp.Diagnostics.AddError("Error parsing response", err.Error())
		return
	}

	state.FromClientModel(&result)

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *MeterResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan MeterModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// The identifiers come off state: they cannot change on an update, and the
	// plan's copy of a Computed one is unknown -- which is also the only place
	// an imported nested resource's parents live.
	var state MeterModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// The UPDATE model, not the create one -- see ToUpdateModel.
	reqBody, err := plan.ToUpdateModel()
	if err != nil {
		resp.Diagnostics.AddError("Invalid meter configuration", err.Error())
		return
	}

	respBody, err := r.client.DoRequest(ctx, "PATCH", fmt.Sprintf("/meters/%v", state.Id.ValueString()), reqBody)
	if err != nil {
		resp.Diagnostics.AddError("Error updating meter", err.Error())
		return
	}

	// AN UPDATE'S ANSWER IS NOT ALWAYS THE READ'S. An API may answer a PUT with the list of
	// changes it made -- ["Description changed from 'a' to 'b'"] -- and some
	// updates answer nothing at all; neither is the resource, and
	// unmarshalling either one is "Error parsing response" AFTER the server
	// has already accepted the change. What it now looks like is read back.
	respBody, err = r.client.DoRequest(ctx, "GET", fmt.Sprintf("/meters/%v", state.Id.ValueString()), nil)
	if err != nil {
		resp.Diagnostics.AddError("Error reading back the updated meter", err.Error())
		return
	}

	if len(respBody) > 0 {
		var result client.Meter
		if err := json.Unmarshal(respBody, &result); err != nil {
			resp.Diagnostics.AddError("Error parsing response", err.Error())
			return
		}

		plan.FromClientModel(&result)
	}

	tflog.Trace(ctx, "updated meter resource")
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *MeterResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	// No delete endpoint available; remove the resource from state.
}

func (r *MeterResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
