// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"encoding/json"



	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"

	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-log/tflog"



	"github.com/n-at-han-k/terraform-provider-polar/internal/client"
)

var _ resource.Resource = &MetricsDashboardResource{}
var _ resource.ResourceWithImportState = &MetricsDashboardResource{}

func NewMetricsDashboardResource() resource.Resource {
	return &MetricsDashboardResource{}
}

type MetricsDashboardResource struct {
	client *client.Client
}

func (r *MetricsDashboardResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_metrics_dashboard"
}

func (r *MetricsDashboardResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a metrics_dashboard resource.",
		Attributes: map[string]schema.Attribute{
			"created_at": schema.StringAttribute{
				Computed:    true,
				Description: "Creation timestamp of the object.",
			},
			"modified_at": schema.StringAttribute{
				Computed:    true,
				Description: "Last modification timestamp of the object.",
			},
			"id": schema.StringAttribute{
				Computed:    true,
				Description: "The ID of the object.",
			},
			"name": schema.StringAttribute{
				Required:    true,
				Description: "Display name for the dashboard.",
			},
			"metrics": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Optional:    true,
				Description: "List of metric slugs displayed in this dashboard.",
			},
			"organization_id": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: "The ID of the organization owning this dashboard.",
			},
		},
	}
}

func (r *MetricsDashboardResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}

	r.client = c
}

func (r *MetricsDashboardResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan MetricsDashboardModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	reqBody, err := plan.ToClientModel()
	if err != nil {
		resp.Diagnostics.AddError("Invalid metrics_dashboard configuration", err.Error())
		return
	}

	respBody, location, err := r.client.DoCreateRequest(ctx, "POST", "/metrics/dashboards", reqBody)
	if err != nil {
		resp.Diagnostics.AddError("Error creating metrics_dashboard", err.Error())
		return
	}

	// RT's create answers a 201 whose body is an identifier and a link, not
	// the resource -- and sometimes only a Location header. Either way what
	// was created has to be READ BACK, not taken from the create's own
	// answer: taking it wrote empty strings over the values just sent,
	// "provider produced inconsistent result after apply".
	if created := client.IDFromCreate(respBody, location); created != "" {
		plan.Id = types.StringValue(created)
	}

	respBody, err = r.client.DoRequest(ctx, "GET", fmt.Sprintf("/metrics/dashboards/%v", plan.Id.ValueString()), nil)
	if err != nil {
		resp.Diagnostics.AddError("Error reading back the created metrics_dashboard", err.Error())
		return
	}

	if len(respBody) > 0 {
		var result client.MetricDashboardSchema
		if err := json.Unmarshal(respBody, &result); err != nil {
			resp.Diagnostics.AddError("Error parsing response", err.Error())
			return
		}

		plan.FromClientModel(&result)
	}

	tflog.Trace(ctx, "created metrics_dashboard resource")
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *MetricsDashboardResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state MetricsDashboardModel

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// A resource with no identifier is not a resource. Without this the read
	// interpolates an empty id and asks the COLLECTION endpoint, which answers
	// 200 and a list -- so a state written before the id was known would look
	// healthy forever instead of being adopted again.
	if state.Id.ValueString() == "" {
		resp.State.RemoveResource(ctx)
		return
	}

	respBody, err := r.client.DoRequest(ctx, "GET", fmt.Sprintf("/metrics/dashboards/%v", state.Id.ValueString()), nil)
	if err != nil {
		// GONE IS NOT BROKEN. A 404 here means the resource this state row
		// describes no longer exists -- deleted by hand, or by something else
		// that owns it -- and the honest answer is to drop the row and let the
		// plan decide whether to recreate it. Raising instead fails every plan
		// in the configuration, including the ones with nothing to do with this
		// resource, and leaves no way out but editing state by hand.
		//
		// ONLY IN Read. The same 404 after a create or an update is a real
		// failure: something we just wrote is missing.
		var apiErr *client.APIError
		if errors.As(err, &apiErr) && apiErr.StatusCode == http.StatusNotFound {
			resp.State.RemoveResource(ctx)
			return
		}

		resp.Diagnostics.AddError("Error reading metrics_dashboard", err.Error())
		return
	}

	var result client.MetricDashboardSchema
	if err := json.Unmarshal(respBody, &result); err != nil {
		resp.Diagnostics.AddError("Error parsing response", err.Error())
		return
	}

	state.FromClientModel(&result)

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *MetricsDashboardResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan MetricsDashboardModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// The identifiers come off state: they cannot change on an update, and the
	// plan's copy of a Computed one is unknown -- which is also the only place
	// an imported nested resource's parents live.
	var state MetricsDashboardModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// The UPDATE model, not the create one -- see ToUpdateModel.
	reqBody, err := plan.ToUpdateModel()
	if err != nil {
		resp.Diagnostics.AddError("Invalid metrics_dashboard configuration", err.Error())
		return
	}

	respBody, err := r.client.DoRequest(ctx, "PATCH", fmt.Sprintf("/metrics/dashboards/%v", state.Id.ValueString()), reqBody)
	if err != nil {
		resp.Diagnostics.AddError("Error updating metrics_dashboard", err.Error())
		return
	}

	// AN UPDATE'S ANSWER IS NOT THE READ'S. RT answers a PUT with the list of
	// changes it made -- ["Description changed from 'a' to 'b'"] -- and some
	// updates answer nothing at all; neither is the resource, and
	// unmarshalling either one is "Error parsing response" AFTER the server
	// has already accepted the change. What it now looks like is read back.
	respBody, err = r.client.DoRequest(ctx, "GET", fmt.Sprintf("/metrics/dashboards/%v", state.Id.ValueString()), nil)
	if err != nil {
		resp.Diagnostics.AddError("Error reading back the updated metrics_dashboard", err.Error())
		return
	}

	if len(respBody) > 0 {
		var result client.MetricDashboardSchema
		if err := json.Unmarshal(respBody, &result); err != nil {
			resp.Diagnostics.AddError("Error parsing response", err.Error())
			return
		}

		plan.FromClientModel(&result)
	}

	tflog.Trace(ctx, "updated metrics_dashboard resource")
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *MetricsDashboardResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state MetricsDashboardModel

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	_, err := r.client.DoRequest(ctx, "DELETE", fmt.Sprintf("/metrics/dashboards/%v", state.Id.ValueString()), nil)
	if err != nil {
		resp.Diagnostics.AddError("Error deleting metrics_dashboard", err.Error())
		return
	}

	tflog.Trace(ctx, "deleted metrics_dashboard resource")
}

func (r *MetricsDashboardResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
