// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"context"
	"fmt"

	"encoding/json"


	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	"github.com/n-at-han-k/terraform-provider-polar/internal/client"
)

var _ datasource.DataSource = &OrderDataSource{}

func NewOrderDataSource() datasource.DataSource {
	return &OrderDataSource{}
}

type OrderDataSource struct {
	client *client.Client
}

func (d *OrderDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_order"
}

func (d *OrderDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Fetches a order data source.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:    true,
				Description: "The ID of the object.",
			},
			"created_at": schema.StringAttribute{
				Computed:    true,
				Description: "Creation timestamp of the object.",
			},
			"modified_at": schema.StringAttribute{
				Computed:    true,
				Description: "Last modification timestamp of the object.",
			},
			"custom_field_data": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "Key-value object storing custom field values.",
			},
			"metadata": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"organization_id": schema.StringAttribute{
				Computed:    true,
				Description: "The organization ID.",
			},
			"customer_id": schema.StringAttribute{
				Required:    true,
				Description: "",
			},
			"product_id": schema.StringAttribute{
				Required:    true,
				Description: "",
			},
			"currency": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"amount": schema.Int64Attribute{
				Computed:    true,
				Description: "A custom amount to charge, in the smallest currency unit. Overrides the product's price; defaults to the product's configured price (0 for free products). A positive amount must be at least the currency's minimum.",
			},
			"description": schema.StringAttribute{
				Computed:    true,
				Description: "A summary description of the order.",
			},
		},
	}
}

func (d *OrderDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Data Source Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}

	d.client = c
}

func (d *OrderDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config OrderModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	respBody, err := d.client.DoRequest(ctx, "GET", fmt.Sprintf("/orders/%v", config.Id.ValueString()), nil)
	if err != nil {
		resp.Diagnostics.AddError("Error reading order", err.Error())
		return
	}

	var result client.Order
	if err := json.Unmarshal(respBody, &result); err != nil {
		resp.Diagnostics.AddError("Error parsing response", err.Error())
		return
	}

	config.FromClientModel(&result)

	tflog.Trace(ctx, "read order data source")
	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
