// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"encoding/json"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"

	"github.com/n-at-han-k/terraform-provider-polar/internal/client"
)

// OrganizationModel is the Terraform model for organization.
type OrganizationModel struct {
	CreatedAt types.String `tfsdk:"created_at"`
	ModifiedAt types.String `tfsdk:"modified_at"`
	Id types.String `tfsdk:"id"`
	Name types.String `tfsdk:"name"`
	Slug types.String `tfsdk:"slug"`
	AvatarUrl types.String `tfsdk:"avatar_url"`
	ProrationBehavior types.String `tfsdk:"proration_behavior"`
	AllowCustomerUpdates types.Bool `tfsdk:"allow_customer_updates"`
	Email types.String `tfsdk:"email"`
	Website types.String `tfsdk:"website"`
	Socials jsontypes.Normalized `tfsdk:"socials"`
	Status types.String `tfsdk:"status"`
	DetailsSubmittedAt types.String `tfsdk:"details_submitted_at"`
	OnboardingResubmissionRequestedAt types.String `tfsdk:"onboarding_resubmission_requested_at"`
	SsoEnforced types.Bool `tfsdk:"sso_enforced"`
	DefaultPresentmentCurrency types.String `tfsdk:"default_presentment_currency"`
	DefaultTaxBehavior types.String `tfsdk:"default_tax_behavior"`
	FeatureSettings jsontypes.Normalized `tfsdk:"feature_settings"`
	SubscriptionSettings jsontypes.Normalized `tfsdk:"subscription_settings"`
	CustomerEmailSettings jsontypes.Normalized `tfsdk:"customer_email_settings"`
	CustomerPortalSettings jsontypes.Normalized `tfsdk:"customer_portal_settings"`
	DisputeSettings jsontypes.Normalized `tfsdk:"dispute_settings"`
	EmbedHosts jsontypes.Normalized `tfsdk:"embed_hosts"`
	EmbedHostsEnforced types.Bool `tfsdk:"embed_hosts_enforced"`
	Country types.String `tfsdk:"country"`
	AccountId types.String `tfsdk:"account_id"`
	PayoutAccountId types.String `tfsdk:"payout_account_id"`
	Capabilities jsontypes.Normalized `tfsdk:"capabilities"`
	Details jsontypes.Normalized `tfsdk:"details"`
}

// ToClientModel converts a Terraform model to a client model.
func (m *OrganizationModel) ToClientModel() (*client.OrganizationUpdate, error) {
	out := &client.OrganizationUpdate{}
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		out.Name = m.Name.ValueString()
	}
	if !m.AvatarUrl.IsNull() && !m.AvatarUrl.IsUnknown() {
		out.AvatarUrl = m.AvatarUrl.ValueString()
	}
	if !m.Email.IsNull() && !m.Email.IsUnknown() {
		out.Email = m.Email.ValueString()
	}
	if !m.Website.IsNull() && !m.Website.IsUnknown() {
		out.Website = m.Website.ValueString()
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.Socials.IsNull() && !m.Socials.IsUnknown() {
		if err := json.Unmarshal([]byte(m.Socials.ValueString()), &out.Socials); err != nil {
			return out, fmt.Errorf("socials: %w", err)
		}
	}
	if !m.SsoEnforced.IsNull() && !m.SsoEnforced.IsUnknown() {
		// Addressed, not assigned: the client field is a *bool so that an
		// explicit false is sent rather than dropped by `omitempty`.
		SsoEnforced := m.SsoEnforced.ValueBool()
		out.SsoEnforced = &SsoEnforced
	}
	if !m.DefaultPresentmentCurrency.IsNull() && !m.DefaultPresentmentCurrency.IsUnknown() {
		out.DefaultPresentmentCurrency = m.DefaultPresentmentCurrency.ValueString()
	}
	if !m.DefaultTaxBehavior.IsNull() && !m.DefaultTaxBehavior.IsUnknown() {
		out.DefaultTaxBehavior = m.DefaultTaxBehavior.ValueString()
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.FeatureSettings.IsNull() && !m.FeatureSettings.IsUnknown() {
		if err := json.Unmarshal([]byte(m.FeatureSettings.ValueString()), &out.FeatureSettings); err != nil {
			return out, fmt.Errorf("feature_settings: %w", err)
		}
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.SubscriptionSettings.IsNull() && !m.SubscriptionSettings.IsUnknown() {
		if err := json.Unmarshal([]byte(m.SubscriptionSettings.ValueString()), &out.SubscriptionSettings); err != nil {
			return out, fmt.Errorf("subscription_settings: %w", err)
		}
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.CustomerEmailSettings.IsNull() && !m.CustomerEmailSettings.IsUnknown() {
		if err := json.Unmarshal([]byte(m.CustomerEmailSettings.ValueString()), &out.CustomerEmailSettings); err != nil {
			return out, fmt.Errorf("customer_email_settings: %w", err)
		}
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.CustomerPortalSettings.IsNull() && !m.CustomerPortalSettings.IsUnknown() {
		if err := json.Unmarshal([]byte(m.CustomerPortalSettings.ValueString()), &out.CustomerPortalSettings); err != nil {
			return out, fmt.Errorf("customer_portal_settings: %w", err)
		}
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.DisputeSettings.IsNull() && !m.DisputeSettings.IsUnknown() {
		if err := json.Unmarshal([]byte(m.DisputeSettings.ValueString()), &out.DisputeSettings); err != nil {
			return out, fmt.Errorf("dispute_settings: %w", err)
		}
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.EmbedHosts.IsNull() && !m.EmbedHosts.IsUnknown() {
		if err := json.Unmarshal([]byte(m.EmbedHosts.ValueString()), &out.EmbedHosts); err != nil {
			return out, fmt.Errorf("embed_hosts: %w", err)
		}
	}
	if !m.Country.IsNull() && !m.Country.IsUnknown() {
		out.Country = m.Country.ValueString()
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.Details.IsNull() && !m.Details.IsUnknown() {
		if err := json.Unmarshal([]byte(m.Details.ValueString()), &out.Details); err != nil {
			return out, fmt.Errorf("details: %w", err)
		}
	}
	return out, nil
}


// FromClientModel updates the Terraform model from a client model.
func (m *OrganizationModel) FromClientModel(c *client.Organization) {
	m.CreatedAt = types.StringValue(c.CreatedAt)
	m.ModifiedAt = types.StringValue(c.ModifiedAt)
	m.Id = types.StringValue(string(c.Id))
	m.Name = types.StringValue(c.Name)
	m.Slug = types.StringValue(c.Slug)
	m.AvatarUrl = types.StringValue(c.AvatarUrl)
	m.ProrationBehavior = types.StringValue(c.ProrationBehavior)
	// A bool the server does not answer leaves the pointer nil, and a Computed
	// attribute is UNKNOWN in the plan -- "provider still indicated an unknown
	// value ... all values must be known after apply". Unknown becomes null; a
	// value the plan already knows is left alone.
	if c.AllowCustomerUpdates != nil {
		m.AllowCustomerUpdates = types.BoolValue(*c.AllowCustomerUpdates)
	} else if m.AllowCustomerUpdates.IsUnknown() {
		m.AllowCustomerUpdates = types.BoolNull()
	}
	m.Email = types.StringValue(c.Email)
	m.Website = types.StringValue(c.Website)
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.Socials); err == nil {
		if m.Socials.IsNull() || m.Socials.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.Socials.ValueString()) {
			m.Socials = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	m.Status = types.StringValue(c.Status)
	m.DetailsSubmittedAt = types.StringValue(c.DetailsSubmittedAt)
	m.OnboardingResubmissionRequestedAt = types.StringValue(c.OnboardingResubmissionRequestedAt)
	// A bool the server does not answer leaves the pointer nil, and a Computed
	// attribute is UNKNOWN in the plan -- "provider still indicated an unknown
	// value ... all values must be known after apply". Unknown becomes null; a
	// value the plan already knows is left alone.
	if c.SsoEnforced != nil {
		m.SsoEnforced = types.BoolValue(*c.SsoEnforced)
	} else if m.SsoEnforced.IsUnknown() {
		m.SsoEnforced = types.BoolNull()
	}
	m.DefaultPresentmentCurrency = types.StringValue(c.DefaultPresentmentCurrency)
	m.DefaultTaxBehavior = types.StringValue(c.DefaultTaxBehavior)
	// The create body takes this and no response of the same shape answers it --
	// AssociationRequest against AssociationResponse -- so nothing above writes
	// it, and a Computed attribute the configuration left out stays UNKNOWN once
	// the apply is over: "provider returned invalid result object after apply".
	// Unknown becomes null; a value the plan already knows is left alone.
	if m.FeatureSettings.IsUnknown() {
		m.FeatureSettings = jsontypes.NewNormalizedNull()
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.SubscriptionSettings); err == nil {
		if m.SubscriptionSettings.IsNull() || m.SubscriptionSettings.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.SubscriptionSettings.ValueString()) {
			m.SubscriptionSettings = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.CustomerEmailSettings); err == nil {
		if m.CustomerEmailSettings.IsNull() || m.CustomerEmailSettings.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.CustomerEmailSettings.ValueString()) {
			m.CustomerEmailSettings = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.CustomerPortalSettings); err == nil {
		if m.CustomerPortalSettings.IsNull() || m.CustomerPortalSettings.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.CustomerPortalSettings.ValueString()) {
			m.CustomerPortalSettings = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	// The create body takes this and no response of the same shape answers it --
	// AssociationRequest against AssociationResponse -- so nothing above writes
	// it, and a Computed attribute the configuration left out stays UNKNOWN once
	// the apply is over: "provider returned invalid result object after apply".
	// Unknown becomes null; a value the plan already knows is left alone.
	if m.DisputeSettings.IsUnknown() {
		m.DisputeSettings = jsontypes.NewNormalizedNull()
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.EmbedHosts); err == nil {
		if m.EmbedHosts.IsNull() || m.EmbedHosts.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.EmbedHosts.ValueString()) {
			m.EmbedHosts = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	// A bool the server does not answer leaves the pointer nil, and a Computed
	// attribute is UNKNOWN in the plan -- "provider still indicated an unknown
	// value ... all values must be known after apply". Unknown becomes null; a
	// value the plan already knows is left alone.
	if c.EmbedHostsEnforced != nil {
		m.EmbedHostsEnforced = types.BoolValue(*c.EmbedHostsEnforced)
	} else if m.EmbedHostsEnforced.IsUnknown() {
		m.EmbedHostsEnforced = types.BoolNull()
	}
	m.Country = types.StringValue(c.Country)
	m.AccountId = types.StringValue(c.AccountId)
	m.PayoutAccountId = types.StringValue(c.PayoutAccountId)
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.Capabilities); err == nil {
		if m.Capabilities.IsNull() || m.Capabilities.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.Capabilities.ValueString()) {
			m.Capabilities = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
}
