// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"encoding/json"



	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"

	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-log/tflog"



	"github.com/n-at-han-k/terraform-provider-polar/internal/client"
)

var _ resource.Resource = &OrganizationResource{}
var _ resource.ResourceWithImportState = &OrganizationResource{}

func NewOrganizationResource() resource.Resource {
	return &OrganizationResource{}
}

type OrganizationResource struct {
	client *client.Client
}

func (r *OrganizationResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_organization"
}

func (r *OrganizationResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a organization resource.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:    true,
				Description: "The ID of the object.",
			},
			"created_at": schema.StringAttribute{
				Computed:    true,
				Description: "Creation timestamp of the object.",
			},
			"modified_at": schema.StringAttribute{
				Computed:    true,
				Description: "Last modification timestamp of the object.",
			},
			"name": schema.StringAttribute{
				Required:    true,
				Description: "Organization name shown in checkout, customer portal, emails etc.",
			},
			"slug": schema.StringAttribute{
				Required:    true,
				Description: "Unique organization slug in checkout, customer portal and credit card statements.",
			},
			"avatar_url": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: "Avatar URL shown in checkout, customer portal, emails etc.",
			},
			"legal_entity": schema.SingleNestedAttribute{
				Optional:    true,
				Attributes: map[string]schema.Attribute{
					"registered_name": schema.StringAttribute{
						Computed:    true,
						Optional:    true,
						Description: "",
					},
					"type": schema.StringAttribute{
						Required:    true,
						Description: "Which variant this is. Selects which of the optional blocks above applies.",
					},
				},
				Description: "",
			},
			"email": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: "Public support email.",
			},
			"website": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: "Official website of the organization.",
			},
			"socials": schema.ListNestedAttribute{
				Computed:    true,
				Optional:    true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"platform": schema.StringAttribute{
							Required:    true,
							Description: "The social platform of the URL",
						},
						"url": schema.StringAttribute{
							Required:    true,
							Description: "The URL to the organization profile",
						},
					},
				},
				Description: "Links to social profiles.",
			},
			"details": schema.SingleNestedAttribute{
				Optional:    true,
				Attributes: map[string]schema.Attribute{
					"about": schema.StringAttribute{
						Computed:    true,
						Optional:    true,
						Description: "Brief information about you and your business.",
					},
					"product_description": schema.StringAttribute{
						Computed:    true,
						Optional:    true,
						Description: "Description of digital products being sold.",
					},
					"selling_categories": schema.StringAttribute{
						CustomType:  jsontypes.NormalizedType{},
						Computed:    true,
						Optional:    true,
						Description: "Categories of products being sold.",
					},
					"pricing_models": schema.StringAttribute{
						CustomType:  jsontypes.NormalizedType{},
						Computed:    true,
						Optional:    true,
						Description: "Pricing models used by the organization.",
					},
					"intended_use": schema.StringAttribute{
						Computed:    true,
						Optional:    true,
						Description: "How the organization will integrate and use Polar.",
					},
					"customer_acquisition": schema.StringAttribute{
						CustomType:  jsontypes.NormalizedType{},
						Computed:    true,
						Optional:    true,
						Description: "Main customer acquisition channels.",
					},
					"future_annual_revenue": schema.Int64Attribute{
						Computed:    true,
						Optional:    true,
						Description: "Estimated revenue in the next 12 months",
					},
					"switching": schema.BoolAttribute{
						Computed:    true,
						Optional:    true,
						Description: "Switching from another platform?",
					},
					"switching_from": schema.StringAttribute{
						Computed:    true,
						Optional:    true,
						Description: "Which platform the organization is migrating from.",
					},
					"previous_annual_revenue": schema.Int64Attribute{
						Computed:    true,
						Optional:    true,
						Description: "Revenue from last year if applicable.",
					},
				},
				Description: "Additional, private, business details Polar needs about active organizations for compliance (KYC).",
			},
			"country": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: "Two-letter country code (ISO 3166-1 alpha-2).",
			},
			"feature_settings": schema.SingleNestedAttribute{
				Optional:    true,
				Attributes: map[string]schema.Attribute{
					"seat_based_pricing_enabled": schema.BoolAttribute{
						Computed:    true,
						Optional:    true,
						Description: "If this organization has seat-based pricing enabled",
					},
					"member_model_enabled": schema.BoolAttribute{
						Computed:    true,
						Optional:    true,
						Description: "If this organization has the Member model enabled",
					},
					"checkout_localization_enabled": schema.BoolAttribute{
						Computed:    true,
						Optional:    true,
						Description: "If this organization has checkout localization enabled",
					},
					"overview_metrics": schema.StringAttribute{
						CustomType:  jsontypes.NormalizedType{},
						Computed:    true,
						Optional:    true,
						Description: "Ordered list of metric slugs shown on the dashboard overview.",
					},
				},
				Description: "Organization feature settings",
			},
			"subscription_settings": schema.SingleNestedAttribute{
				Computed:    true,
				Optional:    true,
				Attributes: map[string]schema.Attribute{
					"allow_multiple_subscriptions": schema.BoolAttribute{
						Required:    true,
						Description: "",
					},
					"proration_behavior": schema.StringAttribute{
						Required:    true,
						Description: "",
					},
					"benefit_revocation_grace_period": schema.Int64Attribute{
						Required:    true,
						Description: "",
					},
					"prevent_trial_abuse": schema.BoolAttribute{
						Required:    true,
						Description: "",
					},
					"allow_customer_updates": schema.BoolAttribute{
						Required:    true,
						Description: "",
					},
				},
				Description: "Settings related to subscriptions management",
			},
			"customer_email_settings": schema.SingleNestedAttribute{
				Computed:    true,
				Optional:    true,
				Attributes: map[string]schema.Attribute{
					"order_confirmation": schema.BoolAttribute{
						Required:    true,
						Description: "",
					},
					"payment_method_expiration_reminder": schema.BoolAttribute{
						Required:    true,
						Description: "",
					},
					"subscription_cancellation": schema.BoolAttribute{
						Required:    true,
						Description: "",
					},
					"subscription_confirmation": schema.BoolAttribute{
						Required:    true,
						Description: "",
					},
					"subscription_cycled": schema.BoolAttribute{
						Required:    true,
						Description: "",
					},
					"subscription_cycled_after_trial": schema.BoolAttribute{
						Required:    true,
						Description: "",
					},
					"subscription_past_due": schema.BoolAttribute{
						Required:    true,
						Description: "",
					},
					"subscription_paused": schema.BoolAttribute{
						Required:    true,
						Description: "",
					},
					"subscription_resumed": schema.BoolAttribute{
						Required:    true,
						Description: "",
					},
					"subscription_renewal_reminder": schema.BoolAttribute{
						Required:    true,
						Description: "",
					},
					"subscription_revoked": schema.BoolAttribute{
						Required:    true,
						Description: "",
					},
					"subscription_trial_conversion_reminder": schema.BoolAttribute{
						Required:    true,
						Description: "",
					},
					"subscription_uncanceled": schema.BoolAttribute{
						Required:    true,
						Description: "",
					},
					"subscription_updated": schema.BoolAttribute{
						Required:    true,
						Description: "",
					},
				},
				Description: "Settings related to customer emails",
			},
			"customer_portal_settings": schema.SingleNestedAttribute{
				Computed:    true,
				Optional:    true,
				Attributes: map[string]schema.Attribute{
					"usage": schema.StringAttribute{
						Required:    true,
						Description: "",
					},
					"subscription": schema.StringAttribute{
						Required:    true,
						Description: "",
					},
					"customer": schema.StringAttribute{
						Computed:    true,
						Optional:    true,
						Description: "",
					},
				},
				Description: "Settings related to the customer portal",
			},
			"default_presentment_currency": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: "Default presentment currency. Used as fallback in checkout and customer portal, if the customer's local currency is not available.",
			},
			"default_tax_behavior": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: "Default tax behavior applied on products.",
			},
		},
	}
}

func (r *OrganizationResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}

	r.client = c
}

func (r *OrganizationResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan OrganizationModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	reqBody, err := plan.ToClientModel()
	if err != nil {
		resp.Diagnostics.AddError("Invalid organization configuration", err.Error())
		return
	}

	respBody, location, err := r.client.DoCreateRequest(ctx, "POST", "/organizations/", reqBody)
	if err != nil {
		resp.Diagnostics.AddError("Error creating organization", err.Error())
		return
	}

	// A create may answer a 201 whose body is an identifier and a link, not
	// the resource -- and sometimes only a Location header. Either way what
	// was created has to be READ BACK, not taken from the create's own
	// answer: taking it wrote empty strings over the values just sent,
	// "provider produced inconsistent result after apply".
	if created := client.IDFromCreate(respBody, location); created != "" {
		plan.Id = types.StringValue(created)
	}

	respBody, err = r.client.DoRequest(ctx, "GET", fmt.Sprintf("/organizations/%v", plan.Id.ValueString()), nil)
	if err != nil {
		resp.Diagnostics.AddError("Error reading back the created organization", err.Error())
		return
	}

	if len(respBody) > 0 {
		var result client.Organization
		if err := json.Unmarshal(respBody, &result); err != nil {
			resp.Diagnostics.AddError("Error parsing response", err.Error())
			return
		}

		plan.FromClientModel(&result)
	}

	tflog.Trace(ctx, "created organization resource")
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *OrganizationResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state OrganizationModel

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// A resource with no identifier is not a resource. Without this the read
	// interpolates an empty id and asks the COLLECTION endpoint, which answers
	// 200 and a list -- so a state written before the id was known would look
	// healthy forever instead of being adopted again.
	if state.Id.ValueString() == "" {
		resp.State.RemoveResource(ctx)
		return
	}

	respBody, err := r.client.DoRequest(ctx, "GET", fmt.Sprintf("/organizations/%v", state.Id.ValueString()), nil)
	if err != nil {
		// GONE IS NOT BROKEN. A 404 here means the resource this state row
		// describes no longer exists -- deleted by hand, or by something else
		// that owns it -- and the honest answer is to drop the row and let the
		// plan decide whether to recreate it. Raising instead fails every plan
		// in the configuration, including the ones with nothing to do with this
		// resource, and leaves no way out but editing state by hand.
		//
		// ONLY IN Read. The same 404 after a create or an update is a real
		// failure: something we just wrote is missing.
		var apiErr *client.APIError
		if errors.As(err, &apiErr) && apiErr.StatusCode == http.StatusNotFound {
			resp.State.RemoveResource(ctx)
			return
		}

		resp.Diagnostics.AddError("Error reading organization", err.Error())
		return
	}

	var result client.Organization
	if err := json.Unmarshal(respBody, &result); err != nil {
		resp.Diagnostics.AddError("Error parsing response", err.Error())
		return
	}

	state.FromClientModel(&result)

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *OrganizationResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan OrganizationModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// The identifiers come off state: they cannot change on an update, and the
	// plan's copy of a Computed one is unknown -- which is also the only place
	// an imported nested resource's parents live.
	var state OrganizationModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// The UPDATE model, not the create one -- see ToUpdateModel.
	reqBody, err := plan.ToUpdateModel()
	if err != nil {
		resp.Diagnostics.AddError("Invalid organization configuration", err.Error())
		return
	}

	respBody, err := r.client.DoRequest(ctx, "PATCH", fmt.Sprintf("/organizations/%v", state.Id.ValueString()), reqBody)
	if err != nil {
		resp.Diagnostics.AddError("Error updating organization", err.Error())
		return
	}

	// AN UPDATE'S ANSWER IS NOT ALWAYS THE READ'S. An API may answer a PUT with the list of
	// changes it made -- ["Description changed from 'a' to 'b'"] -- and some
	// updates answer nothing at all; neither is the resource, and
	// unmarshalling either one is "Error parsing response" AFTER the server
	// has already accepted the change. What it now looks like is read back.
	respBody, err = r.client.DoRequest(ctx, "GET", fmt.Sprintf("/organizations/%v", state.Id.ValueString()), nil)
	if err != nil {
		resp.Diagnostics.AddError("Error reading back the updated organization", err.Error())
		return
	}

	if len(respBody) > 0 {
		var result client.Organization
		if err := json.Unmarshal(respBody, &result); err != nil {
			resp.Diagnostics.AddError("Error parsing response", err.Error())
			return
		}

		plan.FromClientModel(&result)
	}

	tflog.Trace(ctx, "updated organization resource")
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *OrganizationResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	// No delete endpoint available; remove the resource from state.
}

func (r *OrganizationResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
