// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/n-at-han-k/terraform-provider-polar/internal/client"
)

// OrganizationModel is the Terraform model for organization.
type OrganizationModel struct {
	Id                         types.String                             `tfsdk:"id"`
	Name                       types.String                             `tfsdk:"name"`
	Slug                       types.String                             `tfsdk:"slug"`
	AvatarUrl                  types.String                             `tfsdk:"avatar_url"`
	LegalEntity                *OrganizationLegalEntityModel            `tfsdk:"legal_entity"`
	Email                      types.String                             `tfsdk:"email"`
	Website                    types.String                             `tfsdk:"website"`
	Socials                    []OrganizationSocialsModel               `tfsdk:"socials"`
	Details                    *OrganizationDetailsModel                `tfsdk:"details"`
	Country                    types.String                             `tfsdk:"country"`
	FeatureSettings            *OrganizationFeatureSettingsModel        `tfsdk:"feature_settings"`
	SubscriptionSettings       *OrganizationSubscriptionSettingsModel   `tfsdk:"subscription_settings"`
	CustomerEmailSettings      *OrganizationCustomerEmailSettingsModel  `tfsdk:"customer_email_settings"`
	CustomerPortalSettings     *OrganizationCustomerPortalSettingsModel `tfsdk:"customer_portal_settings"`
	DefaultPresentmentCurrency types.String                             `tfsdk:"default_presentment_currency"`
	DefaultTaxBehavior         types.String                             `tfsdk:"default_tax_behavior"`
}

// OrganizationLegalEntityModel is one `legal_entity` block.
//
// A STRUCT WITH tfsdk TAGS, not a types.Object: terraform-plugin-framework
// reflects over these, so a slice of them is a ListNestedAttribute and a
// pointer to one is a SingleNestedAttribute, with no AttributeTypes map to keep
// in step with the fields by hand.
type OrganizationLegalEntityModel struct {
	RegisteredName types.String `tfsdk:"registered_name"`
	Type           types.String `tfsdk:"type"`
}

// ToClientModel converts one block to the client type the request carries.
func (m *OrganizationLegalEntityModel) ToClientModel() (*client.OrganizationCreateLegalEntity, error) {
	out := &client.OrganizationCreateLegalEntity{}
	if !m.RegisteredName.IsNull() && !m.RegisteredName.IsUnknown() {
		RegisteredName := m.RegisteredName.ValueString()
		out.RegisteredName = &RegisteredName
	}
	if !m.Type.IsNull() && !m.Type.IsUnknown() {
		Type := m.Type.ValueString()
		out.Type = &Type
	}
	return out, nil
}

// FromClientModel fills one block from what the server answered.
//
// EVERY CHILD IS WRITTEN, not only the ones the configuration set, because they
// are Optional AND Computed: Polar fills in a price's currency and tax
// behaviour, and a Computed attribute left unknown after an apply is "provider
// returned invalid result object after apply".
func (m *OrganizationLegalEntityModel) FromClientModel(c *client.OrganizationCreateLegalEntity) {
}

// OrganizationSocialsModel is one `socials` block.
//
// A STRUCT WITH tfsdk TAGS, not a types.Object: terraform-plugin-framework
// reflects over these, so a slice of them is a ListNestedAttribute and a
// pointer to one is a SingleNestedAttribute, with no AttributeTypes map to keep
// in step with the fields by hand.
type OrganizationSocialsModel struct {
	Platform types.String `tfsdk:"platform"`
	Url      types.String `tfsdk:"url"`
}

// ToClientModel converts one block to the client type the request carries.
func (m *OrganizationSocialsModel) ToClientModel() (*client.OrganizationSocialLink, error) {
	out := &client.OrganizationSocialLink{}
	if !m.Platform.IsNull() && !m.Platform.IsUnknown() {
		out.Platform = m.Platform.ValueString()
	}
	if !m.Url.IsNull() && !m.Url.IsUnknown() {
		Url := m.Url.ValueString()
		out.Url = &Url
	}
	return out, nil
}

// FromClientModel fills one block from what the server answered.
//
// EVERY CHILD IS WRITTEN, not only the ones the configuration set, because they
// are Optional AND Computed: Polar fills in a price's currency and tax
// behaviour, and a Computed attribute left unknown after an apply is "provider
// returned invalid result object after apply".
func (m *OrganizationSocialsModel) FromClientModel(c *client.OrganizationSocialLink) {
}

// OrganizationDetailsModel is one `details` block.
//
// A STRUCT WITH tfsdk TAGS, not a types.Object: terraform-plugin-framework
// reflects over these, so a slice of them is a ListNestedAttribute and a
// pointer to one is a SingleNestedAttribute, with no AttributeTypes map to keep
// in step with the fields by hand.
type OrganizationDetailsModel struct {
	About                 types.String `tfsdk:"about"`
	ProductDescription    types.String `tfsdk:"product_description"`
	SellingCategories     types.List   `tfsdk:"selling_categories"`
	PricingModels         types.List   `tfsdk:"pricing_models"`
	IntendedUse           types.String `tfsdk:"intended_use"`
	CustomerAcquisition   types.List   `tfsdk:"customer_acquisition"`
	FutureAnnualRevenue   types.Int64  `tfsdk:"future_annual_revenue"`
	Switching             types.Bool   `tfsdk:"switching"`
	SwitchingFrom         types.String `tfsdk:"switching_from"`
	PreviousAnnualRevenue types.Int64  `tfsdk:"previous_annual_revenue"`
}

// ToClientModel converts one block to the client type the request carries.
func (m *OrganizationDetailsModel) ToClientModel() (*client.OrganizationDetails, error) {
	out := &client.OrganizationDetails{}
	if !m.About.IsNull() && !m.About.IsUnknown() {
		About := m.About.ValueString()
		out.About = &About
	}
	if !m.ProductDescription.IsNull() && !m.ProductDescription.IsUnknown() {
		ProductDescription := m.ProductDescription.ValueString()
		out.ProductDescription = &ProductDescription
	}
	if !m.IntendedUse.IsNull() && !m.IntendedUse.IsUnknown() {
		IntendedUse := m.IntendedUse.ValueString()
		out.IntendedUse = &IntendedUse
	}
	if !m.FutureAnnualRevenue.IsNull() && !m.FutureAnnualRevenue.IsUnknown() {
		FutureAnnualRevenue := int32(m.FutureAnnualRevenue.ValueInt64())
		out.FutureAnnualRevenue = &FutureAnnualRevenue
	}
	if !m.Switching.IsNull() && !m.Switching.IsUnknown() {
		Switching := m.Switching.ValueBool()
		out.Switching = &Switching
	}
	if !m.SwitchingFrom.IsNull() && !m.SwitchingFrom.IsUnknown() {
		SwitchingFrom := m.SwitchingFrom.ValueString()
		out.SwitchingFrom = &SwitchingFrom
	}
	if !m.PreviousAnnualRevenue.IsNull() && !m.PreviousAnnualRevenue.IsUnknown() {
		PreviousAnnualRevenue := int32(m.PreviousAnnualRevenue.ValueInt64())
		out.PreviousAnnualRevenue = &PreviousAnnualRevenue
	}
	return out, nil
}

// FromClientModel fills one block from what the server answered.
//
// EVERY CHILD IS WRITTEN, not only the ones the configuration set, because they
// are Optional AND Computed: Polar fills in a price's currency and tax
// behaviour, and a Computed attribute left unknown after an apply is "provider
// returned invalid result object after apply".
func (m *OrganizationDetailsModel) FromClientModel(c *client.OrganizationDetails) {
}

// OrganizationFeatureSettingsModel is one `feature_settings` block.
//
// A STRUCT WITH tfsdk TAGS, not a types.Object: terraform-plugin-framework
// reflects over these, so a slice of them is a ListNestedAttribute and a
// pointer to one is a SingleNestedAttribute, with no AttributeTypes map to keep
// in step with the fields by hand.
type OrganizationFeatureSettingsModel struct {
	IssueFundingEnabled           types.Bool `tfsdk:"issue_funding_enabled"`
	SeatBasedPricingEnabled       types.Bool `tfsdk:"seat_based_pricing_enabled"`
	WalletsEnabled                types.Bool `tfsdk:"wallets_enabled"`
	MemberModelEnabled            types.Bool `tfsdk:"member_model_enabled"`
	CheckoutLocalizationEnabled   types.Bool `tfsdk:"checkout_localization_enabled"`
	OverviewMetrics               types.List `tfsdk:"overview_metrics"`
	ResetProrationBehaviorEnabled types.Bool `tfsdk:"reset_proration_behavior_enabled"`
	OffSessionChargesEnabled      types.Bool `tfsdk:"off_session_charges_enabled"`
	SlackBenefitEnabled           types.Bool `tfsdk:"slack_benefit_enabled"`
	PreviewAccessEnabled          types.Bool `tfsdk:"preview_access_enabled"`
	DisputesEnabled               types.Bool `tfsdk:"disputes_enabled"`
	SsoEnabled                    types.Bool `tfsdk:"sso_enabled"`
	DisputeAutoAcceptEnabled      types.Bool `tfsdk:"dispute_auto_accept_enabled"`
	CompassEnabled                types.Bool `tfsdk:"compass_enabled"`
	MerchantMigrationEnabled      types.Bool `tfsdk:"merchant_migration_enabled"`
}

// ToClientModel converts one block to the client type the request carries.
func (m *OrganizationFeatureSettingsModel) ToClientModel() (*client.OrganizationFeatureSettingsUpdate, error) {
	out := &client.OrganizationFeatureSettingsUpdate{}
	if !m.SeatBasedPricingEnabled.IsNull() && !m.SeatBasedPricingEnabled.IsUnknown() {
		SeatBasedPricingEnabled := m.SeatBasedPricingEnabled.ValueBool()
		out.SeatBasedPricingEnabled = &SeatBasedPricingEnabled
	}
	if !m.MemberModelEnabled.IsNull() && !m.MemberModelEnabled.IsUnknown() {
		MemberModelEnabled := m.MemberModelEnabled.ValueBool()
		out.MemberModelEnabled = &MemberModelEnabled
	}
	if !m.CheckoutLocalizationEnabled.IsNull() && !m.CheckoutLocalizationEnabled.IsUnknown() {
		CheckoutLocalizationEnabled := m.CheckoutLocalizationEnabled.ValueBool()
		out.CheckoutLocalizationEnabled = &CheckoutLocalizationEnabled
	}
	return out, nil
}

// FromClientModel fills one block from what the server answered.
//
// A DIFFERENT CLIENT TYPE FROM THE ONE IT SENDS: this block's children describe
// what Polar answers, and the request carries its own -- see `responseBlocks` in
// the generator configuration. The struct is the same either way, so the two
// conversions have the same fields to work with and do not.
func (m *OrganizationFeatureSettingsModel) FromClientModel(c *client.OrganizationFeatureSettings) {
}

// OrganizationSubscriptionSettingsModel is one `subscription_settings` block.
//
// A STRUCT WITH tfsdk TAGS, not a types.Object: terraform-plugin-framework
// reflects over these, so a slice of them is a ListNestedAttribute and a
// pointer to one is a SingleNestedAttribute, with no AttributeTypes map to keep
// in step with the fields by hand.
type OrganizationSubscriptionSettingsModel struct {
	AllowMultipleSubscriptions   types.Bool   `tfsdk:"allow_multiple_subscriptions"`
	ProrationBehavior            types.String `tfsdk:"proration_behavior"`
	BenefitRevocationGracePeriod types.Int64  `tfsdk:"benefit_revocation_grace_period"`
	PreventTrialAbuse            types.Bool   `tfsdk:"prevent_trial_abuse"`
	AllowCustomerUpdates         types.Bool   `tfsdk:"allow_customer_updates"`
}

// ToClientModel converts one block to the client type the request carries.
func (m *OrganizationSubscriptionSettingsModel) ToClientModel() (*client.OrganizationSubscriptionSettings, error) {
	out := &client.OrganizationSubscriptionSettings{}
	if !m.AllowMultipleSubscriptions.IsNull() && !m.AllowMultipleSubscriptions.IsUnknown() {
		AllowMultipleSubscriptions := m.AllowMultipleSubscriptions.ValueBool()
		out.AllowMultipleSubscriptions = &AllowMultipleSubscriptions
	}
	if !m.ProrationBehavior.IsNull() && !m.ProrationBehavior.IsUnknown() {
		ProrationBehavior := m.ProrationBehavior.ValueString()
		out.ProrationBehavior = &ProrationBehavior
	}
	if !m.BenefitRevocationGracePeriod.IsNull() && !m.BenefitRevocationGracePeriod.IsUnknown() {
		out.BenefitRevocationGracePeriod = int32(m.BenefitRevocationGracePeriod.ValueInt64())
	}
	if !m.PreventTrialAbuse.IsNull() && !m.PreventTrialAbuse.IsUnknown() {
		PreventTrialAbuse := m.PreventTrialAbuse.ValueBool()
		out.PreventTrialAbuse = &PreventTrialAbuse
	}
	if !m.AllowCustomerUpdates.IsNull() && !m.AllowCustomerUpdates.IsUnknown() {
		AllowCustomerUpdates := m.AllowCustomerUpdates.ValueBool()
		out.AllowCustomerUpdates = &AllowCustomerUpdates
	}
	return out, nil
}

// FromClientModel fills one block from what the server answered.
//
// EVERY CHILD IS WRITTEN, not only the ones the configuration set, because they
// are Optional AND Computed: Polar fills in a price's currency and tax
// behaviour, and a Computed attribute left unknown after an apply is "provider
// returned invalid result object after apply".
func (m *OrganizationSubscriptionSettingsModel) FromClientModel(c *client.OrganizationSubscriptionSettings) {
}

// OrganizationCustomerEmailSettingsModel is one `customer_email_settings` block.
//
// A STRUCT WITH tfsdk TAGS, not a types.Object: terraform-plugin-framework
// reflects over these, so a slice of them is a ListNestedAttribute and a
// pointer to one is a SingleNestedAttribute, with no AttributeTypes map to keep
// in step with the fields by hand.
type OrganizationCustomerEmailSettingsModel struct {
	OrderConfirmation                   types.Bool `tfsdk:"order_confirmation"`
	PaymentMethodExpirationReminder     types.Bool `tfsdk:"payment_method_expiration_reminder"`
	SubscriptionCancellation            types.Bool `tfsdk:"subscription_cancellation"`
	SubscriptionConfirmation            types.Bool `tfsdk:"subscription_confirmation"`
	SubscriptionCycled                  types.Bool `tfsdk:"subscription_cycled"`
	SubscriptionCycledAfterTrial        types.Bool `tfsdk:"subscription_cycled_after_trial"`
	SubscriptionPastDue                 types.Bool `tfsdk:"subscription_past_due"`
	SubscriptionPaused                  types.Bool `tfsdk:"subscription_paused"`
	SubscriptionResumed                 types.Bool `tfsdk:"subscription_resumed"`
	SubscriptionRenewalReminder         types.Bool `tfsdk:"subscription_renewal_reminder"`
	SubscriptionRevoked                 types.Bool `tfsdk:"subscription_revoked"`
	SubscriptionTrialConversionReminder types.Bool `tfsdk:"subscription_trial_conversion_reminder"`
	SubscriptionUncanceled              types.Bool `tfsdk:"subscription_uncanceled"`
	SubscriptionUpdated                 types.Bool `tfsdk:"subscription_updated"`
}

// ToClientModel converts one block to the client type the request carries.
func (m *OrganizationCustomerEmailSettingsModel) ToClientModel() (*client.OrganizationCustomerEmailSettings, error) {
	out := &client.OrganizationCustomerEmailSettings{}
	if !m.OrderConfirmation.IsNull() && !m.OrderConfirmation.IsUnknown() {
		OrderConfirmation := m.OrderConfirmation.ValueBool()
		out.OrderConfirmation = &OrderConfirmation
	}
	if !m.PaymentMethodExpirationReminder.IsNull() && !m.PaymentMethodExpirationReminder.IsUnknown() {
		PaymentMethodExpirationReminder := m.PaymentMethodExpirationReminder.ValueBool()
		out.PaymentMethodExpirationReminder = &PaymentMethodExpirationReminder
	}
	if !m.SubscriptionCancellation.IsNull() && !m.SubscriptionCancellation.IsUnknown() {
		SubscriptionCancellation := m.SubscriptionCancellation.ValueBool()
		out.SubscriptionCancellation = &SubscriptionCancellation
	}
	if !m.SubscriptionConfirmation.IsNull() && !m.SubscriptionConfirmation.IsUnknown() {
		SubscriptionConfirmation := m.SubscriptionConfirmation.ValueBool()
		out.SubscriptionConfirmation = &SubscriptionConfirmation
	}
	if !m.SubscriptionCycled.IsNull() && !m.SubscriptionCycled.IsUnknown() {
		SubscriptionCycled := m.SubscriptionCycled.ValueBool()
		out.SubscriptionCycled = &SubscriptionCycled
	}
	if !m.SubscriptionCycledAfterTrial.IsNull() && !m.SubscriptionCycledAfterTrial.IsUnknown() {
		SubscriptionCycledAfterTrial := m.SubscriptionCycledAfterTrial.ValueBool()
		out.SubscriptionCycledAfterTrial = &SubscriptionCycledAfterTrial
	}
	if !m.SubscriptionPastDue.IsNull() && !m.SubscriptionPastDue.IsUnknown() {
		SubscriptionPastDue := m.SubscriptionPastDue.ValueBool()
		out.SubscriptionPastDue = &SubscriptionPastDue
	}
	if !m.SubscriptionPaused.IsNull() && !m.SubscriptionPaused.IsUnknown() {
		SubscriptionPaused := m.SubscriptionPaused.ValueBool()
		out.SubscriptionPaused = &SubscriptionPaused
	}
	if !m.SubscriptionResumed.IsNull() && !m.SubscriptionResumed.IsUnknown() {
		SubscriptionResumed := m.SubscriptionResumed.ValueBool()
		out.SubscriptionResumed = &SubscriptionResumed
	}
	if !m.SubscriptionRenewalReminder.IsNull() && !m.SubscriptionRenewalReminder.IsUnknown() {
		SubscriptionRenewalReminder := m.SubscriptionRenewalReminder.ValueBool()
		out.SubscriptionRenewalReminder = &SubscriptionRenewalReminder
	}
	if !m.SubscriptionRevoked.IsNull() && !m.SubscriptionRevoked.IsUnknown() {
		SubscriptionRevoked := m.SubscriptionRevoked.ValueBool()
		out.SubscriptionRevoked = &SubscriptionRevoked
	}
	if !m.SubscriptionTrialConversionReminder.IsNull() && !m.SubscriptionTrialConversionReminder.IsUnknown() {
		SubscriptionTrialConversionReminder := m.SubscriptionTrialConversionReminder.ValueBool()
		out.SubscriptionTrialConversionReminder = &SubscriptionTrialConversionReminder
	}
	if !m.SubscriptionUncanceled.IsNull() && !m.SubscriptionUncanceled.IsUnknown() {
		SubscriptionUncanceled := m.SubscriptionUncanceled.ValueBool()
		out.SubscriptionUncanceled = &SubscriptionUncanceled
	}
	if !m.SubscriptionUpdated.IsNull() && !m.SubscriptionUpdated.IsUnknown() {
		SubscriptionUpdated := m.SubscriptionUpdated.ValueBool()
		out.SubscriptionUpdated = &SubscriptionUpdated
	}
	return out, nil
}

// FromClientModel fills one block from what the server answered.
//
// EVERY CHILD IS WRITTEN, not only the ones the configuration set, because they
// are Optional AND Computed: Polar fills in a price's currency and tax
// behaviour, and a Computed attribute left unknown after an apply is "provider
// returned invalid result object after apply".
func (m *OrganizationCustomerEmailSettingsModel) FromClientModel(c *client.OrganizationCustomerEmailSettings) {
}

// OrganizationCustomerPortalSettingsModel is one `customer_portal_settings` block.
//
// A STRUCT WITH tfsdk TAGS, not a types.Object: terraform-plugin-framework
// reflects over these, so a slice of them is a ListNestedAttribute and a
// pointer to one is a SingleNestedAttribute, with no AttributeTypes map to keep
// in step with the fields by hand.
type OrganizationCustomerPortalSettingsModel struct {
	Usage        *OrganizationCustomerPortalSettingsModelUsageModel        `tfsdk:"usage"`
	Subscription *OrganizationCustomerPortalSettingsModelSubscriptionModel `tfsdk:"subscription"`
	Customer     *OrganizationCustomerPortalSettingsModelCustomerModel     `tfsdk:"customer"`
}

// ToClientModel converts one block to the client type the request carries.
func (m *OrganizationCustomerPortalSettingsModel) ToClientModel() (*client.OrganizationCustomerPortalSettings, error) {
	out := &client.OrganizationCustomerPortalSettings{}
	return out, nil
}

// FromClientModel fills one block from what the server answered.
//
// EVERY CHILD IS WRITTEN, not only the ones the configuration set, because they
// are Optional AND Computed: Polar fills in a price's currency and tax
// behaviour, and a Computed attribute left unknown after an apply is "provider
// returned invalid result object after apply".
func (m *OrganizationCustomerPortalSettingsModel) FromClientModel(c *client.OrganizationCustomerPortalSettings) {
}

// OrganizationCustomerPortalSettingsModelUsageModel is one `usage` block.
//
// A STRUCT WITH tfsdk TAGS, not a types.Object: terraform-plugin-framework
// reflects over these, so a slice of them is a ListNestedAttribute and a
// pointer to one is a SingleNestedAttribute, with no AttributeTypes map to keep
// in step with the fields by hand.
type OrganizationCustomerPortalSettingsModelUsageModel struct {
	Show types.Bool `tfsdk:"show"`
}

// ToClientModel converts one block to the client type the request carries.
func (m *OrganizationCustomerPortalSettingsModelUsageModel) ToClientModel() (*client.CustomerPortalUsageSettings, error) {
	out := &client.CustomerPortalUsageSettings{}
	if !m.Show.IsNull() && !m.Show.IsUnknown() {
		Show := m.Show.ValueBool()
		out.Show = &Show
	}
	return out, nil
}

// FromClientModel fills one block from what the server answered.
//
// EVERY CHILD IS WRITTEN, not only the ones the configuration set, because they
// are Optional AND Computed: Polar fills in a price's currency and tax
// behaviour, and a Computed attribute left unknown after an apply is "provider
// returned invalid result object after apply".
func (m *OrganizationCustomerPortalSettingsModelUsageModel) FromClientModel(c *client.CustomerPortalUsageSettings) {
}

// OrganizationCustomerPortalSettingsModelSubscriptionModel is one `subscription` block.
//
// A STRUCT WITH tfsdk TAGS, not a types.Object: terraform-plugin-framework
// reflects over these, so a slice of them is a ListNestedAttribute and a
// pointer to one is a SingleNestedAttribute, with no AttributeTypes map to keep
// in step with the fields by hand.
type OrganizationCustomerPortalSettingsModelSubscriptionModel struct {
	UpdateSeats types.Bool `tfsdk:"update_seats"`
	UpdatePlan  types.Bool `tfsdk:"update_plan"`
	Pause       types.Bool `tfsdk:"pause"`
}

// ToClientModel converts one block to the client type the request carries.
func (m *OrganizationCustomerPortalSettingsModelSubscriptionModel) ToClientModel() (*client.CustomerPortalSubscriptionSettings, error) {
	out := &client.CustomerPortalSubscriptionSettings{}
	if !m.UpdateSeats.IsNull() && !m.UpdateSeats.IsUnknown() {
		UpdateSeats := m.UpdateSeats.ValueBool()
		out.UpdateSeats = &UpdateSeats
	}
	if !m.UpdatePlan.IsNull() && !m.UpdatePlan.IsUnknown() {
		UpdatePlan := m.UpdatePlan.ValueBool()
		out.UpdatePlan = &UpdatePlan
	}
	if !m.Pause.IsNull() && !m.Pause.IsUnknown() {
		Pause := m.Pause.ValueBool()
		out.Pause = &Pause
	}
	return out, nil
}

// FromClientModel fills one block from what the server answered.
//
// EVERY CHILD IS WRITTEN, not only the ones the configuration set, because they
// are Optional AND Computed: Polar fills in a price's currency and tax
// behaviour, and a Computed attribute left unknown after an apply is "provider
// returned invalid result object after apply".
func (m *OrganizationCustomerPortalSettingsModelSubscriptionModel) FromClientModel(c *client.CustomerPortalSubscriptionSettings) {
}

// OrganizationCustomerPortalSettingsModelCustomerModel is one `customer` block.
//
// A STRUCT WITH tfsdk TAGS, not a types.Object: terraform-plugin-framework
// reflects over these, so a slice of them is a ListNestedAttribute and a
// pointer to one is a SingleNestedAttribute, with no AttributeTypes map to keep
// in step with the fields by hand.
type OrganizationCustomerPortalSettingsModelCustomerModel struct {
	AllowEmailChange types.Bool `tfsdk:"allow_email_change"`
}

// ToClientModel converts one block to the client type the request carries.
func (m *OrganizationCustomerPortalSettingsModelCustomerModel) ToClientModel() (*client.CustomerPortalCustomerSettings, error) {
	out := &client.CustomerPortalCustomerSettings{}
	if !m.AllowEmailChange.IsNull() && !m.AllowEmailChange.IsUnknown() {
		AllowEmailChange := m.AllowEmailChange.ValueBool()
		out.AllowEmailChange = &AllowEmailChange
	}
	return out, nil
}

// FromClientModel fills one block from what the server answered.
//
// EVERY CHILD IS WRITTEN, not only the ones the configuration set, because they
// are Optional AND Computed: Polar fills in a price's currency and tax
// behaviour, and a Computed attribute left unknown after an apply is "provider
// returned invalid result object after apply".
func (m *OrganizationCustomerPortalSettingsModelCustomerModel) FromClientModel(c *client.CustomerPortalCustomerSettings) {
}

// ToClientModel converts a Terraform model to a client model.
func (m *OrganizationModel) ToClientModel() (*client.OrganizationCreate, error) {
	out := &client.OrganizationCreate{}
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		Name := m.Name.ValueString()
		out.Name = &Name
	}
	if !m.Slug.IsNull() && !m.Slug.IsUnknown() {
		Slug := m.Slug.ValueString()
		out.Slug = &Slug
	}
	if !m.AvatarUrl.IsNull() && !m.AvatarUrl.IsUnknown() {
		AvatarUrl := m.AvatarUrl.ValueString()
		out.AvatarUrl = &AvatarUrl
	}
	if m.LegalEntity != nil {
		converted, err := m.LegalEntity.ToClientModel()
		if err != nil {
			return out, fmt.Errorf("legal_entity: %w", err)
		}
		out.LegalEntity = converted
	}
	if !m.Email.IsNull() && !m.Email.IsUnknown() {
		Email := m.Email.ValueString()
		out.Email = &Email
	}
	if !m.Website.IsNull() && !m.Website.IsUnknown() {
		Website := m.Website.ValueString()
		out.Website = &Website
	}
	if len(m.Socials) > 0 {
		out.Socials = make([]client.OrganizationSocialLink, 0, len(m.Socials))
		for index := range m.Socials {
			converted, err := m.Socials[index].ToClientModel()
			if err != nil {
				return out, fmt.Errorf("socials[%d]: %w", index, err)
			}
			out.Socials = append(out.Socials, *converted)
		}
	}
	if m.Details != nil {
		converted, err := m.Details.ToClientModel()
		if err != nil {
			return out, fmt.Errorf("details: %w", err)
		}
		out.Details = converted
	}
	if !m.Country.IsNull() && !m.Country.IsUnknown() {
		Country := m.Country.ValueString()
		out.Country = &Country
	}
	if m.FeatureSettings != nil {
		converted, err := m.FeatureSettings.ToClientModel()
		if err != nil {
			return out, fmt.Errorf("feature_settings: %w", err)
		}
		out.FeatureSettings = converted
	}
	if m.SubscriptionSettings != nil {
		converted, err := m.SubscriptionSettings.ToClientModel()
		if err != nil {
			return out, fmt.Errorf("subscription_settings: %w", err)
		}
		out.SubscriptionSettings = converted
	}
	if m.CustomerEmailSettings != nil {
		converted, err := m.CustomerEmailSettings.ToClientModel()
		if err != nil {
			return out, fmt.Errorf("customer_email_settings: %w", err)
		}
		out.CustomerEmailSettings = converted
	}
	if m.CustomerPortalSettings != nil {
		converted, err := m.CustomerPortalSettings.ToClientModel()
		if err != nil {
			return out, fmt.Errorf("customer_portal_settings: %w", err)
		}
		out.CustomerPortalSettings = converted
	}
	if !m.DefaultPresentmentCurrency.IsNull() && !m.DefaultPresentmentCurrency.IsUnknown() {
		DefaultPresentmentCurrency := m.DefaultPresentmentCurrency.ValueString()
		out.DefaultPresentmentCurrency = &DefaultPresentmentCurrency
	}
	if !m.DefaultTaxBehavior.IsNull() && !m.DefaultTaxBehavior.IsUnknown() {
		DefaultTaxBehavior := m.DefaultTaxBehavior.ValueString()
		out.DefaultTaxBehavior = &DefaultTaxBehavior
	}
	return out, nil
}

// ToUpdateModel converts a Terraform model to the UPDATE client model, which is
// a different shape from the create one: an update body may declare neither the
// nested blocks the create takes nor the id, and sending the create model to the
// patch endpoint is answered with "provided request body content is not in the
// expected format".
//
// Fields the patch model does not declare are simply absent here -- the
// generator only emits the ones it has.
func (m *OrganizationModel) ToUpdateModel() (*client.OrganizationUpdate, error) {
	out := &client.OrganizationUpdate{}
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		Name := m.Name.ValueString()
		out.Name = &Name
	}
	if !m.AvatarUrl.IsNull() && !m.AvatarUrl.IsUnknown() {
		AvatarUrl := m.AvatarUrl.ValueString()
		out.AvatarUrl = &AvatarUrl
	}
	if !m.Email.IsNull() && !m.Email.IsUnknown() {
		Email := m.Email.ValueString()
		out.Email = &Email
	}
	if !m.Website.IsNull() && !m.Website.IsUnknown() {
		Website := m.Website.ValueString()
		out.Website = &Website
	}
	if len(m.Socials) > 0 {
		out.Socials = make([]client.OrganizationSocialLink, 0, len(m.Socials))
		for index := range m.Socials {
			converted, err := m.Socials[index].ToClientModel()
			if err != nil {
				return out, fmt.Errorf("socials[%d]: %w", index, err)
			}
			out.Socials = append(out.Socials, *converted)
		}
	}
	if m.Details != nil {
		converted, err := m.Details.ToClientModel()
		if err != nil {
			return out, fmt.Errorf("details: %w", err)
		}
		out.Details = converted
	}
	if !m.Country.IsNull() && !m.Country.IsUnknown() {
		Country := m.Country.ValueString()
		out.Country = &Country
	}
	if m.SubscriptionSettings != nil {
		converted, err := m.SubscriptionSettings.ToClientModel()
		if err != nil {
			return out, fmt.Errorf("subscription_settings: %w", err)
		}
		out.SubscriptionSettings = converted
	}
	if m.CustomerEmailSettings != nil {
		converted, err := m.CustomerEmailSettings.ToClientModel()
		if err != nil {
			return out, fmt.Errorf("customer_email_settings: %w", err)
		}
		out.CustomerEmailSettings = converted
	}
	if m.CustomerPortalSettings != nil {
		converted, err := m.CustomerPortalSettings.ToClientModel()
		if err != nil {
			return out, fmt.Errorf("customer_portal_settings: %w", err)
		}
		out.CustomerPortalSettings = converted
	}
	if !m.DefaultPresentmentCurrency.IsNull() && !m.DefaultPresentmentCurrency.IsUnknown() {
		DefaultPresentmentCurrency := m.DefaultPresentmentCurrency.ValueString()
		out.DefaultPresentmentCurrency = &DefaultPresentmentCurrency
	}
	if !m.DefaultTaxBehavior.IsNull() && !m.DefaultTaxBehavior.IsUnknown() {
		DefaultTaxBehavior := m.DefaultTaxBehavior.ValueString()
		out.DefaultTaxBehavior = &DefaultTaxBehavior
	}
	return out, nil
}

// FromClientModel updates the Terraform model from a client model, for a
// RESOURCE: an attribute that is Optional alone is written only where the
// configuration already said something.
//
// OPTIONAL ALONE MEANS THE CONFIGURATION OWNS IT. A value the plan left null and
// the read then answers is "Provider produced inconsistent result after apply",
// on every apply -- so a position the create body does not insist on is filled
// in here only if it was filled in there. The positions where the SERVER fills
// it in are the ones that are Optional AND Computed, and those are written
// unconditionally.
func (m *OrganizationModel) FromClientModel(c *client.Organization) {
	m.fromAnswer(c, false)
}

// WHETHER THIS STATE CAME FROM AN IMPORT rather than from an apply.
//
// ImportState is a passthrough of the identifier: after it, state carries the id
// and nothing else, and only then does the framework call Read. FromClientModel's
// guard -- which exists so a refresh cannot clobber what the configuration said --
// therefore skips every writable attribute, leaving them null. The next plan then
// proposes to ADD url, format and events to a webhook endpoint that already has
// all three, and shows `name` going to (known after apply) when the server has a
// name for it.
//
// So: the identifier is set and nothing the create body owns is. That is an
// import, and an import wants everything the server answered.
func (m *OrganizationModel) importing() bool {
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		return false
	}
	if !m.Slug.IsNull() && !m.Slug.IsUnknown() {
		return false
	}
	if !m.AvatarUrl.IsNull() && !m.AvatarUrl.IsUnknown() {
		return false
	}
	if m.LegalEntity != nil {
		return false
	}
	if !m.Email.IsNull() && !m.Email.IsUnknown() {
		return false
	}
	if !m.Website.IsNull() && !m.Website.IsUnknown() {
		return false
	}
	if len(m.Socials) > 0 {
		return false
	}
	if m.Details != nil {
		return false
	}
	if !m.Country.IsNull() && !m.Country.IsUnknown() {
		return false
	}
	if m.FeatureSettings != nil {
		return false
	}
	if m.SubscriptionSettings != nil {
		return false
	}
	if m.CustomerEmailSettings != nil {
		return false
	}
	if m.CustomerPortalSettings != nil {
		return false
	}
	if !m.DefaultPresentmentCurrency.IsNull() && !m.DefaultPresentmentCurrency.IsUnknown() {
		return false
	}
	if !m.DefaultTaxBehavior.IsNull() && !m.DefaultTaxBehavior.IsUnknown() {
		return false
	}
	return true
}

// FromAnswer writes every attribute the server answered, which is what a DATA
// SOURCE wants: there is no configuration behind it to disagree with, and its
// schema says Computed for everything but the identifier it was given.
func (m *OrganizationModel) FromAnswer(c *client.Organization) {
	m.fromAnswer(c, true)
}

func (m *OrganizationModel) fromAnswer(c *client.Organization, everything bool) {
	// NIL IS ABSENT. The server omitted it, so state says null rather than
	// Go's zero -- otherwise the next plan proposes removing a value nobody set.
	if c.Id != nil {
		m.Id = types.StringValue(*c.Id)
	} else {
		m.Id = types.StringNull()
	}
	if everything || !m.Name.IsNull() && !m.Name.IsUnknown() {
		// NIL IS ABSENT. The server omitted it, so state says null rather than
		// Go's zero -- otherwise the next plan proposes removing a value nobody set.
		if c.Name != nil {
			m.Name = types.StringValue(*c.Name)
		} else {
			m.Name = types.StringNull()
		}
	}
	// NIL IS ABSENT. The server omitted it, so state says null rather than
	// Go's zero -- otherwise the next plan proposes removing a value nobody set.
	if c.Slug != nil {
		m.Slug = types.StringValue(*c.Slug)
	} else {
		m.Slug = types.StringNull()
	}
	if everything || !m.AvatarUrl.IsNull() && !m.AvatarUrl.IsUnknown() {
		// NIL IS ABSENT. The server omitted it, so state says null rather than
		// Go's zero -- otherwise the next plan proposes removing a value nobody set.
		if c.AvatarUrl != nil {
			m.AvatarUrl = types.StringValue(*c.AvatarUrl)
		} else {
			m.AvatarUrl = types.StringNull()
		}
	}
	if everything || !m.Email.IsNull() && !m.Email.IsUnknown() {
		// NIL IS ABSENT. The server omitted it, so state says null rather than
		// Go's zero -- otherwise the next plan proposes removing a value nobody set.
		if c.Email != nil {
			m.Email = types.StringValue(*c.Email)
		} else {
			m.Email = types.StringNull()
		}
	}
	if everything || !m.Website.IsNull() && !m.Website.IsUnknown() {
		// NIL IS ABSENT. The server omitted it, so state says null rather than
		// Go's zero -- otherwise the next plan proposes removing a value nobody set.
		if c.Website != nil {
			m.Website = types.StringValue(*c.Website)
		} else {
			m.Website = types.StringNull()
		}
	}
	if everything || m.Socials != nil {
		// REBUILT FROM THE ANSWER, and the order is the server's. A list attribute
		// compares element by element, so a server that reorders or adds a price is
		// a diff -- which is correct: it did something the configuration did not say.
		Socials := make([]OrganizationSocialsModel, 0, len(c.Socials))
		for index := range c.Socials {
			block := OrganizationSocialsModel{}
			if index < len(m.Socials) {
				block = m.Socials[index]
			}
			block.FromClientModel(&c.Socials[index])
			Socials = append(Socials, block)
		}
		m.Socials = Socials
	}
	if everything || !m.Country.IsNull() && !m.Country.IsUnknown() {
		// NIL IS ABSENT. The server omitted it, so state says null rather than
		// Go's zero -- otherwise the next plan proposes removing a value nobody set.
		if c.Country != nil {
			m.Country = types.StringValue(*c.Country)
		} else {
			m.Country = types.StringNull()
		}
	}
	if everything || m.FeatureSettings != nil {
		// A pointer the server left nil is a block that is not there. Writing an
		// empty one instead would be a diff against a configuration that correctly
		// omitted it.
		if c.FeatureSettings != nil {
			block := OrganizationFeatureSettingsModel{}
			if m.FeatureSettings != nil {
				block = *m.FeatureSettings
			}
			block.FromClientModel(c.FeatureSettings)
			m.FeatureSettings = &block
		} else {
			m.FeatureSettings = nil
		}
	}
	if everything || m.SubscriptionSettings != nil {
		// A pointer the server left nil is a block that is not there. Writing an
		// empty one instead would be a diff against a configuration that correctly
		// omitted it.
		if c.SubscriptionSettings != nil {
			block := OrganizationSubscriptionSettingsModel{}
			if m.SubscriptionSettings != nil {
				block = *m.SubscriptionSettings
			}
			block.FromClientModel(c.SubscriptionSettings)
			m.SubscriptionSettings = &block
		} else {
			m.SubscriptionSettings = nil
		}
	}
	if everything || m.CustomerEmailSettings != nil {
		// A pointer the server left nil is a block that is not there. Writing an
		// empty one instead would be a diff against a configuration that correctly
		// omitted it.
		if c.CustomerEmailSettings != nil {
			block := OrganizationCustomerEmailSettingsModel{}
			if m.CustomerEmailSettings != nil {
				block = *m.CustomerEmailSettings
			}
			block.FromClientModel(c.CustomerEmailSettings)
			m.CustomerEmailSettings = &block
		} else {
			m.CustomerEmailSettings = nil
		}
	}
	// A pointer the server left nil is a block that is not there. Writing an
	// empty one instead would be a diff against a configuration that correctly
	// omitted it.
	if c.CustomerPortalSettings != nil {
		block := OrganizationCustomerPortalSettingsModel{}
		if m.CustomerPortalSettings != nil {
			block = *m.CustomerPortalSettings
		}
		block.FromClientModel(c.CustomerPortalSettings)
		m.CustomerPortalSettings = &block
	} else {
		m.CustomerPortalSettings = nil
	}
	if everything || !m.DefaultPresentmentCurrency.IsNull() && !m.DefaultPresentmentCurrency.IsUnknown() {
		// NIL IS ABSENT. The server omitted it, so state says null rather than
		// Go's zero -- otherwise the next plan proposes removing a value nobody set.
		if c.DefaultPresentmentCurrency != nil {
			m.DefaultPresentmentCurrency = types.StringValue(*c.DefaultPresentmentCurrency)
		} else {
			m.DefaultPresentmentCurrency = types.StringNull()
		}
	}
	if everything || !m.DefaultTaxBehavior.IsNull() && !m.DefaultTaxBehavior.IsUnknown() {
		// NIL IS ABSENT. The server omitted it, so state says null rather than
		// Go's zero -- otherwise the next plan proposes removing a value nobody set.
		if c.DefaultTaxBehavior != nil {
			m.DefaultTaxBehavior = types.StringValue(*c.DefaultTaxBehavior)
		} else {
			m.DefaultTaxBehavior = types.StringNull()
		}
	}
}
