// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/n-at-han-k/terraform-provider-polar/internal/client"
)

// ProductModel is the Terraform model for product.
type ProductModel struct {
	Id                     types.String                       `tfsdk:"id"`
	IsArchived             types.Bool                         `tfsdk:"is_archived"`
	Metadata               types.Map                          `tfsdk:"metadata"`
	Name                   types.String                       `tfsdk:"name"`
	Description            types.String                       `tfsdk:"description"`
	Visibility             types.String                       `tfsdk:"visibility"`
	Prices                 []ProductPricesModel               `tfsdk:"prices"`
	Medias                 types.List                         `tfsdk:"medias"`
	AttachedCustomFields   []ProductAttachedCustomFieldsModel `tfsdk:"attached_custom_fields"`
	TrialInterval          types.String                       `tfsdk:"trial_interval"`
	TrialIntervalCount     types.Int64                        `tfsdk:"trial_interval_count"`
	RecurringInterval      types.String                       `tfsdk:"recurring_interval"`
	RecurringIntervalCount types.Int64                        `tfsdk:"recurring_interval_count"`
	MeterInterval          types.String                       `tfsdk:"meter_interval"`
	MeterIntervalCount     types.Int64                        `tfsdk:"meter_interval_count"`
}

// ProductPricesModel is one `prices` block.
//
// A STRUCT WITH tfsdk TAGS, not a types.Object: terraform-plugin-framework
// reflects over these, so a slice of them is a ListNestedAttribute and a
// pointer to one is a SingleNestedAttribute, with no AttributeTypes map to keep
// in step with the fields by hand.
type ProductPricesModel struct {
	PriceCurrency types.String `tfsdk:"price_currency"`
	TaxBehavior   types.String `tfsdk:"tax_behavior"`
	PriceAmount   types.Int64  `tfsdk:"price_amount"`
	MinimumAmount types.Int64  `tfsdk:"minimum_amount"`
	MaximumAmount types.Int64  `tfsdk:"maximum_amount"`
	PresetAmount  types.Int64  `tfsdk:"preset_amount"`
	MeterId       types.String `tfsdk:"meter_id"`
	UnitAmount    types.String `tfsdk:"unit_amount"`
	CapAmount     types.Int64  `tfsdk:"cap_amount"`
	AmountType    types.String `tfsdk:"amount_type"`
}

// ToClientModel converts one block to the client type the request carries.
func (m *ProductPricesModel) ToClientModel() (*client.ProductCreateRecurringPrices, error) {
	out := &client.ProductCreateRecurringPrices{}
	if !m.PriceCurrency.IsNull() && !m.PriceCurrency.IsUnknown() {
		PriceCurrency := m.PriceCurrency.ValueString()
		out.PriceCurrency = &PriceCurrency
	}
	if !m.TaxBehavior.IsNull() && !m.TaxBehavior.IsUnknown() {
		TaxBehavior := m.TaxBehavior.ValueString()
		out.TaxBehavior = &TaxBehavior
	}
	if !m.PriceAmount.IsNull() && !m.PriceAmount.IsUnknown() {
		PriceAmount := int32(m.PriceAmount.ValueInt64())
		out.PriceAmount = &PriceAmount
	}
	if !m.MinimumAmount.IsNull() && !m.MinimumAmount.IsUnknown() {
		MinimumAmount := int32(m.MinimumAmount.ValueInt64())
		out.MinimumAmount = &MinimumAmount
	}
	if !m.MaximumAmount.IsNull() && !m.MaximumAmount.IsUnknown() {
		MaximumAmount := int32(m.MaximumAmount.ValueInt64())
		out.MaximumAmount = &MaximumAmount
	}
	if !m.PresetAmount.IsNull() && !m.PresetAmount.IsUnknown() {
		PresetAmount := int32(m.PresetAmount.ValueInt64())
		out.PresetAmount = &PresetAmount
	}
	if !m.MeterId.IsNull() && !m.MeterId.IsUnknown() {
		MeterId := m.MeterId.ValueString()
		out.MeterId = &MeterId
	}
	if !m.UnitAmount.IsNull() && !m.UnitAmount.IsUnknown() {
		UnitAmount := m.UnitAmount.ValueString()
		out.UnitAmount = &UnitAmount
	}
	if !m.CapAmount.IsNull() && !m.CapAmount.IsUnknown() {
		CapAmount := int32(m.CapAmount.ValueInt64())
		out.CapAmount = &CapAmount
	}
	if !m.AmountType.IsNull() && !m.AmountType.IsUnknown() {
		out.AmountType = m.AmountType.ValueString()
	}
	return out, nil
}

// FromClientModel fills one block from what the server answered.
//
// A DIFFERENT CLIENT TYPE FROM THE ONE IT SENDS: this block's children describe
// what Polar answers, and the request carries its own -- see `responseBlocks` in
// the generator configuration. The struct is the same either way, so the two
// conversions have the same fields to work with and do not.
func (m *ProductPricesModel) FromClientModel(c *client.CheckoutPricesValueInner) {
	m.PriceCurrency = types.StringValue(c.PriceCurrency)
	// NIL IS ABSENT. The server omitted it, so state says null rather than
	// Go's zero -- otherwise the next plan proposes removing a value nobody set.
	if c.TaxBehavior != nil {
		m.TaxBehavior = types.StringValue(*c.TaxBehavior)
	} else {
		m.TaxBehavior = types.StringNull()
	}
	// NIL IS ABSENT. The server omitted it, so state says null rather than
	// Go's zero -- otherwise the next plan proposes removing a value nobody set.
	if c.PriceAmount != nil {
		m.PriceAmount = types.Int64Value(int64(*c.PriceAmount))
	} else {
		m.PriceAmount = types.Int64Null()
	}
	// NIL IS ABSENT. The server omitted it, so state says null rather than
	// Go's zero -- otherwise the next plan proposes removing a value nobody set.
	if c.MinimumAmount != nil {
		m.MinimumAmount = types.Int64Value(int64(*c.MinimumAmount))
	} else {
		m.MinimumAmount = types.Int64Null()
	}
	// NIL IS ABSENT. The server omitted it, so state says null rather than
	// Go's zero -- otherwise the next plan proposes removing a value nobody set.
	if c.MaximumAmount != nil {
		m.MaximumAmount = types.Int64Value(int64(*c.MaximumAmount))
	} else {
		m.MaximumAmount = types.Int64Null()
	}
	// NIL IS ABSENT. The server omitted it, so state says null rather than
	// Go's zero -- otherwise the next plan proposes removing a value nobody set.
	if c.PresetAmount != nil {
		m.PresetAmount = types.Int64Value(int64(*c.PresetAmount))
	} else {
		m.PresetAmount = types.Int64Null()
	}
	// NIL IS ABSENT. The server omitted it, so state says null rather than
	// Go's zero -- otherwise the next plan proposes removing a value nobody set.
	if c.MeterId != nil {
		m.MeterId = types.StringValue(*c.MeterId)
	} else {
		m.MeterId = types.StringNull()
	}
	// NIL IS ABSENT. The server omitted it, so state says null rather than
	// Go's zero -- otherwise the next plan proposes removing a value nobody set.
	if c.UnitAmount != nil {
		m.UnitAmount = types.StringValue(*c.UnitAmount)
	} else {
		m.UnitAmount = types.StringNull()
	}
	// NIL IS ABSENT. The server omitted it, so state says null rather than
	// Go's zero -- otherwise the next plan proposes removing a value nobody set.
	if c.CapAmount != nil {
		m.CapAmount = types.Int64Value(int64(*c.CapAmount))
	} else {
		m.CapAmount = types.Int64Null()
	}
	m.AmountType = types.StringValue(c.AmountType)
}

// ProductAttachedCustomFieldsModel is one `attached_custom_fields` block.
//
// A STRUCT WITH tfsdk TAGS, not a types.Object: terraform-plugin-framework
// reflects over these, so a slice of them is a ListNestedAttribute and a
// pointer to one is a SingleNestedAttribute, with no AttributeTypes map to keep
// in step with the fields by hand.
type ProductAttachedCustomFieldsModel struct {
	CustomFieldId types.String `tfsdk:"custom_field_id"`
	Required      types.Bool   `tfsdk:"required"`
}

// ToClientModel converts one block to the client type the request carries.
func (m *ProductAttachedCustomFieldsModel) ToClientModel() (*client.AttachedCustomFieldCreate, error) {
	out := &client.AttachedCustomFieldCreate{}
	if !m.CustomFieldId.IsNull() && !m.CustomFieldId.IsUnknown() {
		out.CustomFieldId = m.CustomFieldId.ValueString()
	}
	if !m.Required.IsNull() && !m.Required.IsUnknown() {
		Required := m.Required.ValueBool()
		out.Required = &Required
	}
	return out, nil
}

// FromClientModel fills one block from what the server answered.
//
// EVERY CHILD IS WRITTEN, not only the ones the configuration set, because they
// are Optional AND Computed: Polar fills in a price's currency and tax
// behaviour, and a Computed attribute left unknown after an apply is "provider
// returned invalid result object after apply".
func (m *ProductAttachedCustomFieldsModel) FromClientModel(c *client.AttachedCustomFieldCreate) {
	m.CustomFieldId = types.StringValue(c.CustomFieldId)
	if c.Required != nil {
		m.Required = types.BoolValue(*c.Required)
	} else {
		m.Required = types.BoolNull()
	}
}

// ToClientModel converts a Terraform model to a client model.
func (m *ProductModel) ToClientModel() (*client.ProductCreate, error) {
	out := &client.ProductCreate{}
	if !m.Metadata.IsNull() && !m.Metadata.IsUnknown() {
		out.Metadata = make(map[string]string, len(m.Metadata.Elements()))
		for key, element := range m.Metadata.Elements() {
			out.Metadata[key] = element.(types.String).ValueString()
		}
	}
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		Name := m.Name.ValueString()
		out.Name = &Name
	}
	if !m.Description.IsNull() && !m.Description.IsUnknown() {
		Description := m.Description.ValueString()
		out.Description = &Description
	}
	if !m.Visibility.IsNull() && !m.Visibility.IsUnknown() {
		Visibility := m.Visibility.ValueString()
		out.Visibility = &Visibility
	}
	if len(m.Prices) > 0 {
		out.Prices = make([]client.ProductCreateRecurringPrices, 0, len(m.Prices))
		for index := range m.Prices {
			converted, err := m.Prices[index].ToClientModel()
			if err != nil {
				return out, fmt.Errorf("prices[%d]: %w", index, err)
			}
			out.Prices = append(out.Prices, *converted)
		}
	}
	// ELEMENT BY ELEMENT, so no conversion needs a context: types.ListValueFrom
	// takes one and these functions have none to give.
	if !m.Medias.IsNull() && !m.Medias.IsUnknown() {
		out.Medias = make([]string, 0, len(m.Medias.Elements()))
		for _, element := range m.Medias.Elements() {
			out.Medias = append(out.Medias, element.(types.String).ValueString())
		}
	}
	if len(m.AttachedCustomFields) > 0 {
		out.AttachedCustomFields = make([]client.AttachedCustomFieldCreate, 0, len(m.AttachedCustomFields))
		for index := range m.AttachedCustomFields {
			converted, err := m.AttachedCustomFields[index].ToClientModel()
			if err != nil {
				return out, fmt.Errorf("attached_custom_fields[%d]: %w", index, err)
			}
			out.AttachedCustomFields = append(out.AttachedCustomFields, *converted)
		}
	}
	if !m.TrialInterval.IsNull() && !m.TrialInterval.IsUnknown() {
		TrialInterval := m.TrialInterval.ValueString()
		out.TrialInterval = &TrialInterval
	}
	if !m.TrialIntervalCount.IsNull() && !m.TrialIntervalCount.IsUnknown() {
		TrialIntervalCount := int32(m.TrialIntervalCount.ValueInt64())
		out.TrialIntervalCount = &TrialIntervalCount
	}
	if !m.RecurringInterval.IsNull() && !m.RecurringInterval.IsUnknown() {
		RecurringInterval := m.RecurringInterval.ValueString()
		out.RecurringInterval = &RecurringInterval
	}
	if !m.RecurringIntervalCount.IsNull() && !m.RecurringIntervalCount.IsUnknown() {
		RecurringIntervalCount := int32(m.RecurringIntervalCount.ValueInt64())
		out.RecurringIntervalCount = &RecurringIntervalCount
	}
	if !m.MeterInterval.IsNull() && !m.MeterInterval.IsUnknown() {
		MeterInterval := m.MeterInterval.ValueString()
		out.MeterInterval = &MeterInterval
	}
	if !m.MeterIntervalCount.IsNull() && !m.MeterIntervalCount.IsUnknown() {
		MeterIntervalCount := int32(m.MeterIntervalCount.ValueInt64())
		out.MeterIntervalCount = &MeterIntervalCount
	}
	return out, nil
}

// ToUpdateModel converts a Terraform model to the UPDATE client model, which is
// a different shape from the create one: an update body may declare neither the
// nested blocks the create takes nor the id, and sending the create model to the
// patch endpoint is answered with "provided request body content is not in the
// expected format".
//
// Fields the patch model does not declare are simply absent here -- the
// generator only emits the ones it has.
func (m *ProductModel) ToUpdateModel() (*client.ProductUpdate, error) {
	out := &client.ProductUpdate{}
	if !m.IsArchived.IsNull() && !m.IsArchived.IsUnknown() {
		IsArchived := m.IsArchived.ValueBool()
		out.IsArchived = &IsArchived
	}
	if !m.Metadata.IsNull() && !m.Metadata.IsUnknown() {
		out.Metadata = make(map[string]string, len(m.Metadata.Elements()))
		for key, element := range m.Metadata.Elements() {
			out.Metadata[key] = element.(types.String).ValueString()
		}
	}
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		Name := m.Name.ValueString()
		out.Name = &Name
	}
	if !m.Description.IsNull() && !m.Description.IsUnknown() {
		Description := m.Description.ValueString()
		out.Description = &Description
	}
	if !m.Visibility.IsNull() && !m.Visibility.IsUnknown() {
		Visibility := m.Visibility.ValueString()
		out.Visibility = &Visibility
	}
	// ELEMENT BY ELEMENT, so no conversion needs a context: types.ListValueFrom
	// takes one and these functions have none to give.
	if !m.Medias.IsNull() && !m.Medias.IsUnknown() {
		out.Medias = make([]string, 0, len(m.Medias.Elements()))
		for _, element := range m.Medias.Elements() {
			out.Medias = append(out.Medias, element.(types.String).ValueString())
		}
	}
	if len(m.AttachedCustomFields) > 0 {
		out.AttachedCustomFields = make([]client.AttachedCustomFieldCreate, 0, len(m.AttachedCustomFields))
		for index := range m.AttachedCustomFields {
			converted, err := m.AttachedCustomFields[index].ToClientModel()
			if err != nil {
				return out, fmt.Errorf("attached_custom_fields[%d]: %w", index, err)
			}
			out.AttachedCustomFields = append(out.AttachedCustomFields, *converted)
		}
	}
	if !m.TrialInterval.IsNull() && !m.TrialInterval.IsUnknown() {
		TrialInterval := m.TrialInterval.ValueString()
		out.TrialInterval = &TrialInterval
	}
	if !m.TrialIntervalCount.IsNull() && !m.TrialIntervalCount.IsUnknown() {
		TrialIntervalCount := int32(m.TrialIntervalCount.ValueInt64())
		out.TrialIntervalCount = &TrialIntervalCount
	}
	if !m.RecurringInterval.IsNull() && !m.RecurringInterval.IsUnknown() {
		RecurringInterval := m.RecurringInterval.ValueString()
		out.RecurringInterval = &RecurringInterval
	}
	if !m.RecurringIntervalCount.IsNull() && !m.RecurringIntervalCount.IsUnknown() {
		RecurringIntervalCount := int32(m.RecurringIntervalCount.ValueInt64())
		out.RecurringIntervalCount = &RecurringIntervalCount
	}
	return out, nil
}

// FromClientModel updates the Terraform model from a client model, for a
// RESOURCE: an attribute that is Optional alone is written only where the
// configuration already said something.
//
// OPTIONAL ALONE MEANS THE CONFIGURATION OWNS IT. A value the plan left null and
// the read then answers is "Provider produced inconsistent result after apply",
// on every apply -- so a position the create body does not insist on is filled
// in here only if it was filled in there. The positions where the SERVER fills
// it in are the ones that are Optional AND Computed, and those are written
// unconditionally.
func (m *ProductModel) FromClientModel(c *client.Product) {
	m.fromAnswer(c, false)
}

// WHETHER THIS STATE CAME FROM AN IMPORT rather than from an apply.
//
// ImportState is a passthrough of the identifier: after it, state carries the id
// and nothing else, and only then does the framework call Read. FromClientModel's
// guard -- which exists so a refresh cannot clobber what the configuration said --
// therefore skips every writable attribute, leaving them null. The next plan then
// proposes to ADD url, format and events to a webhook endpoint that already has
// all three, and shows `name` going to (known after apply) when the server has a
// name for it.
//
// So: the identifier is set and nothing the create body owns is. That is an
// import, and an import wants everything the server answered.
func (m *ProductModel) importing() bool {
	if !m.Metadata.IsNull() && !m.Metadata.IsUnknown() {
		return false
	}
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		return false
	}
	if !m.Description.IsNull() && !m.Description.IsUnknown() {
		return false
	}
	if !m.Visibility.IsNull() && !m.Visibility.IsUnknown() {
		return false
	}
	if len(m.Prices) > 0 {
		return false
	}
	if !m.Medias.IsNull() && !m.Medias.IsUnknown() {
		return false
	}
	if len(m.AttachedCustomFields) > 0 {
		return false
	}
	if !m.TrialInterval.IsNull() && !m.TrialInterval.IsUnknown() {
		return false
	}
	if !m.TrialIntervalCount.IsNull() && !m.TrialIntervalCount.IsUnknown() {
		return false
	}
	if !m.RecurringInterval.IsNull() && !m.RecurringInterval.IsUnknown() {
		return false
	}
	if !m.RecurringIntervalCount.IsNull() && !m.RecurringIntervalCount.IsUnknown() {
		return false
	}
	if !m.MeterInterval.IsNull() && !m.MeterInterval.IsUnknown() {
		return false
	}
	if !m.MeterIntervalCount.IsNull() && !m.MeterIntervalCount.IsUnknown() {
		return false
	}
	return true
}

// FromAnswer writes every attribute the server answered, which is what a DATA
// SOURCE wants: there is no configuration behind it to disagree with, and its
// schema says Computed for everything but the identifier it was given.
func (m *ProductModel) FromAnswer(c *client.Product) {
	m.fromAnswer(c, true)
}

func (m *ProductModel) fromAnswer(c *client.Product, everything bool) {
	// NIL IS ABSENT. The server omitted it, so state says null rather than
	// Go's zero -- otherwise the next plan proposes removing a value nobody set.
	if c.Id != nil {
		m.Id = types.StringValue(*c.Id)
	} else {
		m.Id = types.StringNull()
	}
	// A bool the server does not answer leaves the pointer nil, and a Computed
	// attribute is UNKNOWN in the plan -- "provider still indicated an unknown
	// value ... all values must be known after apply". Unknown becomes null; a
	// value the plan already knows is left alone.
	if c.IsArchived != nil {
		m.IsArchived = types.BoolValue(*c.IsArchived)
	} else if m.IsArchived.IsUnknown() {
		m.IsArchived = types.BoolNull()
	}
	if c.Metadata == nil {
		m.Metadata = types.MapNull(types.StringType)
	} else {
		Metadata := make(map[string]attr.Value, len(c.Metadata))
		for key, element := range c.Metadata {
			Metadata[key] = types.StringValue(element)
		}
		m.Metadata = types.MapValueMust(types.StringType, Metadata)
	}
	if everything || !m.Name.IsNull() && !m.Name.IsUnknown() {
		// NIL IS ABSENT. The server omitted it, so state says null rather than
		// Go's zero -- otherwise the next plan proposes removing a value nobody set.
		if c.Name != nil {
			m.Name = types.StringValue(*c.Name)
		} else {
			m.Name = types.StringNull()
		}
	}
	if everything || !m.Description.IsNull() && !m.Description.IsUnknown() {
		// NIL IS ABSENT. The server omitted it, so state says null rather than
		// Go's zero -- otherwise the next plan proposes removing a value nobody set.
		if c.Description != nil {
			m.Description = types.StringValue(*c.Description)
		} else {
			m.Description = types.StringNull()
		}
	}
	// NIL IS ABSENT. The server omitted it, so state says null rather than
	// Go's zero -- otherwise the next plan proposes removing a value nobody set.
	if c.Visibility != nil {
		m.Visibility = types.StringValue(*c.Visibility)
	} else {
		m.Visibility = types.StringNull()
	}
	if everything || m.Prices != nil {
		// REBUILT FROM THE ANSWER, and the order is the server's. A list attribute
		// compares element by element, so a server that reorders or adds a price is
		// a diff -- which is correct: it did something the configuration did not say.
		Prices := make([]ProductPricesModel, 0, len(c.Prices))
		for index := range c.Prices {
			block := ProductPricesModel{}
			if index < len(m.Prices) {
				block = m.Prices[index]
			}
			block.FromClientModel(&c.Prices[index])
			Prices = append(Prices, block)
		}
		m.Prices = Prices
	}
	// The create body takes this and no response of the same shape answers it --
	// AssociationRequest against AssociationResponse -- so nothing above writes
	// it, and a Computed attribute the configuration left out stays UNKNOWN once
	// the apply is over: "provider returned invalid result object after apply".
	// Unknown becomes null; a value the plan already knows is left alone.
	if m.Medias.IsUnknown() {
		m.Medias = types.ListNull(types.StringType)
	}
	if everything || !m.TrialInterval.IsNull() && !m.TrialInterval.IsUnknown() {
		// NIL IS ABSENT. The server omitted it, so state says null rather than
		// Go's zero -- otherwise the next plan proposes removing a value nobody set.
		if c.TrialInterval != nil {
			m.TrialInterval = types.StringValue(*c.TrialInterval)
		} else {
			m.TrialInterval = types.StringNull()
		}
	}
	if everything || !m.TrialIntervalCount.IsNull() && !m.TrialIntervalCount.IsUnknown() {
		// NIL IS ABSENT. The server omitted it, so state says null rather than
		// Go's zero -- otherwise the next plan proposes removing a value nobody set.
		if c.TrialIntervalCount != nil {
			m.TrialIntervalCount = types.Int64Value(int64(*c.TrialIntervalCount))
		} else {
			m.TrialIntervalCount = types.Int64Null()
		}
	}
	if everything || !m.RecurringInterval.IsNull() && !m.RecurringInterval.IsUnknown() {
		// NIL IS ABSENT. The server omitted it, so state says null rather than
		// Go's zero -- otherwise the next plan proposes removing a value nobody set.
		if c.RecurringInterval != nil {
			m.RecurringInterval = types.StringValue(*c.RecurringInterval)
		} else {
			m.RecurringInterval = types.StringNull()
		}
	}
	// NIL IS ABSENT. The server omitted it, so state says null rather than
	// Go's zero -- otherwise the next plan proposes removing a value nobody set.
	if c.RecurringIntervalCount != nil {
		m.RecurringIntervalCount = types.Int64Value(int64(*c.RecurringIntervalCount))
	} else {
		m.RecurringIntervalCount = types.Int64Null()
	}
	if everything || !m.MeterInterval.IsNull() && !m.MeterInterval.IsUnknown() {
		// NIL IS ABSENT. The server omitted it, so state says null rather than
		// Go's zero -- otherwise the next plan proposes removing a value nobody set.
		if c.MeterInterval != nil {
			m.MeterInterval = types.StringValue(*c.MeterInterval)
		} else {
			m.MeterInterval = types.StringNull()
		}
	}
	if everything || !m.MeterIntervalCount.IsNull() && !m.MeterIntervalCount.IsUnknown() {
		// NIL IS ABSENT. The server omitted it, so state says null rather than
		// Go's zero -- otherwise the next plan proposes removing a value nobody set.
		if c.MeterIntervalCount != nil {
			m.MeterIntervalCount = types.Int64Value(int64(*c.MeterIntervalCount))
		} else {
			m.MeterIntervalCount = types.Int64Null()
		}
	}
}
