// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"context"
	"fmt"

	"encoding/json"


	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	"github.com/n-at-han-k/terraform-provider-polar/internal/client"
)

var _ datasource.DataSource = &ProductDataSource{}

func NewProductDataSource() datasource.DataSource {
	return &ProductDataSource{}
}

type ProductDataSource struct {
	client *client.Client
}

func (d *ProductDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_product"
}

func (d *ProductDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Fetches a product data source.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:    true,
				Description: "The ID of the object.",
			},
			"created_at": schema.StringAttribute{
				Computed:    true,
				Description: "Creation timestamp of the object.",
			},
			"modified_at": schema.StringAttribute{
				Computed:    true,
				Description: "Last modification timestamp of the object.",
			},
			"trial_interval": schema.StringAttribute{
				Computed:    true,
				Description: "The interval unit for the trial period.",
			},
			"trial_interval_count": schema.Int64Attribute{
				Computed:    true,
				Description: "The number of interval units for the trial period.",
			},
			"name": schema.StringAttribute{
				Computed:    true,
				Description: "The name of the product.",
			},
			"description": schema.StringAttribute{
				Computed:    true,
				Description: "The description of the product.",
			},
			"visibility": schema.StringAttribute{
				Computed:    true,
				Description: "The visibility of the product.",
			},
			"recurring_interval": schema.StringAttribute{
				Computed:    true,
				Description: "The recurring interval of the product. If `None`, the product is a one-time purchase.",
			},
			"recurring_interval_count": schema.Int64Attribute{
				Computed:    true,
				Description: "Number of interval units of the subscription. If this is set to 1 the charge will happen every interval (e.g. every month), if set to 2 it will be every other month, and so on. None for one-time products.",
			},
			"meter_interval": schema.StringAttribute{
				Computed:    true,
				Description: "The meter cycle of the product, independent of the billing interval. If `None`, metered concerns follow the billing interval.",
			},
			"meter_interval_count": schema.Int64Attribute{
				Computed:    true,
				Description: "Number of meter interval units. None when no meter cycle is set.",
			},
			"is_recurring": schema.BoolAttribute{
				Computed:    true,
				Description: "Whether the product is a subscription.",
			},
			"is_archived": schema.BoolAttribute{
				Computed:    true,
				Description: "Whether the product is archived and no longer available.",
			},
			"organization_id": schema.StringAttribute{
				Computed:    true,
				Description: "The ID of the organization owning the product.",
			},
			"metadata": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"prices": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "List of prices for this product.",
			},
			"benefits": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "List of benefits granted by the product.",
			},
			"medias": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "List of medias associated to the product.",
			},
			"attached_custom_fields": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "List of custom fields attached to the product.",
			},
		},
	}
}

func (d *ProductDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Data Source Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}

	d.client = c
}

func (d *ProductDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config ProductModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	respBody, err := d.client.DoRequest(ctx, "GET", fmt.Sprintf("/products/%v", config.Id.ValueString()), nil)
	if err != nil {
		resp.Diagnostics.AddError("Error reading product", err.Error())
		return
	}

	var result client.Product
	if err := json.Unmarshal(respBody, &result); err != nil {
		resp.Diagnostics.AddError("Error parsing response", err.Error())
		return
	}

	config.FromClientModel(&result)

	tflog.Trace(ctx, "read product data source")
	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
