// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"encoding/json"



	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"

	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"

	"github.com/hashicorp/terraform-plugin-log/tflog"



	"github.com/n-at-han-k/terraform-provider-polar/internal/client"
)

var _ resource.Resource = &SubscriptionResource{}
var _ resource.ResourceWithImportState = &SubscriptionResource{}

func NewSubscriptionResource() resource.Resource {
	return &SubscriptionResource{}
}

type SubscriptionResource struct {
	client *client.Client
}

func (r *SubscriptionResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_subscription"
}

func (r *SubscriptionResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a subscription resource.",
		Attributes: map[string]schema.Attribute{
			"created_at": schema.StringAttribute{
				Computed:    true,
				Description: "Creation timestamp of the object.",
			},
			"modified_at": schema.StringAttribute{
				Computed:    true,
				Description: "Last modification timestamp of the object.",
			},
			"id": schema.StringAttribute{
				Computed:    true,
				Description: "The ID of the object.",
			},
			"amount": schema.Int64Attribute{
				Computed:    true,
				Description: "The amount of the subscription.",
			},
			"currency": schema.StringAttribute{
				Computed:    true,
				Description: "The currency of the subscription.",
			},
			"recurring_interval": schema.StringAttribute{
				Computed:    true,
				Description: "The interval at which the subscription recurs.",
			},
			"recurring_interval_count": schema.Int64Attribute{
				Computed:    true,
				Description: "Number of interval units of the subscription. If this is set to 1 the charge will happen every interval (e.g. every month), if set to 2 it will be every other month, and so on.",
			},
			"status": schema.StringAttribute{
				Computed:    true,
				Description: "The status of the subscription.",
			},
			"current_period_start": schema.StringAttribute{
				Computed:    true,
				Description: "The start timestamp of the current billing period.",
			},
			"current_period_end": schema.StringAttribute{
				Computed:    true,
				Description: "The end timestamp of the current billing period.",
			},
			"current_meter_period_start": schema.StringAttribute{
				Computed:    true,
				Description: "The start timestamp of the current meter period, if the product has a meter cycle set. Metered credits are granted and overage is settled on this cadence.",
			},
			"current_meter_period_end": schema.StringAttribute{
				Computed:    true,
				Description: "The end timestamp of the current meter period, if the product has a meter cycle set. This is when credits next renew.",
			},
			"trial_start": schema.StringAttribute{
				Computed:    true,
				Description: "The start timestamp of the trial period, if any.",
			},
			"trial_end": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: "The end timestamp of the trial period, if any.",
			},
			"cancel_at_period_end": schema.BoolAttribute{
				Required:    true,
				Description: "Whether the subscription will be canceled at the end of the current period.",
			},
			"canceled_at": schema.StringAttribute{
				Computed:    true,
				Description: "The timestamp when the subscription was canceled. The subscription might still be active if `cancel_at_period_end` is `true`.",
			},
			"started_at": schema.StringAttribute{
				Computed:    true,
				Description: "The timestamp when the subscription started.",
			},
			"ends_at": schema.StringAttribute{
				Computed:    true,
				Description: "The timestamp when the subscription will end.",
			},
			"ended_at": schema.StringAttribute{
				Computed:    true,
				Description: "The timestamp when the subscription ended.",
			},
			"past_due_at": schema.StringAttribute{
				Computed:    true,
				Description: "The timestamp when the subscription entered `past_due` status.",
			},
			"pause_at_period_end": schema.BoolAttribute{
				Required:    true,
				Description: "Whether the subscription will be paused at the end of the current period.",
			},
			"paused_at": schema.StringAttribute{
				Computed:    true,
				Description: "The timestamp when the subscription was paused.",
			},
			"resumes_at": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: "The timestamp when a paused subscription is scheduled to automatically resume, if set.",
			},
			"customer_id": schema.StringAttribute{
				Computed:    true,
				Description: "The ID of the subscribed customer.",
			},
			"product_id": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: "The ID of the subscribed product.",
			},
			"discount_id": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: "The ID of the applied discount, if any.",
			},
			"checkout_id": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"seats": schema.Int64Attribute{
				Required:    true,
				Description: "The number of seats for seat-based subscriptions. None for non-seat subscriptions.",
			},
			"customer_cancellation_reason": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: "",
			},
			"customer_cancellation_comment": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: "",
			},
			"metadata": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"custom_field_data": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "Key-value object storing custom field values.",
			},
			"customer": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"product": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"discount": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"prices": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "List of enabled prices for the subscription.",
			},
			"meters": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "List of meters associated with the subscription.",
			},
			"pending_update": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "Pending subscription update that will be applied at the beginning of the next period. If `null`, there is no pending update.",
			},
			"proration_behavior": schema.StringAttribute{
				Optional:    true,
				Description: "Determine how to handle the proration billing. If not provided, will use the default organization setting.",
			},
			"current_billing_period_end": schema.StringAttribute{
				Required:    true,
				Description: "Set a new date for the end of the current billing period. The subscription will renew on this date. The new date can be earlier or later than the current period end, as long as it's in the future.  It is not possible to update the current billing period on a canceled subscription.",
			},
			"revoke": schema.BoolAttribute{
				Required:    true,
				Description: "Cancel and revoke an active subscription immediately",
			},
			"resume": schema.BoolAttribute{
				Required:    true,
				Description: "Resume a paused subscription immediately, starting a new billing period and charging the customer.",
			},
		},
	}
}

func (r *SubscriptionResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}

	r.client = c
}

func (r *SubscriptionResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	resp.Diagnostics.AddError("Not Supported", "Create is not supported for subscription")
}

func (r *SubscriptionResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state SubscriptionModel

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// A resource with no identifier is not a resource. Without this the read
	// interpolates an empty id and asks the COLLECTION endpoint, which answers
	// 200 and a list -- so a state written before the id was known would look
	// healthy forever instead of being adopted again.
	if state.Id.ValueString() == "" {
		resp.State.RemoveResource(ctx)
		return
	}

	respBody, err := r.client.DoRequest(ctx, "GET", fmt.Sprintf("/subscriptions/%v", state.Id.ValueString()), nil)
	if err != nil {
		// GONE IS NOT BROKEN. A 404 here means the resource this state row
		// describes no longer exists -- deleted by hand, or by something else
		// that owns it -- and the honest answer is to drop the row and let the
		// plan decide whether to recreate it. Raising instead fails every plan
		// in the configuration, including the ones with nothing to do with this
		// resource, and leaves no way out but editing state by hand.
		//
		// ONLY IN Read. The same 404 after a create or an update is a real
		// failure: something we just wrote is missing.
		var apiErr *client.APIError
		if errors.As(err, &apiErr) && apiErr.StatusCode == http.StatusNotFound {
			resp.State.RemoveResource(ctx)
			return
		}

		resp.Diagnostics.AddError("Error reading subscription", err.Error())
		return
	}

	var result client.Subscription
	if err := json.Unmarshal(respBody, &result); err != nil {
		resp.Diagnostics.AddError("Error parsing response", err.Error())
		return
	}

	state.FromClientModel(&result)

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *SubscriptionResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan SubscriptionModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// The identifiers come off state: they cannot change on an update, and the
	// plan's copy of a Computed one is unknown -- which is also the only place
	// an imported nested resource's parents live.
	var state SubscriptionModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	reqBody, err := plan.ToClientModel()
	if err != nil {
		resp.Diagnostics.AddError("Invalid subscription configuration", err.Error())
		return
	}

	respBody, err := r.client.DoRequest(ctx, "PATCH", fmt.Sprintf("/subscriptions/%v", state.Id.ValueString()), reqBody)
	if err != nil {
		resp.Diagnostics.AddError("Error updating subscription", err.Error())
		return
	}

	// AN UPDATE'S ANSWER IS NOT THE READ'S. RT answers a PUT with the list of
	// changes it made -- ["Description changed from 'a' to 'b'"] -- and some
	// updates answer nothing at all; neither is the resource, and
	// unmarshalling either one is "Error parsing response" AFTER the server
	// has already accepted the change. What it now looks like is read back.
	respBody, err = r.client.DoRequest(ctx, "GET", fmt.Sprintf("/subscriptions/%v", state.Id.ValueString()), nil)
	if err != nil {
		resp.Diagnostics.AddError("Error reading back the updated subscription", err.Error())
		return
	}

	if len(respBody) > 0 {
		var result client.Subscription
		if err := json.Unmarshal(respBody, &result); err != nil {
			resp.Diagnostics.AddError("Error parsing response", err.Error())
			return
		}

		plan.FromClientModel(&result)
	}

	tflog.Trace(ctx, "updated subscription resource")
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *SubscriptionResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state SubscriptionModel

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	_, err := r.client.DoRequest(ctx, "DELETE", fmt.Sprintf("/subscriptions/%v", state.Id.ValueString()), nil)
	if err != nil {
		resp.Diagnostics.AddError("Error deleting subscription", err.Error())
		return
	}

	tflog.Trace(ctx, "deleted subscription resource")
}

func (r *SubscriptionResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
